"""
Cargo Scaling Lua-mod deployer.

Writes a runnable `CryovacCargoScaling/` UE4SS Lua mod folder the user (or
anyone downloading the deployable) can drop into `ue4ss/Mods/`. The mod
reshapes FCargoRow.PaymentPer1KmMultiplierByMaxWeight on the live
`Cargos_01` DataTable at session start.

Why Lua and not Balance.json:
  Balance.json Cargo.PaymentMultipliers is a flat per-cargo-type
  multiplier — it can't change the pickup-vs-box-truck slope. The slope
  lives in the DataTable field above. The DataTable is in UE5
  unversioned-properties format with no .usmap schema we can parse, so
  we can't round-trip it as a pak'd uasset. Runtime Lua (via UE4SS
  reflection) is the only workable path.

Modes:
  Vanilla — no modification (scalar 1.0× on weight_mult).
  Low     — halve the weight_mult (scalar 0.5×). Bigger trucks earn
            ~60% more per unit than vanilla at a given capacity.
  High    — amplify the weight_mult (scalar 1.5×). Bigger trucks earn
            less than vanilla. Small-vehicle pay is unchanged.
  Off     — remove the weight_mult entirely (scalar 0.0×). Every
            vehicle size earns the small-vehicle rate for the same cargo.

Anchor preservation:
  All modes preserve the small-vehicle pay because the game formula
  reduces to base × f(weight_mult, cap) where f(x, cap_min) ≈ 1
  regardless of weight_mult. Scaling weight_mult only affects how
  steeply pay declines as vehicle capacity grows past the cargo's
  minimum-fit size.
"""
import json
import logging
import os
import shutil
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


CARGO_SCALING_MODES = ('Vanilla', 'Low', 'High', 'Off')

MODE_WEIGHT_FACTOR = {
    'Vanilla': 1.0,
    'Low':     0.5,
    'High':    1.5,
    'Off':     0.0,
}

MOD_FOLDER_NAME = 'CryovacCargoScaling'

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT_DIR = os.path.join(_PROJECT_ROOT, 'data', 'lua_mod_output')


# ---------------------------------------------------------------------------
# main.lua template
# ---------------------------------------------------------------------------
_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Cargo Scaling
    ======================
    Reshapes the per-vehicle cargo-payment penalty that makes small
    trucks earn more per unit than big trucks for the same cargo.

    The lever is FCargoRow.PaymentSqrtRatio (vanilla = 1.0 on most
    rows). Scaling it reshapes the penalty:

      Vanilla : 1.0x  (no change — default penalty)
      Low     : 0.5x  (gentler penalty — big trucks earn more per unit)
      High    : 1.5x  (steeper penalty — big trucks earn less)
      Off     : 0.0x  (no penalty — every vehicle earns the small-
                       truck rate for the same cargo)

    Matches the field the NexusMods #90 pak mod modifies.

    Target DataTables: both Cargos.uasset (CompositeDataTable) AND
    Cargos_01.uasset (DataTable). Both get the modification to cover
    whichever the game consults at payment-calc time.

    Small-vehicle pay is unchanged under any mode — the penalty only
    bites as vehicle capacity exceeds the cargo's natural fit size.

    Generated by Frog Mod Editor. Mode is hardcoded below — regenerate
    the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

-- ============================================================
-- Configuration (regenerate via Frog Mod Editor to change)
-- ============================================================
local CONFIG = {{
    Mode = "{mode}",

    -- Scale applied to FCargoRow.PaymentSqrtRatio.
    ModeFactor = {{
        Vanilla = 1.0,
        Low     = 0.5,
        High    = 1.5,
        Off     = 0.0,
    }},

    TargetDTSubstring  = "/Cargos",
    ExcludeDTSubstring = "Deprecated",

    InitialDelayMs = 15000,
}}

-- ============================================================
-- Helpers
-- ============================================================
local function Log(msg) print("[CryovacCargoScaling] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- ============================================================
-- Find matching Cargo DataTables (both Cargos and Cargos_01)
-- ============================================================
local function FindCargoDTs()
    local dts = FindAllOf("DataTable")
    if not dts then return {{}} end
    local count = 0
    pcall(function() count = #dts end)
    local matched = {{}}
    for i = 1, count do
        local dt = dts[i]
        local fullName = ""
        pcall(function() fullName = dt:GetFullName() end)
        if string.find(fullName, CONFIG.TargetDTSubstring, 1, true)
           and not string.find(fullName, CONFIG.ExcludeDTSubstring, 1, true) then
            matched[#matched + 1] = {{ dt = dt, name = fullName }}
        end
    end
    return matched
end

-- ============================================================
-- Apply scaling to all rows across all matched tables
--   (idempotent via applied flag + per-table-row baseline cache)
-- ============================================================
local applied = false
local vanilla_baseline = {{}}   -- [table_name][row_name] = original sqrt_ratio

local function ApplyScaling()
    if applied then return true end

    local mode = CONFIG.Mode
    local factor = CONFIG.ModeFactor[mode]
    if factor == nil then
        Log("Unknown mode: " .. tostring(mode) .. " - aborting.")
        applied = true
        return true
    end

    if mode == "Vanilla" then
        Log("Mode=Vanilla - no modifications applied.")
        applied = true
        return true
    end

    local matched = FindCargoDTs()
    if #matched == 0 then return false end

    local total_mods = 0
    local sampleLogged = 0

    for _, m in ipairs(matched) do
        local dt, fullName = m.dt, m.name

        local rowNames = nil
        pcall(function() rowNames = dt:GetRowNames() end)
        if not rowNames then
            Log(string.format("%s: GetRowNames failed; will retry.", fullName))
            return false
        end

        local n = 0
        pcall(function() n = #rowNames end)
        if n == 0 then
            Log(string.format("%s: 0 rows; will retry.", fullName))
            return false
        end

        Log(string.format("Matched %s (%d rows). Mode=%s (sqrt_ratio x%s)",
            fullName, n, mode, tostring(factor)))

        vanilla_baseline[fullName] = vanilla_baseline[fullName] or {{}}
        local baselineTbl = vanilla_baseline[fullName]

        local thisTableMods = 0
        for i = 1, n do
            local rowName = rowNames[i]
            local struct = nil
            pcall(function()
                struct = dt:FindRow(rowName, "CargoScaling", false)
            end)
            if struct then
                local key = tostring(rowName)
                if baselineTbl[key] == nil then
                    baselineTbl[key] = SafeGet(struct, "PaymentSqrtRatio")
                end
                local baseSqrt = baselineTbl[key]
                if type(baseSqrt) == "number" then
                    local newSqrt = baseSqrt * factor
                    pcall(function()
                        struct.PaymentSqrtRatio = newSqrt
                    end)
                    if sampleLogged < 6 then
                        local verify = SafeGet(struct, "PaymentSqrtRatio")
                        Log(string.format("  [%s] %s: sqrt_ratio %.3f -> %.3f",
                            fullName:match("([^%.]+)$") or fullName,
                            key, baseSqrt, verify or 0))
                        sampleLogged = sampleLogged + 1
                    end
                    thisTableMods = thisTableMods + 1
                end
            end
        end

        Log(string.format("  -> Applied %s to %d rows in %s.",
            mode, thisTableMods, fullName))
        total_mods = total_mods + thisTableMods
    end

    Log(string.format("Applied %s to %d rows across %d table(s).",
        mode, total_mods, #matched))
    applied = true
    return true
end

-- ============================================================
-- Init
-- ============================================================
Log("=== Cryovac Cargo Scaling Loading ===")
Log(string.format("Mode: %s  (PaymentSqrtRatio x%s)",
    CONFIG.Mode, tostring(CONFIG.ModeFactor[CONFIG.Mode] or "?")))
Log(string.format("Target substring: %s (excluding: %s)",
    CONFIG.TargetDTSubstring, CONFIG.ExcludeDTSubstring))

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyScaling() then
        LoopAsync(5000, function() return ApplyScaling() end)
    end
end)

Log("=== Cryovac Cargo Scaling Loaded ===")
'''


# ---------------------------------------------------------------------------
# README / install instructions
# ---------------------------------------------------------------------------
_README_TEMPLATE = '''CryovacCargoScaling
===================

Selected mode: {mode} (weight-penalty scalar x{factor})

WHAT THIS MOD DOES
------------------
Reshapes how per-unit cargo payment scales with vehicle capacity on
Motor Town. At the cargo's minimum-fit vehicle size, pay is unchanged
from vanilla. As trucks get bigger, the mode controls how quickly
per-unit pay drops off:

  Vanilla  1.0x  Default Motor Town penalty. No change.
  Low      0.5x  Half the penalty slope - big trucks catch up.
  High     1.5x  Steeper penalty - big trucks earn even less.
  Off      0.0x  No penalty at all - every truck earns the small-vehicle
                 rate for the same cargo.

To switch modes, regenerate this mod from Frog Mod Editor with a
different selection and overwrite this folder.


PREREQUISITE: UE4SS
-------------------
This mod runs through UE4SS (Unreal Engine Scripting System). Without
UE4SS installed in Motor Town, the mod will not load.

1. Download the latest UE4SS release:
     https://github.com/UE4SS-RE/RE-UE4SS/releases
   (Look for a file named like UE4SS_v3.0.1.zip. Pick the
   non-experimental build unless you know you need otherwise.)

2. Extract the zip directly into Motor Town's Binaries/Win64 folder:
     <Motor Town install>\\MotorTown\\Binaries\\Win64\\
   After extraction this folder will contain (among other files):
     dwmapi.dll
     UE4SS.dll
     UE4SS-settings.ini
     ue4ss\\
   The `ue4ss` subfolder is where mods live.

   If you can't find your install folder: in Steam, right-click Motor
   Town -> Manage -> Browse local files. That is `<Motor Town install>`.
   The Binaries/Win64 folder is inside it.


INSTALL THIS MOD
----------------
1. Copy the entire CryovacCargoScaling folder (this folder) into:
     <Motor Town install>\\MotorTown\\Binaries\\Win64\\ue4ss\\Mods\\

   The final path should look like:
     ...\\Binaries\\Win64\\ue4ss\\Mods\\CryovacCargoScaling\\enabled.txt
     ...\\Binaries\\Win64\\ue4ss\\Mods\\CryovacCargoScaling\\Scripts\\main.lua

2. Enable the mod in UE4SS's mods.txt:
     ...\\Binaries\\Win64\\ue4ss\\Mods\\mods.txt

   Open that file and add this line (before the "Built-in keybinds"
   comment if present):
     CryovacCargoScaling : 1

3. Launch Motor Town as normal. UE4SS loads automatically. The mod
   waits 15 seconds after world load and then applies the selected
   mode. If the DataTable isn't ready yet, it retries every 5 seconds.


VERIFYING IT LOADED
-------------------
- UE4SS opens a console window on launch. Look for lines tagged
  [CryovacCargoScaling] - you should see the mode, row count, and a
  sample of before/after weight_mult values.
- If you don't see a console, open UE4SS-settings.ini in Binaries/Win64
  and set GuiConsoleVisible = 1 (under [Debug]).
- Alternatively, check the log at:
    ...\\Binaries\\Win64\\ue4ss\\UE4SS.log


UNINSTALLING
------------
1. Delete the CryovacCargoScaling folder from ue4ss/Mods/.
2. Remove its line from mods.txt (or set it to : 0).
3. Relaunch the game. Vanilla cargo scaling returns.


NOTES
-----
- This mod runs server-side. For multiplayer, install on the host /
  dedicated server. Clients do not need it.
- The mod captures each row's vanilla PaymentPer1KmMultiplierByMaxWeight
  once per session as its baseline, so re-applying (e.g. through a Lua
  reload) will not compound the effect.
- Only affects the `Cargos_01` DataTable. Future game updates adding
  new cargo tables may need this mod updated.

Generated by Frog Mod Editor.
'''


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def generate_main_lua(mode: str) -> str:
    """Return the main.lua source for the given mode.

    The template has a doubled-brace Lua table literal; `.format()` turns
    `{{` into `{`. Only {mode} is substituted.
    """
    if mode not in CARGO_SCALING_MODES:
        raise ValueError(
            f"Unknown cargo scaling mode: {mode!r}. "
            f"Expected one of: {CARGO_SCALING_MODES}"
        )
    return _MAIN_LUA_TEMPLATE.format(mode=mode)


def generate_readme(mode: str) -> str:
    """Return the README.txt content describing install steps + mode."""
    if mode not in CARGO_SCALING_MODES:
        raise ValueError(f"Unknown cargo scaling mode: {mode!r}")
    return _README_TEMPLATE.format(
        mode=mode,
        factor=MODE_WEIGHT_FACTOR[mode],
    )


def deploy(mode: str, output_dir: Optional[str] = None,
           overwrite: bool = True) -> Dict[str, Any]:
    """Write the `CryovacCargoScaling/` mod folder with main.lua + README.

    Args:
        mode: One of CARGO_SCALING_MODES. Baked into main.lua as CONFIG.Mode.
        output_dir: Parent directory to write `CryovacCargoScaling/` into.
                    Defaults to data/lua_mod_output/ inside the project.
        overwrite: If True, replace an existing folder at the target.

    Returns:
        {'success': True,  'path': <mod_folder_path>,  'mode': <mode>}
        {'success': False, 'error': <message>}
    """
    if mode not in CARGO_SCALING_MODES:
        return {'success': False, 'error': f'Unknown mode: {mode!r}'}

    out_parent = output_dir or DEFAULT_OUTPUT_DIR
    mod_folder = os.path.join(out_parent, MOD_FOLDER_NAME)
    scripts_dir = os.path.join(mod_folder, 'Scripts')

    try:
        # Overwrite files in place rather than rm+recreate the tree — some
        # sandboxed filesystems (bindfs on the cowork mount) refuse unlink
        # even when the mkdir would otherwise succeed.
        os.makedirs(scripts_dir, exist_ok=True)

        # enabled.txt (UE4SS convention — empty file signals "load this mod")
        # Use os.open with O_TRUNC so we don't need to unlink first.
        enabled_path = os.path.join(mod_folder, 'enabled.txt')
        fd = os.open(enabled_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
        os.close(fd)

        # Scripts/main.lua
        with open(os.path.join(scripts_dir, 'main.lua'), 'w',
                  encoding='utf-8', newline='\n') as f:
            f.write(generate_main_lua(mode))

        # README.txt — shipped alongside the mod for whoever installs it
        with open(os.path.join(mod_folder, 'README.txt'), 'w',
                  encoding='utf-8') as f:
            f.write(generate_readme(mode))

        # Stamp the selected mode for programmatic inspection too
        with open(os.path.join(mod_folder, 'mod_info.json'), 'w',
                  encoding='utf-8') as f:
            json.dump({
                'mod_name': MOD_FOLDER_NAME,
                'mode': mode,
                'weight_factor': MODE_WEIGHT_FACTOR[mode],
                'generated_by': 'Frog Mod Editor',
            }, f, indent=2)

        logger.info("Deployed %s (mode=%s) to %s",
                    MOD_FOLDER_NAME, mode, mod_folder)
        return {'success': True, 'path': mod_folder, 'mode': mode}
    except Exception as e:
        logger.warning("Deploy failed: %s", e)
        return {'success': False, 'error': str(e)}


def get_install_instructions(mode: str) -> str:
    """Return the README text for display in a Qt dialog."""
    return generate_readme(mode)
