"""Shared helpers for every Lua-mod deployer.

Writing files via os.open(..., O_TRUNC) instead of shutil.rmtree + rewrite
sidesteps the bindfs permission issue we hit on the cowork mount when
redeploying into the same output folder.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict

logger = logging.getLogger(__name__)


UE4SS_RELEASE_URL = 'https://github.com/UE4SS-RE/RE-UE4SS/releases'


# The install-instructions block below is identical across mods except for
# the mod folder name. Callers supply that name; everything else is shared.
_README_TEMPLATE = """{mod_name}
{heading_underline}

{body}

PREREQUISITE: UE4SS
-------------------
This mod runs through UE4SS (Unreal Engine Scripting System). Without
UE4SS installed in Motor Town, the mod will not load.

1. Download the latest UE4SS release:
     {ue4ss_url}
   (Look for a file named like UE4SS_v3.0.1.zip. Pick the
   non-experimental build unless you know you need otherwise.)

2. Extract the zip directly into Motor Town's Binaries/Win64 folder:
     <Motor Town install>\\MotorTown\\Binaries\\Win64\\
   After extraction this folder will contain (among other files):
     dwmapi.dll
     UE4SS.dll
     UE4SS-settings.ini
     ue4ss\\
   The `ue4ss` subfolder is where mods live.

   If you can't find your install folder: in Steam, right-click Motor
   Town -> Manage -> Browse local files. That is <Motor Town install>.
   The Binaries/Win64 folder is inside it.


INSTALL THIS MOD
----------------
1. Copy the entire {mod_name} folder (this folder) into:
     <Motor Town install>\\MotorTown\\Binaries\\Win64\\ue4ss\\Mods\\

   The final path should look like:
     ...\\Binaries\\Win64\\ue4ss\\Mods\\{mod_name}\\enabled.txt
     ...\\Binaries\\Win64\\ue4ss\\Mods\\{mod_name}\\Scripts\\main.lua

2. Enable the mod in UE4SS's mods.txt:
     ...\\Binaries\\Win64\\ue4ss\\Mods\\mods.txt

   Open that file and add this line (before the "Built-in keybinds"
   comment if present):
     {mod_name} : 1

3. Launch Motor Town as normal. UE4SS loads automatically. Check
   ue4ss\\UE4SS.log or the UE4SS console for [{mod_name}] log entries.


UNINSTALLING
------------
1. Delete the {mod_name} folder from ue4ss/Mods/.
2. Remove its line from mods.txt (or set it to : 0).
3. Relaunch the game. Vanilla behavior returns.


NOTES
-----
- To reconfigure this mod, regenerate it from Frog Mod Editor with new
  settings and overwrite this folder. The mod captures vanilla values
  on first apply, so baselines are preserved across runs.
- This mod runs server-side. For multiplayer, install on the host /
  dedicated server. Clients do not need it.

Generated by Frog Mod Editor.
"""


def render_install_readme(mod_name: str, body: str) -> str:
    """Stitch the per-mod intro `body` into the shared install template."""
    heading = '=' * len(mod_name)
    return _README_TEMPLATE.format(
        mod_name=mod_name,
        heading_underline=heading,
        body=body.rstrip(),
        ue4ss_url=UE4SS_RELEASE_URL,
    )


# Standard UE4SS built-in mods shipped with every RE-UE4SS install,
# with their out-of-the-box enable/disable defaults. We include these
# in any mods.txt we generate so the file is drop-in usable for a
# fresh UE4SS installation; users with existing mods.txt files can
# also just copy the "Cryovac" section out of ours.
_UE4SS_BUILTIN_MOD_LINES = [
    'CheatManagerEnablerMod : 1',
    'ActorDumperMod : 0',
    'ConsoleCommandsMod : 1',
    'ConsoleEnablerMod : 1',
    'SplitScreenMod : 0',
    'LineTraceMod : 0',
    'BPModLoaderMod : 1',
    'BPML_GenericFunctions : 1',
    'jsbLuaProfilerMod : 0',
]

# Every mods.txt must end with the Keybinds entry AFTER the
# "do not move up" comment — UE4SS wants this exact tail.
_UE4SS_KEYBINDS_TAIL = [
    '',
    '; Built-in keybinds, do not move up!',
    'Keybinds : 1',
    '',
]


def generate_mods_txt(enabled_mod_names: list) -> str:
    """Render a complete UE4SS mods.txt containing the built-in mod
    lines, each deployed Cryovac mod as `Name : 1`, and the required
    Keybinds tail. Safe to drop straight into ue4ss/Mods/ for a clean
    install, or users can copy the Cryovac lines into their own file."""
    lines: list = []
    lines.append('; UE4SS built-in mods')
    lines.extend(_UE4SS_BUILTIN_MOD_LINES)
    if enabled_mod_names:
        lines.append('')
        lines.append('; Cryovac mods deployed by Frog Mod Editor')
        lines.append(
            '; (each line format: "ModName : 1" to enable, ": 0" to disable)'
        )
        for name in enabled_mod_names:
            lines.append(f'{name} : 1')
    lines.extend(_UE4SS_KEYBINDS_TAIL)
    return '\n'.join(lines)


def write_mods_txt(enabled_mod_names: list, output_dir: str) -> Dict[str, Any]:
    """Write the generated mods.txt to <output_dir>/mods.txt, overwriting
    any previous copy in place (os.O_TRUNC — see write_mod_folder)."""
    try:
        os.makedirs(output_dir, exist_ok=True)
        contents = generate_mods_txt(enabled_mod_names)
        path = os.path.join(output_dir, 'mods.txt')
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
        try:
            os.write(fd, contents.encode('utf-8'))
        finally:
            os.close(fd)
        return {'success': True, 'path': path, 'mod_count': len(enabled_mod_names)}
    except Exception as e:
        logger.warning("mods.txt write failed: %s", e)
        return {'success': False, 'error': str(e)}


def write_mod_folder(
    mod_name: str,
    output_dir: str,
    main_lua: str,
    readme: str,
    mod_info: Dict[str, Any],
) -> Dict[str, Any]:
    """Write a complete UE4SS mod folder (Scripts/main.lua + enabled.txt +
    README.txt + mod_info.json) at output_dir/mod_name/.

    Overwrites files in place — no rmtree — so redeploys don't trip the
    cowork bindfs unlink restriction.
    """
    mod_folder = os.path.join(output_dir, mod_name)
    scripts_dir = os.path.join(mod_folder, 'Scripts')
    try:
        os.makedirs(scripts_dir, exist_ok=True)

        # enabled.txt — UE4SS convention, empty file signals "load this mod"
        enabled_path = os.path.join(mod_folder, 'enabled.txt')
        fd = os.open(enabled_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
        os.close(fd)

        main_path = os.path.join(scripts_dir, 'main.lua')
        with open(main_path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(main_lua)

        with open(os.path.join(mod_folder, 'README.txt'), 'w', encoding='utf-8') as f:
            f.write(readme)

        with open(os.path.join(mod_folder, 'mod_info.json'), 'w', encoding='utf-8') as f:
            json.dump({'mod_name': mod_name, 'generated_by': 'Frog Mod Editor', **mod_info},
                      f, indent=2)

        logger.info("Deployed %s to %s", mod_name, mod_folder)
        return {'success': True, 'path': mod_folder}
    except Exception as e:
        logger.warning("Deploy failed for %s: %s", mod_name, e)
        return {'success': False, 'error': str(e)}
