"""Cryovac Cargo Scaling — reshapes FCargoRow.PaymentSqrtRatio on both
Cargos.Cargos (CompositeDataTable) and Cargos_01.Cargos_01 (DataTable)."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, ModeOption, Setting, MODE_FACTOR_OPTIONS
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCargoScaling'

UI_TITLE = 'Vehicle Capacity Penalty'

UI_DESCRIPTION = (
    "Reshapes how per-unit cargo payment drops as vehicle capacity grows. "
    "Small-vehicle pay is identical under every mode — only the decay slope "
    "changes.\n\n"
    "<b>Vanilla</b> keeps the default pickup-vs-truck penalty.<br>"
    "<b>Low</b> halves the penalty slope — big trucks catch up ~60% toward "
    "small-truck rates.<br>"
    "<b>High</b> 1.5× the penalty — big trucks earn less than vanilla.<br>"
    "<b>Off</b> flattens entirely — every vehicle size earns the small-truck "
    "rate for the same cargo.\n\n"
    "Modifies <code>FCargoRow.PaymentSqrtRatio</code> at runtime (requires UE4SS)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'mode': 'Off',
}

SETTINGS = [
    Setting(
        key='mode',
        label='Mode',
        kind='mode',
        default='Off',
        options=MODE_FACTOR_OPTIONS,
        tooltip='Factor applied to every cargo row\'s PaymentSqrtRatio.',
    ),
]


# ---------------------------------------------------------------------------
# Lua template
# ---------------------------------------------------------------------------
_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Cargo Scaling
    ======================
    Reshapes the per-vehicle cargo-payment penalty that makes small
    trucks earn more per unit than big trucks for the same cargo.

    The lever is FCargoRow.PaymentSqrtRatio (vanilla = 1.0 on most
    rows). Scaling it reshapes the penalty:

      Vanilla : 1.0x  (no change — default penalty)
      Low     : 0.5x  (gentler penalty — big trucks earn more per unit)
      High    : 1.5x  (steeper penalty — big trucks earn less)
      Off     : 0.0x  (no penalty — every vehicle earns the small-
                       truck rate for the same cargo)

    Target DataTables: both Cargos.uasset (CompositeDataTable) AND
    Cargos_01.uasset (DataTable). Small-vehicle pay is unchanged.

    Generated by Frog Mod Editor. Mode is hardcoded below — regenerate
    the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Mode = "{mode}",

    ModeFactor = {{
        Vanilla = 1.0,
        Low     = 0.5,
        High    = 1.5,
        Off     = 0.0,
    }},

    TargetDTSubstring  = "/Cargos",
    ExcludeDTSubstring = "Deprecated",

    InitialDelayMs = 15000,
}}

local function Log(msg) print("[CryovacCargoScaling] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function FindCargoDTs()
    local dts = FindAllOf("DataTable")
    if not dts then return {{}} end
    local count = 0
    pcall(function() count = #dts end)
    local matched = {{}}
    for i = 1, count do
        local dt = dts[i]
        local fullName = ""
        pcall(function() fullName = dt:GetFullName() end)
        if string.find(fullName, CONFIG.TargetDTSubstring, 1, true)
           and not string.find(fullName, CONFIG.ExcludeDTSubstring, 1, true) then
            matched[#matched + 1] = {{ dt = dt, name = fullName }}
        end
    end
    return matched
end

local applied = false
local vanilla_baseline = {{}}

local function ApplyScaling()
    if applied then return true end
    local mode = CONFIG.Mode
    local factor = CONFIG.ModeFactor[mode]
    if factor == nil then
        Log("Unknown mode: " .. tostring(mode) .. " - aborting.")
        applied = true
        return true
    end
    if mode == "Vanilla" then
        Log("Mode=Vanilla - no modifications applied.")
        applied = true
        return true
    end
    local matched = FindCargoDTs()
    if #matched == 0 then return false end

    local total_mods = 0
    local sampleLogged = 0

    for _, m in ipairs(matched) do
        local dt, fullName = m.dt, m.name
        local rowNames = nil
        pcall(function() rowNames = dt:GetRowNames() end)
        if not rowNames then
            Log(string.format("%s: GetRowNames failed; will retry.", fullName))
            return false
        end
        local n = 0
        pcall(function() n = #rowNames end)
        if n == 0 then
            Log(string.format("%s: 0 rows; will retry.", fullName))
            return false
        end
        Log(string.format("Matched %s (%d rows). Mode=%s (sqrt_ratio x%s)",
            fullName, n, mode, tostring(factor)))

        vanilla_baseline[fullName] = vanilla_baseline[fullName] or {{}}
        local baselineTbl = vanilla_baseline[fullName]
        local thisTableMods = 0
        for i = 1, n do
            local rowName = rowNames[i]
            local struct = nil
            pcall(function() struct = dt:FindRow(rowName, "CargoScaling", false) end)
            if struct then
                local key = tostring(rowName)
                if baselineTbl[key] == nil then
                    baselineTbl[key] = SafeGet(struct, "PaymentSqrtRatio")
                end
                local baseSqrt = baselineTbl[key]
                if type(baseSqrt) == "number" then
                    local newSqrt = baseSqrt * factor
                    pcall(function() struct.PaymentSqrtRatio = newSqrt end)
                    if sampleLogged < 6 then
                        local verify = SafeGet(struct, "PaymentSqrtRatio")
                        Log(string.format("  [%s] %s: sqrt_ratio %.3f -> %.3f",
                            fullName:match("([^%.]+)$") or fullName,
                            key, baseSqrt, verify or 0))
                        sampleLogged = sampleLogged + 1
                    end
                    thisTableMods = thisTableMods + 1
                end
            end
        end
        Log(string.format("  -> Applied %s to %d rows in %s.",
            mode, thisTableMods, fullName))
        total_mods = total_mods + thisTableMods
    end
    Log(string.format("Applied %s to %d rows across %d table(s).",
        mode, total_mods, #matched))
    applied = true
    return true
end

Log("=== Cryovac Cargo Scaling Loading ===")
Log(string.format("Mode: %s  (PaymentSqrtRatio x%s)",
    CONFIG.Mode, tostring(CONFIG.ModeFactor[CONFIG.Mode] or "?")))
Log(string.format("Target substring: %s (excluding: %s)",
    CONFIG.TargetDTSubstring, CONFIG.ExcludeDTSubstring))

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyScaling() then
        LoopAsync(5000, function() return ApplyScaling() end)
    end
end)

Log("=== Cryovac Cargo Scaling Loaded ===")
'''


def generate_main_lua(config: Dict[str, Any]) -> str:
    mode = config.get('mode', DEFAULT_CONFIG['mode'])
    if mode not in {opt.key for opt in MODE_FACTOR_OPTIONS}:
        raise ValueError(f"Unknown cargo scaling mode: {mode!r}")
    return _MAIN_LUA_TEMPLATE.format(mode=mode)


def generate_readme(config: Dict[str, Any]) -> str:
    mode = config.get('mode', DEFAULT_CONFIG['mode'])
    factor = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}[mode]
    body = (
        f"Selected mode: {mode} (PaymentSqrtRatio scalar \u00d7{factor})\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Reshapes how per-unit cargo payment scales with vehicle capacity.\n"
        "At the cargo's minimum-fit vehicle size, pay is unchanged from\n"
        "vanilla. As trucks get bigger, the selected mode controls how\n"
        "quickly per-unit pay drops off:\n\n"
        "  Vanilla  1.0x  Default Motor Town penalty. No change.\n"
        "  Low      0.5x  Half the penalty slope - big trucks catch up.\n"
        "  High     1.5x  Steeper penalty - big trucks earn even less.\n"
        "  Off      0.0x  No penalty - every vehicle earns the small-vehicle\n"
        "                 rate for the same cargo.\n\n"
        "To switch modes, regenerate from Frog Mod Editor and overwrite\n"
        "this folder."
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    mode = config.get('mode', DEFAULT_CONFIG['mode'])
    factor = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}[mode]
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'mode': mode, 'sqrt_ratio_factor': factor},
    )


import sys as _sys
register(_sys.modules[__name__])
