"""Cryovac Cargo Volume Boost — scales DumpVolume on every live
UMTVehicleCargoSpaceComponent whose CargoSpaceType matches one of the
targeted families (Tanker, Dump, DryBulk, Garbage). Polls every
5 seconds so freshly-spawned vehicles get the boost too.

This is the runtime Lua equivalent of the old "More Cargo" pak mod
(which was a static asset override of specific vehicle Blueprints).
Using Lua instead means: one mod covers every vehicle of each type,
not just the single Blueprint the pak replaced, and you can retune
the multiplier without recompiling assets.
"""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCargoVolumeBoost'

UI_TITLE = 'Cargo Volume Boost'

UI_DESCRIPTION = (
    "Scales how much cargo the bulk/fluid vehicle classes can carry. "
    "One slider per truck family, because a 2\u00d7 dump might not be "
    "what you want on a fuel tanker.\n\n"
    "Each slider multiplies the <code>DumpVolume</code> field on every "
    "live <code>UMTVehicleCargoSpaceComponent</code> whose "
    "<code>CargoSpaceType</code> matches that family:\n"
    "<br>\u2022 <b>Tanker</b> \u2014 liquid fuel / oil / water tank trucks\n"
    "<br>\u2022 <b>Dump</b> \u2014 dump trucks (loose fill, not containerised)\n"
    "<br>\u2022 <b>Dry Bulk</b> \u2014 cement, sand, ore silo trucks\n"
    "<br>\u2022 <b>Garbage</b> \u2014 garbage compactor trucks\n\n"
    "Polls every 5 seconds so vehicles that spawn mid-session also "
    "get the boost. Baselines are captured per-instance on first "
    "apply so re-polling doesn't compound the multiplier.\n\n"
    "Other volume-based types (ConcreteMixer, LiveFishTanker, Grain, "
    "Log) are not touched by this mod \u2014 ask if you want them added."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'tanker_multiplier':   1.0,
    'dump_multiplier':     1.0,
    'dry_bulk_multiplier': 1.0,
    'garbage_multiplier':  1.0,
    'cap_weight_at_vanilla': False,
}


def _slider(key: str, label: str, tooltip: str) -> Setting:
    return Setting(
        key=key,
        label=label,
        kind='slider',
        default=1.0,
        min_value=1.0,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip=tooltip,
    )


SETTINGS = [
    _slider('tanker_multiplier',   'Tanker',
            'Multiplier on DumpVolume for Tanker-class cargo spaces.'),
    _slider('dump_multiplier',     'Dump',
            'Multiplier on DumpVolume for Dump-truck cargo spaces.'),
    _slider('dry_bulk_multiplier', 'Dry Bulk',
            'Multiplier on DumpVolume for DryBulk cargo spaces.'),
    _slider('garbage_multiplier',  'Garbage',
            'Multiplier on DumpVolume for Garbage compactor cargo spaces.'),
    Setting(
        key='cap_weight_at_vanilla',
        label='Ignore increased weight',
        kind='bool',
        default=False,
        tooltip='Keep each vehicle\'s cargo weight at the vanilla-volume '
                'equivalent, even when you fill it past vanilla capacity. '
                'Strongly recommended when using multipliers above 1.5\u00d7 '
                '\u2014 otherwise overloaded trucks slam the suspension to '
                'the ground.',
        hint='When checked, any fill past the vanilla DumpVolume contributes '
             'no extra weight. Volume is still boosted; only the physics mass '
             'stays at vanilla-loaded levels.',
    ),
]


# Values of the EMTCargoSpaceType enum we care about, matched against
# UMTVehicleCargoSpaceComponent.CargoSpaceType at runtime. Enum is
# uint8 so comparisons are cheap. Source of truth:
#   UHTHeaderDump/MotorTown/Public/EMTCargoSpaceType.h
# Invalid=0 Flatbed=1 Box=2 Dump=3 ConcreteMixer=4 Container=5
# Tanker=6 DryBulk=7 LiveFishTanker=8 Log=9 Garbage=10 CarCarrier=11
# Grain=12 Max=13
_ENUM_DUMP    = 3
_ENUM_TANKER  = 6
_ENUM_DRYBULK = 7
_ENUM_GARBAGE = 10


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Cargo Volume Boost
    ===========================
    Scales DumpVolume on every live UMTVehicleCargoSpaceComponent
    whose CargoSpaceType is Tanker (6), Dump (3), DryBulk (7), or
    Garbage (10). One multiplier per family.

    When CapWeightAtVanilla is true, any fill past the vanilla
    DumpVolume contributes no extra physics weight - the vehicle's
    Net_Cargo.CargoWeightKg is proportionally clamped to what the
    vanilla-volume load would have weighed. Stops the suspension
    from bottoming out on overloaded trucks.

    Baselines (per-component vanilla DumpVolume) are captured on
    first apply, so polling every 2s doesn't compound the effect.
    Freshly-spawned vehicles are baselined + scaled on the next poll.

    Generated by Frog Mod Editor. Config is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    TankerMultiplier   = {tanker_multiplier},
    DumpMultiplier     = {dump_multiplier},
    DryBulkMultiplier  = {dry_bulk_multiplier},
    GarbageMultiplier  = {garbage_multiplier},
    CapWeightAtVanilla = {cap_weight_at_vanilla},

    -- EMTCargoSpaceType enum values we target. Anything not in this
    -- map is ignored (Box, Flatbed, Container, Log, CarCarrier, etc.)
    TypeMultipliers = {{
        [3]  = nil,  -- Dump     (set below so Lua sees the CONFIG values)
        [6]  = nil,  -- Tanker
        [7]  = nil,  -- DryBulk
        [10] = nil,  -- Garbage
    }},

    -- Poll more frequently than other mods because fuel / bulk loads
    -- change their volume and weight live as the truck fills up.
    PollIntervalMs = 2000,
}}

-- Fill in the lookup table with live config values (table literal
-- can't self-reference at definition time).
CONFIG.TypeMultipliers[3]  = CONFIG.DumpMultiplier
CONFIG.TypeMultipliers[6]  = CONFIG.TankerMultiplier
CONFIG.TypeMultipliers[7]  = CONFIG.DryBulkMultiplier
CONFIG.TypeMultipliers[10] = CONFIG.GarbageMultiplier

local function Log(msg) print("[CryovacCargoVolumeBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local typeNames = {{
    [3]="Dump", [6]="Tanker", [7]="DryBulk", [10]="Garbage",
}}

local baselines = {{}}   -- [componentKey] = {{t=typeInt, v=vanilla_DumpVolume}}

-- Per-vehicle physics-mass calibration state.
--   body            : the UPrimitiveComponent we drive mass on.
--                     AMTVehicle has BOTH a UMTVehicleRootComponent
--                     (RootBody, USphereComponent-derived, the actual
--                     physics root that carries cargo weight) and a
--                     UStaticMeshComponent (Mesh, the visual chassis).
--                     We prefer RootBody and fall back to Mesh, then
--                     cache the choice so we don't keep rediscovering.
--   empty_mass      : body mass observed when LoadedItemVolume is
--                     essentially zero AND no scale is active.
--                     Captured once per vehicle.
--   mass_per_volume : kg added to the body per unit of loaded volume.
--                     Calibrated whenever fill > 1.0 AND scale_active
--                     is false (so GetMass returns the game's natural
--                     mass, not our scaled view).
--   slope_logged    : have we logged the slope value yet (one-shot)
--   overload_logged : have we logged that this vehicle was overloaded
--                     (one-shot, so the log shows the moment it
--                     crossed the cap even if the clamp can't engage)
--   scale_active    : whether SetMassScale != 1.0 is currently in
--                     effect on this vehicle.
local vehicleMassStates = {{}}

-- Resolve the vehicle's physics-bearing primitive component. RootBody
-- carries the cargo weight in MT (it's the truck's chassis sphere
-- collider); Mesh is visual only on most blueprints.
local function GetPhysicsBody(owner)
    local rb = SafeGet(owner, "RootBody")
    if rb then return rb, "RootBody" end
    local mesh = SafeGet(owner, "Mesh")
    if mesh then return mesh, "Mesh" end
    return nil, nil
end

-- Clamp the OWNING VEHICLE's chassis physics mass when its cargo space
-- is filled past the vanilla DumpVolume. Drives the body's MassScale
-- (which calls UpdateMassProperties immediately, unlike SetMassOverride
-- which only takes effect at body creation).
local function MaybeClampWeight(comp, vanilla_volume)
    if not CONFIG.CapWeightAtVanilla then return end
    if vanilla_volume <= 0 then return end

    local loaded = SafeGet(comp, "Net_LoadedItemVolume")
    if type(loaded) ~= "number" then return end

    local owner = nil
    pcall(function() owner = comp:GetOwner() end)
    if not owner then return end

    local vehicleKey = ""
    pcall(function() vehicleKey = owner:GetFullName() end)
    if vehicleKey == "" then return end

    local state = vehicleMassStates[vehicleKey]
    if state == nil then
        local body, bodyName = GetPhysicsBody(owner)
        if not body then return end
        state = {{
            body = body,
            body_name = bodyName,
            empty_mass = nil,
            mass_per_volume = nil,
            slope_logged = false,
            overload_logged = false,
            scale_active = false,
        }}
        vehicleMassStates[vehicleKey] = state
    end

    local body = state.body

    -- Calibration: read the body's mass ONLY while no scale is active.
    -- Once scaled, GetMass returns BaseMass*MassScale; using that
    -- would feedback-collapse the slope.
    if not state.scale_active then
        local currentMass = nil
        pcall(function() currentMass = body:GetMass() end)
        if type(currentMass) == "number" and currentMass > 0 then
            -- Stage 1: capture empty mass when truck is essentially empty.
            local empty_threshold = math.max(1.0, vanilla_volume * 0.05)
            if state.empty_mass == nil and loaded < empty_threshold then
                state.empty_mass = currentMass
                Log(string.format("calibrated empty mass for %s [%s]: %.0f kg",
                    vehicleKey, state.body_name, currentMass))
            end
            -- Stage 2: derive kg-per-volume slope.
            if state.empty_mass and loaded > 1.0 then
                local cargo_mass = currentMass - state.empty_mass
                if cargo_mass > 0 then
                    state.mass_per_volume = cargo_mass / loaded
                    if not state.slope_logged then
                        Log(string.format(
                            "calibrated slope for %s [%s]: %.2f kg/u "
                         .. "(empty=%.0f, observed=%.0f at loaded=%.1f)",
                            vehicleKey, state.body_name, state.mass_per_volume,
                            state.empty_mass, currentMass, loaded))
                        state.slope_logged = true
                    end
                end
            end
        end
    end

    -- Diagnostic: log the moment a vehicle crosses vanilla cap, even
    -- if we can't clamp yet. Helps confirm whether the trigger condition
    -- is being reached.
    if loaded > vanilla_volume and not state.overload_logged then
        Log(string.format(
            "%s overloaded: loaded=%.1f vanilla=%.1f (have_slope=%s, scaled=%s)",
            vehicleKey, loaded, vanilla_volume,
            tostring(state.mass_per_volume ~= nil),
            tostring(state.scale_active)))
        state.overload_logged = true
    end

    if state.empty_mass == nil or state.mass_per_volume == nil then
        -- Not enough calibration data yet. Will catch up on a future
        -- uncapped poll once the truck has a non-trivial fill.
        return
    end

    local effective_volume = math.min(loaded, vanilla_volume)
    local target_mass  = state.empty_mass + state.mass_per_volume * effective_volume
    local natural_mass = state.empty_mass + state.mass_per_volume * loaded

    if loaded > vanilla_volume then
        if natural_mass <= 0 then return end
        local scale = target_mass / natural_mass
        local ok = pcall(function() body:SetMassScale("None", scale) end)
        if ok and not state.scale_active then
            Log(string.format(
                "%s mass clamped on [%s]: natural=%.0f kg -> physics=%.0f kg "
             .. "(loaded %.1f / vanilla %.1f, scale %.3f, slope %.2f kg/u)",
                vehicleKey, state.body_name, natural_mass, target_mass,
                loaded, vanilla_volume, scale, state.mass_per_volume))
        end
        if ok then state.scale_active = true end

        local netCargo = SafeGet(owner, "Net_Cargo")
        if netCargo then
            local hudWeight = state.mass_per_volume * effective_volume
            pcall(function() netCargo.CargoWeightKg = hudWeight end)
        end
    elseif state.scale_active then
        pcall(function() body:SetMassScale("None", 1.0) end)
        state.scale_active = false
        state.overload_logged = false  -- arm the next overload log
        Log(string.format("%s mass scale released [%s] (loaded %.1f <= vanilla %.1f)",
            vehicleKey, state.body_name, loaded, vanilla_volume))
    end
end

local function ApplyToAllComponents()
    local comps = FindAllOf("MTVehicleCargoSpaceComponent")
    if not comps then return 0, 0 end
    local count = 0
    pcall(function() count = #comps end)

    local modified = 0
    local seen = 0

    for i = 1, count do
        local comp = comps[i]
        local spaceType = SafeGet(comp, "CargoSpaceType")
        if spaceType == nil then goto nextComp end

        -- UE4SS may wrap enum as a number or as a named wrapper.
        -- Try to coerce to int via :get() if direct compare fails.
        local typeInt = spaceType
        if type(typeInt) ~= "number" then
            pcall(function() typeInt = spaceType:get() end)
        end
        if type(typeInt) ~= "number" then goto nextComp end

        local mult = CONFIG.TypeMultipliers[typeInt]
        if not mult then goto nextComp end

        seen = seen + 1

        local key = ""
        pcall(function() key = comp:GetFullName() end)
        if key == "" then goto nextComp end

        if baselines[key] == nil then
            local currentVolume = SafeGet(comp, "DumpVolume")
            if type(currentVolume) ~= "number" then goto nextComp end
            baselines[key] = {{ t = typeInt, v = currentVolume }}
            Log(string.format("baseline %s (%s): DumpVolume=%.2f",
                key, typeNames[typeInt] or tostring(typeInt),
                currentVolume))
        end

        local baseline = baselines[key].v
        local target   = baseline * mult
        local current  = SafeGet(comp, "DumpVolume")
        if type(current) == "number" and math.abs(current - target) > 0.001 then
            local ok, err = pcall(function() comp.DumpVolume = target end)
            if ok then
                modified = modified + 1
            end
        end

        -- Whether we just boosted or the component was already boosted,
        -- re-clamp the weight each poll so the game's continuous
        -- fill-update loop can't sneak past us.
        MaybeClampWeight(comp, baseline)

        ::nextComp::
    end

    return seen, modified
end

Log("=== Cryovac Cargo Volume Boost Loading ===")
Log(string.format("Tanker=x%.2f  Dump=x%.2f  DryBulk=x%.2f  Garbage=x%.2f  CapWeight=%s",
    CONFIG.TankerMultiplier, CONFIG.DumpMultiplier,
    CONFIG.DryBulkMultiplier, CONFIG.GarbageMultiplier,
    tostring(CONFIG.CapWeightAtVanilla)))

local lastSeen = -1

LoopAsync(CONFIG.PollIntervalMs, function()
    local seen, modified = ApplyToAllComponents()
    if seen ~= lastSeen then
        Log(string.format("Poll: %d matching components, %d freshly scaled this cycle",
            seen, modified))
        lastSeen = seen
    end
    return false  -- keep looping
end)

Log("=== Cryovac Cargo Volume Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for s in SETTINGS:
        val = config.get(s.key, s.default)
        if s.kind == 'bool':
            out[s.key] = bool(val)
            continue
        try:
            val = float(val)
        except (TypeError, ValueError):
            raise ValueError(f"{s.key} must be numeric")
        if not 0.1 <= val <= 10.0:
            raise ValueError(f"{s.key} = {val} out of sanity range [0.1, 10.0]")
        out[s.key] = val
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        tanker_multiplier=f"{cfg['tanker_multiplier']:.3f}",
        dump_multiplier=f"{cfg['dump_multiplier']:.3f}",
        dry_bulk_multiplier=f"{cfg['dry_bulk_multiplier']:.3f}",
        garbage_multiplier=f"{cfg['garbage_multiplier']:.3f}",
        cap_weight_at_vanilla='true' if cfg['cap_weight_at_vanilla'] else 'false',
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    cap = "enabled" if cfg['cap_weight_at_vanilla'] else "disabled"
    body = (
        "Multipliers (applied to DumpVolume by CargoSpaceType):\n"
        f"  Tanker   (EMTCargoSpaceType.Tanker=6):  x{cfg['tanker_multiplier']:.2f}\n"
        f"  Dump     (EMTCargoSpaceType.Dump=3):    x{cfg['dump_multiplier']:.2f}\n"
        f"  Dry Bulk (EMTCargoSpaceType.DryBulk=7): x{cfg['dry_bulk_multiplier']:.2f}\n"
        f"  Garbage  (EMTCargoSpaceType.Garbage=10):x{cfg['garbage_multiplier']:.2f}\n\n"
        f"Ignore increased weight: {cap}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Every 2 seconds the mod scans every live\n"
        "UMTVehicleCargoSpaceComponent. For each component whose\n"
        "CargoSpaceType matches one of the four families above, the\n"
        "DumpVolume field is rewritten to (vanilla_value x multiplier).\n\n"
        "Baselines are captured per component on first sighting, so\n"
        "repeated polls don't compound the effect on the same instance.\n"
        "Newly-spawned vehicles are picked up on the next poll.\n\n"
        "Cargo space types NOT modified by this mod: Flatbed (1),\n"
        "Box (2), ConcreteMixer (4), Container (5), LiveFishTanker (8),\n"
        "Log (9), CarCarrier (11), Grain (12).\n\n"
        "WEIGHT CLAMPING (\"Ignore increased weight\")\n"
        "-------------------------------------------\n"
        "Vanilla cargo weight scales linearly with the loaded volume:\n"
        "if you fill a tanker twice as much, the vehicle weighs twice\n"
        "as much. Combining that with a volume boost can slam the\n"
        "suspension when the truck is overloaded.\n\n"
        "When \"Ignore increased weight\" is checked, the mod calls\n"
        "SetMassScale on AMTVehicle.RootBody (a UMTVehicleRootComponent\n"
        "/ USphereComponent - the truck's actual physics root that\n"
        "carries cargo weight). Falls back to AMTVehicle.Mesh if\n"
        "RootBody is null. SetMassScale is the BodyInstance entry\n"
        "point that runs UpdateMassProperties immediately;\n"
        "SetMassOverrideInKg writes the override field but doesn't\n"
        "recompute the body's effective mass at runtime, so it has no\n"
        "effect on already-spawned vehicles.\n\n"
        "Per-vehicle calibration:\n\n"
        "  1. On first sight while the truck is empty (LoadedVolume\n"
        "     near zero) and not yet scaled, the mod records the\n"
        "     chassis 'empty mass'.\n"
        "  2. Whenever the truck has any fill AND no scale is active,\n"
        "     the mod measures the kg-per-unit-volume slope.\n"
        "  3. When fill exceeds vanilla DumpVolume, the chassis is\n"
        "     scaled by (target_mass / natural_mass) where\n"
        "       natural_mass = empty + slope * loaded\n"
        "       target_mass  = empty + slope * vanilla\n"
        "     i.e. what the truck would weigh at exactly vanilla fill.\n"
        "  4. As soon as the truck drops back to or below vanilla\n"
        "     volume, MassScale is reset to 1.0 and natural physics\n"
        "     resume.\n\n"
        "Because the scale targets the actual physics mass (not the\n"
        "HUD field), the suspension behaves identically to vanilla\n"
        "regardless of how much extra cargo the boost lets you carry.\n"
        "The HUD CargoWeightKg readout is also clamped so the displayed\n"
        "weight matches the physics weight.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
