"""Cryovac Cargo Volume Boost — scales DumpVolume on every live
UMTVehicleCargoSpaceComponent whose CargoSpaceType matches one of the
targeted families (Tanker, Dump, DryBulk, Garbage). Polls every
5 seconds so freshly-spawned vehicles get the boost too.

This is the runtime Lua equivalent of the old "More Cargo" pak mod
(which was a static asset override of specific vehicle Blueprints).
Using Lua instead means: one mod covers every vehicle of each type,
not just the single Blueprint the pak replaced, and you can retune
the multiplier without recompiling assets.
"""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCargoVolumeBoost'

UI_TITLE = 'Cargo Volume Boost'

UI_DESCRIPTION = (
    "<p style='color:#ff5252;'><b>WARNING:</b> This mod boosts cargo "
    "VOLUME but cannot cap cargo WEIGHT. A truck loaded past its "
    "vanilla capacity will weigh proportionally more, which slams the "
    "suspension, lengthens stopping distance, and bogs the engine on "
    "hills. Keep multipliers at or below ~1.5\u20132\u00d7 for sane "
    "driving feel.</p>"
    "Scales how much cargo the bulk/fluid vehicle classes can carry. "
    "One slider per truck family, because a 2\u00d7 dump might not be "
    "what you want on a fuel tanker.\n\n"
    "Each slider multiplies the <code>DumpVolume</code> field on every "
    "live <code>UMTVehicleCargoSpaceComponent</code> whose "
    "<code>CargoSpaceType</code> matches that family:\n"
    "<br>\u2022 <b>Tanker</b> \u2014 liquid fuel / oil / water tank trucks\n"
    "<br>\u2022 <b>Dump</b> \u2014 dump trucks (loose fill, not containerised)\n"
    "<br>\u2022 <b>Dry Bulk</b> \u2014 cement, sand, ore silo trucks\n"
    "<br>\u2022 <b>Garbage</b> \u2014 garbage compactor trucks\n\n"
    "Polls every 2 seconds so vehicles that spawn mid-session also "
    "get the boost. Baselines are captured per-instance on first "
    "apply so re-polling doesn't compound the multiplier.\n\n"
    "Other volume-based types (ConcreteMixer, LiveFishTanker, Grain, "
    "Log) are not touched by this mod \u2014 ask if you want them added."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'tanker_multiplier':   1.0,
    'dump_multiplier':     1.0,
    'dry_bulk_multiplier': 1.0,
    'garbage_multiplier':  1.0,
}


def _slider(key: str, label: str, tooltip: str) -> Setting:
    return Setting(
        key=key,
        label=label,
        kind='slider',
        default=1.0,
        min_value=1.0,
        max_value=2.5,
        step=0.1,
        suffix='\u00d7',
        tooltip=tooltip,
    )


SETTINGS = [
    _slider('tanker_multiplier',   'Tanker',
            'Multiplier on DumpVolume for Tanker-class cargo spaces. '
            'Cargo weight scales with volume \u2014 keep \u2264 ~2\u00d7 for sane handling.'),
    _slider('dump_multiplier',     'Dump',
            'Multiplier on DumpVolume for Dump-truck cargo spaces. '
            'Cargo weight scales with volume \u2014 keep \u2264 ~2\u00d7 for sane handling.'),
    _slider('dry_bulk_multiplier', 'Dry Bulk',
            'Multiplier on DumpVolume for DryBulk cargo spaces. '
            'Cargo weight scales with volume \u2014 keep \u2264 ~2\u00d7 for sane handling.'),
    _slider('garbage_multiplier',  'Garbage',
            'Multiplier on DumpVolume for Garbage compactor cargo spaces. '
            'Cargo weight scales with volume \u2014 keep \u2264 ~2\u00d7 for sane handling.'),
]


# Values of the EMTCargoSpaceType enum we care about, matched against
# UMTVehicleCargoSpaceComponent.CargoSpaceType at runtime. Enum is
# uint8 so comparisons are cheap. Source of truth:
#   UHTHeaderDump/MotorTown/Public/EMTCargoSpaceType.h
# Invalid=0 Flatbed=1 Box=2 Dump=3 ConcreteMixer=4 Container=5
# Tanker=6 DryBulk=7 LiveFishTanker=8 Log=9 Garbage=10 CarCarrier=11
# Grain=12 Max=13
_ENUM_DUMP    = 3
_ENUM_TANKER  = 6
_ENUM_DRYBULK = 7
_ENUM_GARBAGE = 10


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Cargo Volume Boost
    ===========================
    Scales DumpVolume on every live UMTVehicleCargoSpaceComponent
    whose CargoSpaceType is Tanker (6), Dump (3), DryBulk (7), or
    Garbage (10). One multiplier per family.

    Baselines (per-component vanilla DumpVolume) are captured on
    first apply, so polling every 2s doesn't compound the effect.
    Freshly-spawned vehicles are baselined + scaled on the next poll.

    NOTE: cargo physics weight scales with the loaded volume in
    Motor Town's native code, and that weight is not reachable from
    Lua reflection (no UPROPERTY/UFUNCTION exposes it). A truck
    loaded past vanilla therefore weighs more in physics, with the
    expected handling impact. Use multipliers <= 2x for sane feel.

    Generated by Frog Mod Editor. Config is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    TankerMultiplier   = {tanker_multiplier},
    DumpMultiplier     = {dump_multiplier},
    DryBulkMultiplier  = {dry_bulk_multiplier},
    GarbageMultiplier  = {garbage_multiplier},

    -- EMTCargoSpaceType enum values we target. Anything not in this
    -- map is ignored (Box, Flatbed, Container, Log, CarCarrier, etc.)
    TypeMultipliers = {{
        [3]  = nil,  -- Dump     (set below so Lua sees the CONFIG values)
        [6]  = nil,  -- Tanker
        [7]  = nil,  -- DryBulk
        [10] = nil,  -- Garbage
    }},

    PollIntervalMs = 2000,
}}

-- Fill in the lookup table with live config values (table literal
-- can't self-reference at definition time).
CONFIG.TypeMultipliers[3]  = CONFIG.DumpMultiplier
CONFIG.TypeMultipliers[6]  = CONFIG.TankerMultiplier
CONFIG.TypeMultipliers[7]  = CONFIG.DryBulkMultiplier
CONFIG.TypeMultipliers[10] = CONFIG.GarbageMultiplier

local function Log(msg) print("[CryovacCargoVolumeBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local typeNames = {{
    [3]="Dump", [6]="Tanker", [7]="DryBulk", [10]="Garbage",
}}

local baselines = {{}}   -- [componentKey] = {{t=typeInt, v=vanilla_DumpVolume}}

local function ApplyToAllComponents()
    local comps = FindAllOf("MTVehicleCargoSpaceComponent")
    if not comps then return 0, 0 end
    local count = 0
    pcall(function() count = #comps end)

    local modified = 0
    local seen = 0

    for i = 1, count do
        local comp = comps[i]
        local spaceType = SafeGet(comp, "CargoSpaceType")
        if spaceType == nil then goto nextComp end

        -- UE4SS may wrap enum as a number or as a named wrapper.
        -- Try to coerce to int via :get() if direct compare fails.
        local typeInt = spaceType
        if type(typeInt) ~= "number" then
            pcall(function() typeInt = spaceType:get() end)
        end
        if type(typeInt) ~= "number" then goto nextComp end

        local mult = CONFIG.TypeMultipliers[typeInt]
        if not mult then goto nextComp end

        seen = seen + 1

        local key = ""
        pcall(function() key = comp:GetFullName() end)
        if key == "" then goto nextComp end

        if baselines[key] == nil then
            local currentVolume = SafeGet(comp, "DumpVolume")
            if type(currentVolume) ~= "number" then goto nextComp end
            baselines[key] = {{ t = typeInt, v = currentVolume }}
            Log(string.format("baseline %s (%s): DumpVolume=%.2f",
                key, typeNames[typeInt] or tostring(typeInt),
                currentVolume))
        end

        local baseline = baselines[key].v
        local target   = baseline * mult
        local current  = SafeGet(comp, "DumpVolume")
        if type(current) == "number" and math.abs(current - target) > 0.001 then
            local ok, err = pcall(function() comp.DumpVolume = target end)
            if ok then
                modified = modified + 1
            end
        end

        ::nextComp::
    end

    return seen, modified
end

Log("=== Cryovac Cargo Volume Boost Loading ===")
Log(string.format("Tanker=x%.2f  Dump=x%.2f  DryBulk=x%.2f  Garbage=x%.2f",
    CONFIG.TankerMultiplier, CONFIG.DumpMultiplier,
    CONFIG.DryBulkMultiplier, CONFIG.GarbageMultiplier))

local lastSeen = -1

LoopAsync(CONFIG.PollIntervalMs, function()
    local seen, modified = ApplyToAllComponents()
    if seen ~= lastSeen then
        Log(string.format("Poll: %d matching components, %d freshly scaled this cycle",
            seen, modified))
        lastSeen = seen
    end
    return false  -- keep looping
end)

Log("=== Cryovac Cargo Volume Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for s in SETTINGS:
        val = config.get(s.key, s.default)
        try:
            val = float(val)
        except (TypeError, ValueError):
            raise ValueError(f"{s.key} must be numeric")
        if not 1.0 <= val <= 2.5:
            raise ValueError(f"{s.key} = {val} out of range [1.0, 2.5]")
        out[s.key] = val
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        tanker_multiplier=f"{cfg['tanker_multiplier']:.3f}",
        dump_multiplier=f"{cfg['dump_multiplier']:.3f}",
        dry_bulk_multiplier=f"{cfg['dry_bulk_multiplier']:.3f}",
        garbage_multiplier=f"{cfg['garbage_multiplier']:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    body = (
        "Multipliers (applied to DumpVolume by CargoSpaceType):\n"
        f"  Tanker   (EMTCargoSpaceType.Tanker=6):  x{cfg['tanker_multiplier']:.2f}\n"
        f"  Dump     (EMTCargoSpaceType.Dump=3):    x{cfg['dump_multiplier']:.2f}\n"
        f"  Dry Bulk (EMTCargoSpaceType.DryBulk=7): x{cfg['dry_bulk_multiplier']:.2f}\n"
        f"  Garbage  (EMTCargoSpaceType.Garbage=10):x{cfg['garbage_multiplier']:.2f}\n\n"
        "*** IMPORTANT - WEIGHT IS NOT CAPPED ***\n"
        "----------------------------------------\n"
        "This mod boosts cargo VOLUME but cannot cap cargo WEIGHT.\n"
        "Motor Town computes effective vehicle weight in native code\n"
        "from the loaded volume, and that weight is not exposed via\n"
        "any field reachable from UE4SS Lua reflection.\n\n"
        "A truck loaded past its vanilla volume therefore weighs\n"
        "proportionally more in physics: stiffer engine load on\n"
        "hills, longer braking distance, suspension compression that\n"
        "can bottom out at high overload, more tire wear.\n\n"
        "Recommendation: keep multipliers at or below 2.0x for sane\n"
        "driveability. The slider is hard-capped at 2.5x for this\n"
        "reason.\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Every 2 seconds the mod scans every live\n"
        "UMTVehicleCargoSpaceComponent. For each component whose\n"
        "CargoSpaceType matches one of the four families above, the\n"
        "DumpVolume field is rewritten to (vanilla_value x multiplier).\n\n"
        "Baselines are captured per component on first sighting, so\n"
        "repeated polls don't compound the effect on the same instance.\n"
        "Newly-spawned vehicles are picked up on the next poll.\n\n"
        "Cargo space types NOT modified by this mod: Flatbed (1),\n"
        "Box (2), ConcreteMixer (4), Container (5), LiveFishTanker (8),\n"
        "Log (9), CarCarrier (11), Grain (12).\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
