"""Cryovac Company Profit Boost — boosts the owner-profit-share
payout ONLY on deliveries made in vehicles you own (vehicles whose
Net_OwnerCompanyGuid matches one of your own companies). Non-company
vehicles are untouched, so you don't get penalised when driving
rentals or AI-company rigs.

Mechanism: pre-hook on
  /Script/MotorTown.MotorTownPlayerController:ServerGiveOwnerProfitShare
that mutates the Money parameter in place before vanilla executes.
When the target vehicle belongs to one of the local player's owned
companies, Money is rewritten to `floor(money * multiplier)` and the
vanilla payment logic runs unchanged on the boosted value. Result:
the on-screen "+$X Owner's Profit Share" popup AND the company
transaction ledger both show the single boosted number — no ghost
second-line credit, no ambiguity. At 1.0x the mod is a no-op and
the hook is never installed."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCompanyProfitBoost'

UI_TITLE = 'Company Profit Boost'

UI_DESCRIPTION = (
    "Multiplies the owner-profit-share payout from deliveries made in "
    "your own company\u2019s vehicles. Vehicles you don\u2019t own "
    "(AI-company, rental, another player\u2019s company) are untouched.\n\n"
    "When a delivery wraps up, the game fires "
    "<code>ServerGiveOwnerProfitShare(vehicle, money, type)</code>. "
    "This mod installs a pre-hook on that RPC: if the vehicle\u2019s "
    "<code>Net_OwnerCompanyGuid</code> matches a company you own, it "
    "rewrites the <code>money</code> parameter to "
    "<code>floor(money \u00d7 multiplier)</code> BEFORE vanilla runs. "
    "Vanilla then pays out the boosted amount as a single transaction "
    "\u2014 the on-screen popup and the company ledger both show the "
    "full boosted number.\n\n"
    "<b>1.0\u00d7</b> \u2014 no change. Mod is a no-op (hook not installed).<br>"
    "<b>2.0\u00d7</b> \u2014 deliveries in your own vehicles pay double.<br>"
    "<b>5.0\u00d7</b> \u2014 deliveries in your own vehicles pay 5\u00d7 vanilla.\n\n"
    "Runs on the SERVER (host / dedicated)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'multiplier': 1.0,
}

SETTINGS = [
    Setting(
        key='multiplier',
        label='Company profit multiplier',
        kind='slider',
        default=1.0,
        min_value=1.0,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip='Scale the owner-profit-share payout on your own company\'s '
                'vehicles only. 1.0 = no change, 2.0 = +100% bonus, '
                '5.0 = +400% bonus. Non-company vehicles stay vanilla.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Company Profit Boost
    =============================
    Boosts the owner-profit-share payout ONLY on vehicles your
    company owns. Non-company vehicles stay vanilla.

    Mechanism: pre-hook on
        MotorTownPlayerController:ServerGiveOwnerProfitShare(
            Vehicle, Money, TxType)
    When Vehicle.Net_OwnerCompanyGuid matches a company the local
    player owns, we rewrite the Money parameter IN PLACE to
    floor(Money * Multiplier) before vanilla executes. Vanilla then
    pays out the boosted amount as a single transaction, so both the
    on-screen popup and the company ledger reflect the real total.

    Generated by Frog Mod Editor. Multiplier is hardcoded below;
    regenerate from Frog to change it.

    Runs on SERVER (host / dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Multiplier = {multiplier},

    -- How frequently we rediscover the player's owned-company list
    -- (handles newly-founded or left companies mid-session).
    OwnerRescanEverySec = 30,
}}

local function Log(msg) print("[CryovacCompanyProfitBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function Unwrap(obj)
    if obj == nil then return nil end
    -- UE4SS wraps primitives and structs as accessors. Try :get() first,
    -- fall back to the raw value if it's already unwrapped.
    local ok, val = pcall(function() return obj:get() end)
    if ok and val ~= nil then return val end
    return obj
end

local function GuidsEqual(g1, g2)
    if not g1 or not g2 then return false end
    return (SafeGet(g1, "A") == SafeGet(g2, "A"))
       and (SafeGet(g1, "B") == SafeGet(g2, "B"))
       and (SafeGet(g1, "C") == SafeGet(g2, "C"))
       and (SafeGet(g1, "D") == SafeGet(g2, "D"))
end

local function GuidAsString(g)
    if not g then return "<nil>" end
    return string.format("%08x-%08x-%08x-%08x",
        SafeGet(g, "A") or 0, SafeGet(g, "B") or 0,
        SafeGet(g, "C") or 0, SafeGet(g, "D") or 0)
end

-- Cached list of (MTCompanySystem, CompanyGuid) for the local player's
-- owned companies. Refreshed on a slow cadence so newly-founded
-- companies start getting the boost without requiring a relaunch.
local ownedCompanies = {{}}

local function FindLocalPlayerCharacterGuid()
    -- Find the local PlayerController + the character GUID the player
    -- currently controls. In the company-system list, a company lists
    -- its owner by character GUID, so this is what we compare against.
    local pcs = FindAllOf("MotorTownPlayerController")
    if not pcs then return nil end
    local count = 0
    pcall(function() count = #pcs end)
    for i = 1, count do
        local pc = pcs[i]
        local isLocal = false
        pcall(function() isLocal = pc:IsLocalController() end)
        if isLocal then
            -- Try a few paths to get the character GUID.
            local ps = SafeGet(pc, "PlayerState")
            if ps then
                local cid = SafeGet(ps, "Net_OwnerCharacterId")
                if cid then
                    local g = SafeGet(cid, "CharacterGuid")
                    if g then return g end
                end
                local g2 = SafeGet(ps, "Net_OwnerCharacterGuid")
                if g2 then return g2 end
            end
        end
    end
    return nil
end

local function RefreshOwnedCompanies()
    ownedCompanies = {{}}
    local myCharacterGuid = FindLocalPlayerCharacterGuid()
    if not myCharacterGuid then
        return
    end

    local systems = FindAllOf("MTCompanySystem")
    if not systems then return end
    local sysCount = 0
    pcall(function() sysCount = #systems end)

    for s = 1, sysCount do
        local cs = systems[s]
        local companies = SafeGet(cs, "Server_Companies")
        if companies then
            local count = 0
            pcall(function() count = #companies end)
            for i = 1, count do
                local co = companies[i]
                -- Company's founding owner. Field name varies across
                -- builds; try a few reasonable ones.
                local ownerGuid = SafeGet(co, "OwnerCharacterGuid")
                              or SafeGet(co, "Net_OwnerCharacterGuid")
                              or SafeGet(co, "FounderCharacterGuid")
                if GuidsEqual(ownerGuid, myCharacterGuid) then
                    local guid = SafeGet(co, "Guid")
                    if guid then
                        ownedCompanies[#ownedCompanies + 1] = {{
                            system = cs,
                            guid = guid,
                            name = SafeGet(co, "Net_CompanyName") or "<?>",
                        }}
                    end
                end
            end
        end
    end

    if #ownedCompanies > 0 then
        local names = {{}}
        for _, c in ipairs(ownedCompanies) do
            names[#names + 1] = tostring(c.name)
        end
        Log("Owned companies: " .. table.concat(names, ", "))
    end
end

local function IsOwnedByMyCompany(vehicle)
    if not vehicle or #ownedCompanies == 0 then return false end
    local vg = SafeGet(vehicle, "Net_OwnerCompanyGuid")
    if not vg then return false end
    for _, c in ipairs(ownedCompanies) do
        if GuidsEqual(vg, c.guid) then
            return true, c
        end
    end
    return false, nil
end

-- ============================================================
-- Hook: ServerGiveOwnerProfitShare(Vehicle, Money, TxType)
-- Pre-hook that rewrites Money BEFORE vanilla runs, so the boosted
-- amount is what gets paid out (and what the in-game popup / ledger
-- display). Untouched for vehicles not owned by the local player.
-- ============================================================
local function SetupHook()
    if math.abs(CONFIG.Multiplier - 1.0) < 1e-6 then
        Log("Multiplier = 1.0 -- no hook installed (mod is a no-op).")
        return
    end
    local ok, err = pcall(function()
        RegisterHook(
            "/Script/MotorTown.MotorTownPlayerController:ServerGiveOwnerProfitShare",
            function(self, vehicleWrap, moneyWrap, txTypeWrap)
                local vehicle = Unwrap(vehicleWrap)
                if not vehicle then return end

                local matched, company = IsOwnedByMyCompany(vehicle)
                if not matched then return end

                local money = Unwrap(moneyWrap) or 0
                if type(money) ~= "number" or money <= 0 then return end

                local boosted = math.floor(money * CONFIG.Multiplier)
                if boosted <= money then return end  -- no-op guard

                -- Rewrite the parameter wrapper. UE4SS exposes :set()
                -- on param accessors; when vanilla executes, it sees
                -- the new value and pays out the boosted amount as a
                -- single transaction.
                local setOk, setErr = pcall(function()
                    moneyWrap:set(boosted)
                end)
                if setOk then
                    Log(string.format(
                        "boost applied: %d -> %d (x%.2f) company=%s",
                        money, boosted, CONFIG.Multiplier, tostring(company.name)))
                else
                    Log("param :set() failed: " .. tostring(setErr)
                        .. " (vanilla payout unchanged)")
                end
            end)
    end)
    if ok then
        Log("Hook registered: MotorTownPlayerController:ServerGiveOwnerProfitShare")
    else
        Log("Hook failed: " .. tostring(err))
    end
end

-- ============================================================
-- Init
-- ============================================================
Log("=== Cryovac Company Profit Boost Loading ===")
Log(string.format("Multiplier: x%.2f", CONFIG.Multiplier))

-- Seed the owned-companies list once things are loaded.
ExecuteWithDelay(15000, function()
    RefreshOwnedCompanies()
    SetupHook()
end)

-- Rescan periodically so a freshly-founded company starts benefiting
-- without forcing a relaunch.
LoopAsync(CONFIG.OwnerRescanEverySec * 1000, function()
    RefreshOwnedCompanies()
    return false  -- keep looping
end)

Log("=== Cryovac Company Profit Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    try:
        val = float(config.get('multiplier', DEFAULT_CONFIG['multiplier']))
    except (TypeError, ValueError):
        raise ValueError("multiplier must be numeric")
    if not 1.0 <= val <= 10.0:
        raise ValueError(f"multiplier {val} out of sanity range [1.0, 10.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(multiplier=f"{val:.3f}")


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    if abs(val - 1.0) < 1e-6:
        effect = "no change (mod is a no-op, hook not installed)"
    else:
        pct = val * 100.0
        effect = f"deliveries in your own vehicles pay {pct:.0f}% of vanilla"
    body = (
        f"Multiplier: x{val:.2f}  ({effect})\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Pre-hooks MotorTownPlayerController:ServerGiveOwnerProfitShare.\n"
        "When it fires for a vehicle whose Net_OwnerCompanyGuid matches\n"
        "a company the local player owns, the mod rewrites the Money\n"
        "parameter to floor(Money * multiplier) BEFORE vanilla runs.\n"
        "Vanilla then pays out the boosted amount as a single\n"
        "transaction - the on-screen '+$X Owner's Profit Share' popup\n"
        "and the company transaction ledger both reflect the real total.\n\n"
        "Owner lookup walks MTCompanySystem.Server_Companies every 30s\n"
        "and picks out the ones whose OwnerCharacterGuid matches the\n"
        "local player's character GUID. Companies founded mid-session\n"
        "start getting the boost within the next 30s.\n\n"
        "Non-company vehicles (AI-company, rental, other players'\n"
        "companies) are ignored entirely - the hook short-circuits\n"
        "before touching the Money parameter.\n\n"
        "If the UE4SS param :set() call fails for any reason (rare), a\n"
        "warning is logged and the vanilla payment goes through\n"
        "unchanged - no stuck state, no double-credit.\n\n"
        "Runs server-side. On a dedicated server, install on the host.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'multiplier': val, 'bonus_percent': (val - 1.0) * 100.0},
    )


import sys as _sys
register(_sys.modules[__name__])
