"""Cryovac Company Vehicle Care — reshapes CompanyAI running-cost and
condition-usage multipliers on every FVehicleRow across all Vehicles*
DataTables. Three independent mode factors so the player can tune
running cost, on-road wear, and offroad wear separately."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting, MODE_FACTOR_OPTIONS
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCompanyVehicleCare'

UI_TITLE = 'Company Vehicle Care'

UI_DESCRIPTION = (
    "Scales how expensive and how quickly-worn your company-owned, "
    "AI-driven vehicles are. Three independent sliders so you can keep "
    "realistic wear on-road while softening offroad abuse, or slash "
    "running costs without touching wear.\n\n"
    "<b>Running Cost</b> — <code>CompanyAIRunningCostMultiplier</code>. "
    "Hourly cost your company pays while an AI drives the vehicle.<br>"
    "<b>On-road Wear</b> — <code>CompanyAIConditionUsageMultiplier</code>. "
    "Base wear rate from normal driving.<br>"
    "<b>Offroad Wear</b> — <code>CompanyAIConditionUsageMultiplierOffroad</code>. "
    "Extra wear on unpaved / rough terrain.\n\n"
    "Each mode multiplies the vanilla value: Low halves it, High 1.5\u00d7s "
    "it, Off zeroes it entirely. Modifies the Vehicles DataTables at "
    "runtime (requires UE4SS)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'running_cost_mode':   'Vanilla',
    'condition_mode':      'Low',
    'condition_offroad_mode': 'Low',
}

SETTINGS = [
    Setting(
        key='running_cost_mode',
        label='Running Cost',
        kind='mode',
        default='Vanilla',
        options=MODE_FACTOR_OPTIONS,
        tooltip='Factor applied to every vehicle\'s CompanyAIRunningCostMultiplier.',
    ),
    Setting(
        key='condition_mode',
        label='On-road Wear',
        kind='mode',
        default='Low',
        options=MODE_FACTOR_OPTIONS,
        tooltip='Factor applied to every vehicle\'s CompanyAIConditionUsageMultiplier.',
    ),
    Setting(
        key='condition_offroad_mode',
        label='Offroad Wear',
        kind='mode',
        default='Low',
        options=MODE_FACTOR_OPTIONS,
        tooltip='Factor applied to every vehicle\'s CompanyAIConditionUsageMultiplierOffroad.',
    ),
]


# ---------------------------------------------------------------------------
# Lua template
# ---------------------------------------------------------------------------
_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Company Vehicle Care
    =============================
    Scales three FVehicleRow fields on every vehicle in the Vehicles
    DataTables at session start:

      CompanyAIRunningCostMultiplier              - running cost
      CompanyAIConditionUsageMultiplier           - on-road wear
      CompanyAIConditionUsageMultiplierOffroad    - offroad wear

    Each has its own independent mode factor (Vanilla/Low/High/Off).
    Baselines are captured per row on first apply, so re-applying does
    not compound. Vanilla mode for a given axis is a no-op.

    Generated by Frog Mod Editor. Modes are hardcoded below - regenerate
    the mod from Frog to change them.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    RunningCostMode        = "{running_cost_mode}",
    ConditionMode          = "{condition_mode}",
    ConditionOffroadMode   = "{condition_offroad_mode}",

    ModeFactor = {{
        Vanilla = 1.0,
        Low     = 0.5,
        High    = 1.5,
        Off     = 0.0,
    }},

    -- Match every /Game/DataAsset/Vehicles/*.uasset (DataTable OR
    -- CompositeDataTable), skip the Deprecated one.
    TargetDTSubstring  = "/Vehicles",
    ExcludeDTSubstring = "Deprecated",

    InitialDelayMs = 15000,
}}

local function Log(msg) print("[CryovacCompanyVehicleCare] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function FindVehicleDTs()
    local dts = FindAllOf("DataTable")
    if not dts then return {{}} end
    local count = 0
    pcall(function() count = #dts end)
    local matched = {{}}
    for i = 1, count do
        local dt = dts[i]
        local fullName = ""
        pcall(function() fullName = dt:GetFullName() end)
        if string.find(fullName, CONFIG.TargetDTSubstring, 1, true)
           and not string.find(fullName, CONFIG.ExcludeDTSubstring, 1, true) then
            matched[#matched + 1] = {{ dt = dt, name = fullName }}
        end
    end
    return matched
end

local applied = false
local vanilla_baseline = {{}}   -- [table][row] = {{running, cond, cond_off}}

local function ApplyScaling()
    if applied then return true end

    local rcFactor = CONFIG.ModeFactor[CONFIG.RunningCostMode]
    local cFactor  = CONFIG.ModeFactor[CONFIG.ConditionMode]
    local coFactor = CONFIG.ModeFactor[CONFIG.ConditionOffroadMode]
    if rcFactor == nil or cFactor == nil or coFactor == nil then
        Log("Unknown mode in config; aborting.")
        applied = true
        return true
    end

    -- If every axis is Vanilla, nothing to do.
    if CONFIG.RunningCostMode == "Vanilla"
       and CONFIG.ConditionMode == "Vanilla"
       and CONFIG.ConditionOffroadMode == "Vanilla" then
        Log("All modes Vanilla - no modifications applied.")
        applied = true
        return true
    end

    local matched = FindVehicleDTs()
    if #matched == 0 then return false end

    local total_mods = 0
    local sampleLogged = 0

    for _, m in ipairs(matched) do
        local dt, fullName = m.dt, m.name
        local rowNames = nil
        pcall(function() rowNames = dt:GetRowNames() end)
        if not rowNames then return false end
        local n = 0
        pcall(function() n = #rowNames end)
        if n == 0 then return false end

        Log(string.format("Matched %s (%d rows). RunningCost=%s On-road=%s Offroad=%s",
            fullName, n,
            CONFIG.RunningCostMode, CONFIG.ConditionMode,
            CONFIG.ConditionOffroadMode))

        vanilla_baseline[fullName] = vanilla_baseline[fullName] or {{}}
        local baselineTbl = vanilla_baseline[fullName]
        local thisTableMods = 0

        for i = 1, n do
            local rowName = rowNames[i]
            local struct = nil
            pcall(function() struct = dt:FindRow(rowName, "VehicleCare", false) end)
            if struct then
                local key = tostring(rowName)
                if baselineTbl[key] == nil then
                    baselineTbl[key] = {{
                        running  = SafeGet(struct, "CompanyAIRunningCostMultiplier"),
                        cond     = SafeGet(struct, "CompanyAIConditionUsageMultiplier"),
                        cond_off = SafeGet(struct, "CompanyAIConditionUsageMultiplierOffroad"),
                    }}
                end
                local b = baselineTbl[key]
                local did = false
                if type(b.running) == "number" then
                    pcall(function()
                        struct.CompanyAIRunningCostMultiplier = b.running * rcFactor
                    end)
                    did = true
                end
                if type(b.cond) == "number" then
                    pcall(function()
                        struct.CompanyAIConditionUsageMultiplier = b.cond * cFactor
                    end)
                    did = true
                end
                if type(b.cond_off) == "number" then
                    pcall(function()
                        struct.CompanyAIConditionUsageMultiplierOffroad = b.cond_off * coFactor
                    end)
                    did = true
                end
                if did and sampleLogged < 6 then
                    local vR = SafeGet(struct, "CompanyAIRunningCostMultiplier") or 0
                    local vC = SafeGet(struct, "CompanyAIConditionUsageMultiplier") or 0
                    local vO = SafeGet(struct, "CompanyAIConditionUsageMultiplierOffroad") or 0
                    Log(string.format(
                        "  [%s] %s: running %.3f->%.3f  wear %.3f->%.3f  offroad %.3f->%.3f",
                        fullName:match("([^%.]+)$") or fullName, key,
                        b.running or 0, vR,
                        b.cond    or 0, vC,
                        b.cond_off or 0, vO))
                    sampleLogged = sampleLogged + 1
                end
                if did then thisTableMods = thisTableMods + 1 end
            end
        end

        Log(string.format("  -> Touched %d rows in %s.", thisTableMods, fullName))
        total_mods = total_mods + thisTableMods
    end

    Log(string.format("Applied Company Vehicle Care to %d rows across %d table(s).",
        total_mods, #matched))
    applied = true
    return true
end

Log("=== Cryovac Company Vehicle Care Loading ===")
Log(string.format("Modes: RunningCost=%s  On-road=%s  Offroad=%s",
    CONFIG.RunningCostMode, CONFIG.ConditionMode, CONFIG.ConditionOffroadMode))

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyScaling() then
        LoopAsync(5000, function() return ApplyScaling() end)
    end
end)

Log("=== Cryovac Company Vehicle Care Loaded ===")
'''


_VALID_MODES = {opt.key for opt in MODE_FACTOR_OPTIONS}


def _validate(config: Dict[str, Any]) -> Dict[str, str]:
    out = {}
    for key in ('running_cost_mode', 'condition_mode', 'condition_offroad_mode'):
        val = config.get(key, DEFAULT_CONFIG[key])
        if val not in _VALID_MODES:
            raise ValueError(f"Unknown {key}: {val!r}. Expected one of {_VALID_MODES}")
        out[key] = val
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(**cfg)


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    factors = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}
    body = (
        f"Selected modes:\n"
        f"  Running Cost:   {cfg['running_cost_mode']} (x{factors[cfg['running_cost_mode']]})\n"
        f"  On-road Wear:   {cfg['condition_mode']} (x{factors[cfg['condition_mode']]})\n"
        f"  Offroad Wear:   {cfg['condition_offroad_mode']} (x{factors[cfg['condition_offroad_mode']]})\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Reshapes three CompanyAI fields on every vehicle row in the\n"
        "Motor Town Vehicles DataTables. Baselines are captured per row\n"
        "on first apply so re-applying doesn't compound.\n\n"
        "  CompanyAIRunningCostMultiplier             (Running Cost)\n"
        "  CompanyAIConditionUsageMultiplier          (On-road Wear)\n"
        "  CompanyAIConditionUsageMultiplierOffroad   (Offroad Wear)\n\n"
        "Each of the three sliders is independent. Setting any axis to\n"
        "Vanilla leaves that field untouched on every row.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    factors = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={
            'running_cost': {'mode': cfg['running_cost_mode'],
                             'factor': factors[cfg['running_cost_mode']]},
            'condition':    {'mode': cfg['condition_mode'],
                             'factor': factors[cfg['condition_mode']]},
            'condition_offroad': {'mode': cfg['condition_offroad_mode'],
                                  'factor': factors[cfg['condition_offroad_mode']]},
        },
    )


import sys as _sys
register(_sys.modules[__name__])
