"""Cryovac Company Vehicle Care — reshapes CompanyAI running-cost and
condition-usage multipliers on every FVehicleRow across all Vehicles*
DataTables. Three independent mode factors so the player can tune
running cost, on-road wear, and offroad wear separately."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting, MODE_FACTOR_OPTIONS
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCompanyVehicleCare'

UI_TITLE = 'Company Vehicle Care'

UI_DESCRIPTION = (
    "Scales how expensive and how quickly-worn your company-owned, "
    "AI-driven vehicles are. Running Cost uses a Vanilla/Low/High/Off "
    "mode selector; the two wear axes are free-range sliders so you "
    "can tune them precisely.\n\n"
    "<b>Running Cost</b> \u2014 <code>CompanyAIRunningCostMultiplier</code>. "
    "Hourly cost your company pays while an AI drives the vehicle.<br>"
    "<b>On-road Wear</b> \u2014 <code>CompanyAIConditionUsageMultiplier</code>. "
    "Base wear rate from normal driving.<br>"
    "<b>Offroad Wear</b> \u2014 <code>CompanyAIConditionUsageMultiplierOffroad</code>. "
    "Extra wear on unpaved / rough terrain.\n\n"
    "<b>Wear slider semantics</b> \u2014 1.0\u00d7 is vanilla. Values below 1.0\u00d7 "
    "slow the wear interval (vehicles last longer); values above 1.0\u00d7 "
    "speed it up (vehicles degrade faster). 0.0\u00d7 disables wear on that "
    "axis entirely.\n\n"
    "Modifies the Vehicles DataTables at runtime (requires UE4SS)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'running_cost_mode':           'Vanilla',
    'condition_multiplier':        1.0,
    'condition_offroad_multiplier': 1.0,
}

SETTINGS = [
    Setting(
        key='running_cost_mode',
        label='Running Cost',
        kind='mode',
        default='Vanilla',
        options=MODE_FACTOR_OPTIONS,
        tooltip='Factor applied to every vehicle\'s CompanyAIRunningCostMultiplier.',
    ),
    Setting(
        key='condition_multiplier',
        label='On-road Wear',
        kind='slider',
        default=1.0,
        min_value=0.0,
        max_value=2.0,
        step=0.05,
        suffix='\u00d7',
        tooltip='Multiplier on every vehicle\'s CompanyAIConditionUsageMultiplier. '
                '1.0 = vanilla, below 1 = slower wear, above 1 = faster wear.',
    ),
    Setting(
        key='condition_offroad_multiplier',
        label='Offroad Wear',
        kind='slider',
        default=1.0,
        min_value=0.0,
        max_value=2.0,
        step=0.05,
        suffix='\u00d7',
        tooltip='Multiplier on every vehicle\'s CompanyAIConditionUsageMultiplierOffroad. '
                '1.0 = vanilla, below 1 = slower offroad wear, above 1 = faster.',
    ),
]


# ---------------------------------------------------------------------------
# Lua template
# ---------------------------------------------------------------------------
_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Company Vehicle Care
    =============================
    Scales three FVehicleRow fields on every vehicle in the Vehicles
    DataTables at session start:

      CompanyAIRunningCostMultiplier              - running cost
      CompanyAIConditionUsageMultiplier           - on-road wear
      CompanyAIConditionUsageMultiplierOffroad    - offroad wear

    Running Cost uses a Vanilla/Low/High/Off mode factor. The two
    wear axes use direct float multipliers (1.0 = vanilla, <1 = slower
    wear, >1 = faster wear, 0 = disabled).

    Baselines are captured per row on first apply, so re-applying does
    not compound.

    Generated by Frog Mod Editor. Values are hardcoded below - regenerate
    the mod from Frog to change them.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    RunningCostMode           = "{running_cost_mode}",
    ConditionMultiplier       = {condition_multiplier},
    ConditionOffroadMultiplier = {condition_offroad_multiplier},

    ModeFactor = {{
        Vanilla = 1.0,
        Low     = 0.5,
        High    = 1.5,
        Off     = 0.0,
    }},

    -- Match every /Game/DataAsset/Vehicles/*.uasset (DataTable OR
    -- CompositeDataTable), skip the Deprecated one.
    TargetDTSubstring  = "/Vehicles",
    ExcludeDTSubstring = "Deprecated",

    InitialDelayMs = 15000,
}}

local function Log(msg) print("[CryovacCompanyVehicleCare] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function FindVehicleDTs()
    local dts = FindAllOf("DataTable")
    if not dts then return {{}} end
    local count = 0
    pcall(function() count = #dts end)
    local matched = {{}}
    for i = 1, count do
        local dt = dts[i]
        local fullName = ""
        pcall(function() fullName = dt:GetFullName() end)
        if string.find(fullName, CONFIG.TargetDTSubstring, 1, true)
           and not string.find(fullName, CONFIG.ExcludeDTSubstring, 1, true) then
            matched[#matched + 1] = {{ dt = dt, name = fullName }}
        end
    end
    return matched
end

local applied = false
local vanilla_baseline = {{}}   -- [table][row] = {{running, cond, cond_off}}

local function ApplyScaling()
    if applied then return true end

    local rcFactor = CONFIG.ModeFactor[CONFIG.RunningCostMode]
    local cFactor  = CONFIG.ConditionMultiplier
    local coFactor = CONFIG.ConditionOffroadMultiplier
    if rcFactor == nil then
        Log("Unknown RunningCostMode: " .. tostring(CONFIG.RunningCostMode) .. "; aborting.")
        applied = true
        return true
    end

    -- If every axis is at vanilla (1.0x) nothing to do.
    if CONFIG.RunningCostMode == "Vanilla"
       and math.abs(cFactor - 1.0) < 1e-6
       and math.abs(coFactor - 1.0) < 1e-6 then
        Log("All axes at vanilla - no modifications applied.")
        applied = true
        return true
    end

    local matched = FindVehicleDTs()
    if #matched == 0 then return false end

    local total_mods = 0
    local sampleLogged = 0

    for _, m in ipairs(matched) do
        local dt, fullName = m.dt, m.name
        local rowNames = nil
        pcall(function() rowNames = dt:GetRowNames() end)
        if not rowNames then return false end
        local n = 0
        pcall(function() n = #rowNames end)
        if n == 0 then return false end

        Log(string.format("Matched %s (%d rows). RunningCost=%s (x%.3f)  "
            .. "OnRoadWear=x%.3f  OffroadWear=x%.3f",
            fullName, n,
            CONFIG.RunningCostMode, rcFactor,
            cFactor, coFactor))

        vanilla_baseline[fullName] = vanilla_baseline[fullName] or {{}}
        local baselineTbl = vanilla_baseline[fullName]
        local thisTableMods = 0

        for i = 1, n do
            local rowName = rowNames[i]
            local struct = nil
            pcall(function() struct = dt:FindRow(rowName, "VehicleCare", false) end)
            if struct then
                local key = tostring(rowName)
                if baselineTbl[key] == nil then
                    baselineTbl[key] = {{
                        running  = SafeGet(struct, "CompanyAIRunningCostMultiplier"),
                        cond     = SafeGet(struct, "CompanyAIConditionUsageMultiplier"),
                        cond_off = SafeGet(struct, "CompanyAIConditionUsageMultiplierOffroad"),
                    }}
                end
                local b = baselineTbl[key]
                local did = false
                if type(b.running) == "number" then
                    pcall(function()
                        struct.CompanyAIRunningCostMultiplier = b.running * rcFactor
                    end)
                    did = true
                end
                if type(b.cond) == "number" then
                    pcall(function()
                        struct.CompanyAIConditionUsageMultiplier = b.cond * cFactor
                    end)
                    did = true
                end
                if type(b.cond_off) == "number" then
                    pcall(function()
                        struct.CompanyAIConditionUsageMultiplierOffroad = b.cond_off * coFactor
                    end)
                    did = true
                end
                if did and sampleLogged < 6 then
                    local vR = SafeGet(struct, "CompanyAIRunningCostMultiplier") or 0
                    local vC = SafeGet(struct, "CompanyAIConditionUsageMultiplier") or 0
                    local vO = SafeGet(struct, "CompanyAIConditionUsageMultiplierOffroad") or 0
                    Log(string.format(
                        "  [%s] %s: running %.3f->%.3f  wear %.3f->%.3f  offroad %.3f->%.3f",
                        fullName:match("([^%.]+)$") or fullName, key,
                        b.running or 0, vR,
                        b.cond    or 0, vC,
                        b.cond_off or 0, vO))
                    sampleLogged = sampleLogged + 1
                end
                if did then thisTableMods = thisTableMods + 1 end
            end
        end

        Log(string.format("  -> Touched %d rows in %s.", thisTableMods, fullName))
        total_mods = total_mods + thisTableMods
    end

    Log(string.format("Applied Company Vehicle Care to %d rows across %d table(s).",
        total_mods, #matched))
    applied = true
    return true
end

Log("=== Cryovac Company Vehicle Care Loading ===")
Log(string.format("RunningCost=%s (x%.3f)  OnRoadWear=x%.3f  OffroadWear=x%.3f",
    CONFIG.RunningCostMode,
    CONFIG.ModeFactor[CONFIG.RunningCostMode] or 1.0,
    CONFIG.ConditionMultiplier,
    CONFIG.ConditionOffroadMultiplier))

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyScaling() then
        LoopAsync(5000, function() return ApplyScaling() end)
    end
end)

Log("=== Cryovac Company Vehicle Care Loaded ===")
'''


_VALID_MODES = {opt.key for opt in MODE_FACTOR_OPTIONS}


def _validate(config: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}

    rc = config.get('running_cost_mode', DEFAULT_CONFIG['running_cost_mode'])
    if rc not in _VALID_MODES:
        raise ValueError(f"Unknown running_cost_mode: {rc!r}. "
                         f"Expected one of {_VALID_MODES}")
    out['running_cost_mode'] = rc

    for key in ('condition_multiplier', 'condition_offroad_multiplier'):
        try:
            val = float(config.get(key, DEFAULT_CONFIG[key]))
        except (TypeError, ValueError):
            raise ValueError(f"{key} must be numeric")
        if not 0.0 <= val <= 2.0:
            raise ValueError(f"{key} {val} out of [0.0, 2.0]")
        out[key] = val

    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        running_cost_mode=cfg['running_cost_mode'],
        condition_multiplier=f"{cfg['condition_multiplier']:.3f}",
        condition_offroad_multiplier=f"{cfg['condition_offroad_multiplier']:.3f}",
    )


def _describe_wear(val: float) -> str:
    if val <= 0.0:
        return "disabled (no wear)"
    if abs(val - 1.0) < 1e-6:
        return "vanilla"
    if val < 1.0:
        return f"x{val:.2f} (wear at {val * 100:.0f}% of vanilla speed)"
    return f"x{val:.2f} (wear at {val * 100:.0f}% of vanilla speed)"


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    factors = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}
    body = (
        "Selected settings:\n"
        f"  Running Cost:   {cfg['running_cost_mode']} (x{factors[cfg['running_cost_mode']]})\n"
        f"  On-road Wear:   {_describe_wear(cfg['condition_multiplier'])}\n"
        f"  Offroad Wear:   {_describe_wear(cfg['condition_offroad_multiplier'])}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Scales three CompanyAI fields on every vehicle row in the\n"
        "Motor Town Vehicles DataTables. Baselines are captured per row\n"
        "on first apply so re-applying doesn't compound.\n\n"
        "  CompanyAIRunningCostMultiplier             (Running Cost)\n"
        "  CompanyAIConditionUsageMultiplier          (On-road Wear)\n"
        "  CompanyAIConditionUsageMultiplierOffroad   (Offroad Wear)\n\n"
        "Running Cost uses the Vanilla/Low/High/Off mode factor\n"
        "(0.5/1.0/1.5/0.0). The two wear axes are direct multipliers\n"
        "on vanilla wear speed:\n\n"
        "  0.0x    no wear at all\n"
        "  0.5x    half the vanilla wear speed\n"
        "  1.0x    vanilla\n"
        "  2.0x    twice the vanilla wear speed\n\n"
        "Running Cost = Vanilla and Wear = 1.0x both leave that axis\n"
        "untouched on every row.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    factors = {opt.key: opt.factor for opt in MODE_FACTOR_OPTIONS}
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={
            'running_cost': {'mode': cfg['running_cost_mode'],
                             'factor': factors[cfg['running_cost_mode']]},
            'condition_multiplier':          cfg['condition_multiplier'],
            'condition_offroad_multiplier':  cfg['condition_offroad_multiplier'],
        },
    )


import sys as _sys
register(_sys.modules[__name__])
