"""Cryovac Company Profit Boost — boosts the owner-profit-share
payout from AI-DRIVER deliveries made in vehicles your company owns.
Player-driven deliveries are NOT touched (the Economy Editor's
cargo-payment multiplier handles those — stacking the two would
double-multiply). Non-company vehicles are also untouched, so the
old INI-wide problem of boosting payouts on AI-company / rental
vehicles you don't own goes away.

Scope:
  - AI driver completes delivery in MY company's vehicle → BOOSTED
  - Player completes delivery in any vehicle              → not touched
  - AI driver completes delivery in someone else's vehicle → not touched

Mechanism: pre-hook on whichever AI-side profit-share RPC the
current MT build exposes, mutating the Money parameter in place
before vanilla executes. Result: the on-screen "+$X Owner's Profit
Share" popup AND the company transaction ledger both show the
single boosted number — no ghost second-line credit, no ambiguity.

Hook target discovery: the AI-side RPC name varies across MT
builds. The mod tries every plausible candidate at startup and
logs which ones registered. If none fire for AI deliveries, the
log will be silent on AI events and the user can use UE4SS Live
View to identify the right function name to add to HOOK_TARGETS.

At 1.0x the mod is a no-op and no hooks are installed."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCompanyProfitBoost'

UI_TITLE = 'Company Profit Boost'

UI_DESCRIPTION = (
    "<b>AI-driver deliveries only.</b> Multiplies the owner-profit-share "
    "payout when an AI driver hired by YOUR company completes a "
    "delivery in one of YOUR vehicles. Player deliveries are not "
    "touched \u2014 the Economy Editor's cargo-payment multiplier handles "
    "those, and stacking the two would double-multiply. Vehicles "
    "owned by AI companies, rentals, or other players are also "
    "untouched (this is the runtime-Lua replacement for the old "
    "INI-wide profit-share preset, which boosted EVERY company's "
    "vehicles indiscriminately).\n\n"
    "How the filter works: when the AI profit-share RPC fires, the "
    "mod compares the vehicle's <code>Net_OwnerCompanyGuid</code> "
    "against a list of companies the local player owns. Match \u2192 "
    "rewrite the Money parameter to <code>floor(money \u00d7 multiplier)</code> "
    "BEFORE vanilla runs. No match \u2192 leave it untouched.\n\n"
    "Hook target discovery: the AI-side profit-share function name "
    "varies across MT builds. The mod tries every plausible "
    "candidate at startup and logs which ones registered. If your "
    "AI deliveries still aren't boosted after deploying, open "
    "<code>UE4SS.log</code> and look for the line "
    "<code>Hooks registered (N): A, B, C</code> \u2014 that's the list "
    "of active hooks. If no AI-related entry shows up, use UE4SS "
    "Live View to find the AI delivery function on this build "
    "(MTAIController / MTCompanySystem / MotorTownGameMode \u2014 look "
    "for 'Profit', 'Reward', 'Delivery') and report the name.\n\n"
    "<b>1.0\u00d7</b> \u2014 no change. Mod is a no-op (hooks not installed).<br>"
    "<b>2.0\u00d7</b> \u2014 AI driver profit shares from your vehicles pay double.<br>"
    "<b>5.0\u00d7</b> \u2014 AI driver profit shares from your vehicles pay 5\u00d7 vanilla.\n\n"
    "Runs on the SERVER (host / dedicated)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'multiplier': 1.0,
}

SETTINGS = [
    Setting(
        key='multiplier',
        label='Company profit multiplier',
        kind='slider',
        default=1.0,
        min_value=1.0,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip='Scale the owner-profit-share payout on your own company\'s '
                'vehicles only. 1.0 = no change, 2.0 = +100% bonus, '
                '5.0 = +400% bonus. Non-company vehicles stay vanilla.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Company Profit Boost
    =============================
    Boosts the owner-profit-share payout ONLY on vehicles your
    company owns. Non-company vehicles stay vanilla.

    Mechanism: pre-hook on
        MotorTownPlayerController:ServerGiveOwnerProfitShare(
            Vehicle, Money, TxType)
    When Vehicle.Net_OwnerCompanyGuid matches a company the local
    player owns, we rewrite the Money parameter IN PLACE to
    floor(Money * Multiplier) before vanilla executes. Vanilla then
    pays out the boosted amount as a single transaction, so both the
    on-screen popup and the company ledger reflect the real total.

    Generated by Frog Mod Editor. Multiplier is hardcoded below;
    regenerate from Frog to change it.

    Runs on SERVER (host / dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Multiplier = {multiplier},

    -- How frequently we rediscover the player's owned-company list
    -- (handles newly-founded or left companies mid-session).
    OwnerRescanEverySec = 30,
}}

local function Log(msg) print("[CryovacCompanyProfitBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function Unwrap(obj)
    if obj == nil then return nil end
    -- UE4SS wraps primitives and structs as accessors. Try :get() first,
    -- fall back to the raw value if it's already unwrapped.
    local ok, val = pcall(function() return obj:get() end)
    if ok and val ~= nil then return val end
    return obj
end

local function GuidsEqual(g1, g2)
    if not g1 or not g2 then return false end
    return (SafeGet(g1, "A") == SafeGet(g2, "A"))
       and (SafeGet(g1, "B") == SafeGet(g2, "B"))
       and (SafeGet(g1, "C") == SafeGet(g2, "C"))
       and (SafeGet(g1, "D") == SafeGet(g2, "D"))
end

local function GuidAsString(g)
    if not g then return "<nil>" end
    return string.format("%08x-%08x-%08x-%08x",
        SafeGet(g, "A") or 0, SafeGet(g, "B") or 0,
        SafeGet(g, "C") or 0, SafeGet(g, "D") or 0)
end

-- Cached list of (MTCompanySystem, CompanyGuid) for the local player's
-- owned companies. Refreshed on a slow cadence so newly-founded
-- companies start getting the boost without requiring a relaunch.
local ownedCompanies = {{}}

-- Field-name cache for MTCompany's owner-character GUID. Motor Town's
-- MTCompany struct exposes the owner under a name that varies across
-- builds (and at least one variant -- "Net_OwnerCharacterGuid" -- is
-- registered in metadata but errors loudly inside UE4SS's reflection
-- layer when read, spamming the log every 30s as we rescan). We
-- discover the working name on the first successful read, cache it,
-- and skip the others forever after. If no candidate works the cache
-- stays nil and we log a single warning instead of failing silently.
local ownerGuidField = nil           -- the field name that worked
local ownerGuidDiscoveryDone = false -- avoid re-warning on every refresh
local OWNER_GUID_CANDIDATES = {{
    -- Order matters: try the most likely current-build name first.
    -- "Net_OwnerCharacterGuid" is intentionally absent — it is
    -- metadata-mapped on MTCompany but UE4SS cannot retrieve it on
    -- this build, and even pcall can't suppress the engine-level
    -- error spam it produces.
    "OwnerCharacterGuid",
    "FounderCharacterGuid",
}}

local function GetCompanyOwnerGuid(co)
    if ownerGuidField then
        return SafeGet(co, ownerGuidField)
    end
    for _, name in ipairs(OWNER_GUID_CANDIDATES) do
        local v = SafeGet(co, name)
        if v ~= nil then
            ownerGuidField = name
            Log(string.format("MTCompany owner field discovered: %s", name))
            return v
        end
    end
    return nil
end

local function FindLocalPlayerCharacterGuid()
    -- Find the local PlayerController + the character GUID the player
    -- currently controls. In the company-system list, a company lists
    -- its owner by character GUID, so this is what we compare against.
    local pcs = FindAllOf("MotorTownPlayerController")
    if not pcs then return nil end
    local count = 0
    pcall(function() count = #pcs end)
    for i = 1, count do
        local pc = pcs[i]
        local isLocal = false
        pcall(function() isLocal = pc:IsLocalController() end)
        if isLocal then
            -- Try a few paths to get the character GUID.
            local ps = SafeGet(pc, "PlayerState")
            if ps then
                local cid = SafeGet(ps, "Net_OwnerCharacterId")
                if cid then
                    local g = SafeGet(cid, "CharacterGuid")
                    if g then return g end
                end
                local g2 = SafeGet(ps, "Net_OwnerCharacterGuid")
                if g2 then return g2 end
            end
        end
    end
    return nil
end

local function RefreshOwnedCompanies()
    ownedCompanies = {{}}
    local myCharacterGuid = FindLocalPlayerCharacterGuid()
    if not myCharacterGuid then
        return
    end

    local systems = FindAllOf("MTCompanySystem")
    if not systems then return end
    local sysCount = 0
    pcall(function() sysCount = #systems end)

    for s = 1, sysCount do
        local cs = systems[s]
        local companies = SafeGet(cs, "Server_Companies")
        if companies then
            local count = 0
            pcall(function() count = #companies end)
            for i = 1, count do
                local co = companies[i]
                -- Company's founding owner. Cached field name lookup —
                -- see GetCompanyOwnerGuid for the discovery logic.
                local ownerGuid = GetCompanyOwnerGuid(co)
                if GuidsEqual(ownerGuid, myCharacterGuid) then
                    local guid = SafeGet(co, "Guid")
                    if guid then
                        ownedCompanies[#ownedCompanies + 1] = {{
                            system = cs,
                            guid = guid,
                            name = SafeGet(co, "Net_CompanyName") or "<?>",
                        }}
                    end
                end
            end
        end
    end

    if #ownedCompanies > 0 then
        local names = {{}}
        for _, c in ipairs(ownedCompanies) do
            names[#names + 1] = tostring(c.name)
        end
        Log("Owned companies: " .. table.concat(names, ", "))
    elseif not ownerGuidDiscoveryDone then
        ownerGuidDiscoveryDone = true
        if ownerGuidField then
            -- Field name worked but no companies matched the local
            -- player's character GUID — they don't own any company yet.
            -- The boost won't fire until the player founds one.
            Log("No owned companies (matched field: " .. ownerGuidField
                .. "). Boost will not fire until the player founds a "
                .. "company. Re-scan happens every 30s.")
        else
            -- Every candidate field returned nil. We can't safely scope
            -- the boost to "MY company's vehicles" without knowing what
            -- companies the player owns. Stay idle rather than fall
            -- back to "boost everyone" — that's the old INI-wide
            -- behaviour we were specifically replacing.
            Log("MTCompany owner-GUID field not exposed on this build. "
                .. "Boost cannot fire (we won't fall back to boosting "
                .. "every company's vehicles indiscriminately — that "
                .. "was the v6 INI-wide behaviour this mod replaces). "
                .. "Use UE4SS Live View on MTCompany to find the real "
                .. "owner-character field name and report it so we can "
                .. "add it to OWNER_GUID_CANDIDATES.")
        end
    end
end

local function IsOwnedByMyCompany(vehicle)
    if not vehicle or #ownedCompanies == 0 then return false end
    local vg = SafeGet(vehicle, "Net_OwnerCompanyGuid")
    if not vg then return false end
    for _, c in ipairs(ownedCompanies) do
        if GuidsEqual(vg, c.guid) then
            return true, c
        end
    end
    return false, nil
end

-- ============================================================
-- Hook targets to try. Player path is confirmed; the AI-driver
-- paths are best-guess names — UE4SS RegisterHook fails silently
-- if a target doesn't exist, so the wrong ones drop out and the
-- right ones (if any) start firing. Add more here as we learn
-- the actual function names per MT build.
-- AI-side profit-share hook targets. The player-controller RPC
-- (MotorTownPlayerController:ServerGiveOwnerProfitShare) is
-- INTENTIONALLY ABSENT from this list — player cargo income is
-- the Economy Editor's job, and hooking it here would
-- double-multiply when both mods are active.
--
-- The right AI-side function name varies across MT builds.
-- UE4SS RegisterHook fails silently for non-existent targets when
-- wrapped in pcall, so listing every plausible candidate is safe:
-- the wrong ones drop out, the right one (if present) starts firing.
local HOOK_TARGETS = {{
    -- AI controller variants
    "/Script/MotorTown.MotorTownAIController:ServerGiveOwnerProfitShare",
    "/Script/MotorTown.MTAIController:ServerGiveOwnerProfitShare",
    "/Script/MotorTown.MTAICharacter:ServerGiveOwnerProfitShare",
    "/Script/MotorTown.MotorTownAIController:GiveOwnerProfitShare",
    "/Script/MotorTown.MTAIController:GiveOwnerProfitShare",
    -- Company-system level (server-side delivery callback)
    "/Script/MotorTown.MTCompanySystem:GiveOwnerProfitShare",
    "/Script/MotorTown.MTCompanySystem:Server_GiveOwnerProfitShare",
    "/Script/MotorTown.MTCompanySystem:OnAIDeliveryCompleted",
    "/Script/MotorTown.MTCompanySystem:AddDeliveryProfitShare",
    -- Game-mode level (catches both player + AI on some builds, but
    -- our company-membership filter will still skip non-owned
    -- vehicles, so the mod stays scoped correctly even if this
    -- catches a player call by accident)
    "/Script/MotorTown.MotorTownGameMode:GiveOwnerProfitShare",
    "/Script/MotorTown.MotorTownGameMode:OnDeliveryCompleted",
}}

-- Single shared boost handler used by every successfully-registered
-- hook. `self` may be an AIController, CompanySystem, or GameMode
-- depending on which RPC fired — the handler only cares about the
-- vehicle parameter and its owner-company GUID. The local-controller
-- fallback that earlier versions used is INTENTIONALLY GONE: it was
-- there to catch the local player's own deliveries, which are no
-- longer in scope (Economy Editor handles them). For AI deliveries
-- the company-membership match is the only path, so if MTCompany
-- field discovery fails, the boost won't fire — and the user sees
-- the "MTCompany owner-GUID field not exposed" startup warning so
-- the situation is diagnosable.
local function BoostHandler(hookName)
    return function(self, vehicleWrap, moneyWrap, txTypeWrap)
        local vehicle = Unwrap(vehicleWrap)
        if not vehicle then return end

        -- Only path: vehicle's owner-company GUID matches one of the
        -- local player's owned companies. This is what scopes the
        -- mod to "MY company's AI vehicles" — vehicles owned by AI
        -- companies, rentals, or other players never match.
        local matched, company = IsOwnedByMyCompany(vehicle)
        if not matched then return end

        local money = Unwrap(moneyWrap) or 0
        if type(money) ~= "number" or money <= 0 then return end

        local boosted = math.floor(money * CONFIG.Multiplier)
        if boosted <= money then return end  -- no-op guard

        local setOk, setErr = pcall(function()
            moneyWrap:set(boosted)
        end)
        if setOk then
            Log(string.format(
                "boost applied: %d -> %d (x%.2f) via=%s company=%s",
                money, boosted, CONFIG.Multiplier, hookName, tostring(company.name)))
        else
            Log("param :set() failed on " .. hookName .. ": " .. tostring(setErr)
                .. " (vanilla payout unchanged)")
        end
    end
end

-- Hook: try every candidate target. Each pcall'd registration that
-- succeeds adds another firing site for the boost. AI driver coverage
-- depends on whether MT exposes one of the candidate AI paths on the
-- user's build.
local function SetupHook()
    if math.abs(CONFIG.Multiplier - 1.0) < 1e-6 then
        Log("Multiplier = 1.0 -- no hooks installed (mod is a no-op).")
        return
    end
    local registered = 0
    local registeredNames = {{}}
    for _, target in ipairs(HOOK_TARGETS) do
        -- Short label for the log line: just the trailing
        -- ClassName:FunctionName, drop the /Script/Module. prefix.
        local label = target
        local lastSlash = string.find(string.reverse(target), "/", 1, true)
        if lastSlash then
            label = string.sub(target, #target - lastSlash + 2)
        end
        local ok, err = pcall(function()
            RegisterHook(target, BoostHandler(label))
        end)
        if ok then
            registered = registered + 1
            registeredNames[#registeredNames + 1] = label
        end
    end
    if registered == 0 then
        Log("WARNING: no AI-side hook targets registered on this build. "
            .. "Boost will not fire. Use UE4SS Live View to find the AI "
            .. "delivery profit-share function (search MTAIController / "
            .. "MTCompanySystem / MotorTownGameMode for 'Profit', "
            .. "'Reward', 'Delivery') and report the name so we can add "
            .. "it to HOOK_TARGETS.")
    else
        Log(string.format("Hooks registered (%d): %s",
            registered, table.concat(registeredNames, ", ")))
        Log("Player deliveries are NOT boosted by this mod (Economy "
            .. "Editor handles those). Vehicles not owned by your "
            .. "company are also untouched. If an AI delivery in YOUR "
            .. "vehicle fires no 'boost applied' line in the log, "
            .. "either none of the registered hooks is the right one "
            .. "or MTCompany owner-GUID discovery failed (separate "
            .. "warning above).")
    end
end

-- ============================================================
-- Init
-- ============================================================
Log("=== Cryovac Company Profit Boost Loading ===")
Log(string.format("Multiplier: x%.2f", CONFIG.Multiplier))

-- Seed the owned-companies list once things are loaded.
ExecuteWithDelay(15000, function()
    RefreshOwnedCompanies()
    SetupHook()
end)

-- Rescan periodically so a freshly-founded company starts benefiting
-- without forcing a relaunch.
LoopAsync(CONFIG.OwnerRescanEverySec * 1000, function()
    RefreshOwnedCompanies()
    return false  -- keep looping
end)

Log("=== Cryovac Company Profit Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    try:
        val = float(config.get('multiplier', DEFAULT_CONFIG['multiplier']))
    except (TypeError, ValueError):
        raise ValueError("multiplier must be numeric")
    if not 1.0 <= val <= 10.0:
        raise ValueError(f"multiplier {val} out of sanity range [1.0, 10.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(multiplier=f"{val:.3f}")


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    if abs(val - 1.0) < 1e-6:
        effect = "no change (mod is a no-op, hooks not installed)"
    else:
        pct = val * 100.0
        effect = f"AI driver deliveries in your company's vehicles pay {pct:.0f}% of vanilla"
    body = (
        f"Multiplier: x{val:.2f}  ({effect})\n\n"
        "SCOPE\n"
        "-----\n"
        "AI-DRIVER deliveries only. Player deliveries are NOT touched\n"
        "by this mod -- the Economy Editor's cargo-payment multiplier\n"
        "handles those, and stacking the two would double-multiply.\n"
        "Vehicles owned by AI companies, rentals, or other players are\n"
        "also untouched -- the boost is scoped to YOUR company's vehicles\n"
        "by matching the vehicle's Net_OwnerCompanyGuid against the list\n"
        "of companies the local player owns.\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Pre-hooks the AI-side profit-share RPC. The exact function\n"
        "name varies across MT builds, so the mod tries every plausible\n"
        "candidate at startup (MotorTownAIController, MTAIController,\n"
        "MTAICharacter, MTCompanySystem, MotorTownGameMode variants).\n"
        "Whichever target is real on this build gets registered.\n\n"
        "When the hook fires for an AI delivery in one of YOUR vehicles,\n"
        "the mod rewrites the Money parameter to floor(Money * multiplier)\n"
        "BEFORE vanilla runs. Vanilla then pays out the boosted amount\n"
        "as a single transaction -- the company transaction ledger\n"
        "reflects the real total, no second-line credit.\n\n"
        "OWNER LOOKUP\n"
        "------------\n"
        "Walks MTCompanySystem.Server_Companies every 30s and picks out\n"
        "the ones whose OwnerCharacterGuid (or FounderCharacterGuid)\n"
        "matches the local player's character GUID. Companies founded\n"
        "mid-session start getting the boost within the next 30s.\n\n"
        "If MTCompany doesn't expose a recognised owner-GUID field on\n"
        "this build, the mod logs a warning and stays idle (the boost\n"
        "won't fire). Without owner identification we can't safely\n"
        "scope the boost to YOUR company without falling back to the\n"
        "old 'boost everyone's payouts' behaviour we were specifically\n"
        "trying to avoid.\n\n"
        "DIAGNOSING ISSUES\n"
        "-----------------\n"
        "Look at UE4SS.log for these lines from this mod:\n"
        "  '=== Cryovac Company Profit Boost Loaded ==='\n"
        "    -> mod loaded successfully.\n"
        "  'Hooks registered (N): A, B, C'\n"
        "    -> N hook targets registered. If N is 0, your build\n"
        "       doesn't expose any of the candidates we tried; report\n"
        "       which AI-side function MT actually calls.\n"
        "  'Owned companies: NAME1, NAME2'\n"
        "    -> owner discovery worked, mod knows what to scope to.\n"
        "  'MTCompany owner-GUID field not exposed on this build'\n"
        "    -> owner discovery failed; boost cannot fire on this\n"
        "       build until the right field name is identified.\n"
        "  'boost applied: X -> Y (x2.00) via=HookName company=Name'\n"
        "    -> a delivery was just boosted.\n\n"
        "Runs server-side. On a dedicated server, install on the host.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'multiplier': val, 'bonus_percent': (val - 1.0) * 100.0},
    )


import sys as _sys
register(_sys.modules[__name__])
