"""Cryovac Company Vehicle Limits — raises the vanilla "Add Slot"
cap on the company-vehicles purchase dialog from 5 additional up to
a configurable ceiling. The user still pays for every slot through
the in-game dialog; this mod only intervenes when vanilla silently
refuses a confirmed purchase inside the allowed window."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacCompanyVehicleLimits'

UI_TITLE = 'Company Vehicle Limits'

UI_DESCRIPTION = (
    "Extends the vanilla \"Add Slot\" purchase cap on the company-vehicles "
    "dialog from the default 5 additional slots up to your configured "
    "ceiling. The user still purchases each slot through the normal "
    "in-game dialog; the mod only intervenes when vanilla silently "
    "refuses a confirmed purchase inside the allowed window.\n\n"
    "Hard game limit is 15 additional (20 total including the vanilla "
    "starting slots) — going higher is accepted by the dialog but the "
    "UI caps at 20."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'max_added_slots': 15,
}

SETTINGS = [
    Setting(
        key='max_added_slots',
        label='Max added slots',
        kind='int',
        default=15,
        min_value=5,
        max_value=15,
        step=1,
        suffix=' slots',
        tooltip='How many slots the mod will allow beyond the vanilla 5 '
                'base slots. 5 = vanilla behavior (mod does nothing). '
                '15 = allow every purchasable slot (UI caps at 20 total).',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Company Vehicle Limits
    ================================
    Extends the vanilla "Add Slot" purchase cap from 5 additional up to
    MaxAddedSlots additional slots.

    The user still purchases each slot through the normal in-game
    dialog. The mod only intervenes when vanilla silently refuses a
    confirmed purchase inside the allowed window - in that case it
    grants the slot that vanilla would have given if its cap were
    higher.

    When the user is past the point where vanilla shows its "You
    cannot have more" popup, the RPC never fires and the mod stays
    out of the way. The game's popup stands.

    Generated by Frog Mod Editor. MaxAddedSlots is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    MaxAddedSlots   = {max_added_slots},
    PostCallDelayMs = 100,
}}

local function Log(msg) print("[CryovacVehicleLimits] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function GuidsEqual(g1, g2)
    if not g1 or not g2 then return false end
    return (SafeGet(g1, "A") == SafeGet(g2, "A"))
       and (SafeGet(g1, "B") == SafeGet(g2, "B"))
       and (SafeGet(g1, "C") == SafeGet(g2, "C"))
       and (SafeGet(g1, "D") == SafeGet(g2, "D"))
end

local function FindCompanyByGuid(guid)
    local systems = FindAllOf("MTCompanySystem")
    if not systems then return nil end
    for _, cs in ipairs(systems) do
        local companies = SafeGet(cs, "Server_Companies")
        if companies then
            local count = 0
            pcall(function() count = #companies end)
            for i = 1, count do
                local co = companies[i]
                if GuidsEqual(SafeGet(co, "Guid"), guid) then
                    return cs, co, i
                end
            end
        end
    end
    return nil
end

local function SetupHook()
    local ok, err = pcall(function()
        RegisterHook("/Script/MotorTown.MotorTownPlayerController:ServerAddCompanyVehicleSlot",
            function(self, companyGuid)
                local guid = companyGuid
                pcall(function()
                    local unwrapped = companyGuid:get()
                    if unwrapped then guid = unwrapped end
                end)
                if not guid then return end

                local cs, co, idx = FindCompanyByGuid(guid)
                if not co then
                    Log("rpc: company not found for GUID; skipping")
                    return
                end
                local before = SafeGet(co, "AddedVehicleSlots") or 0

                ExecuteWithDelay(CONFIG.PostCallDelayMs, function()
                    local cs2, co2, idx2 = FindCompanyByGuid(guid)
                    if not co2 then return end
                    local after = SafeGet(co2, "AddedVehicleSlots")
                    if after == nil then return end

                    if after > before then
                        Log(string.format("vanilla purchased slot #%d (%d -> %d), no intervention",
                            after, before, after))
                        return
                    end

                    if before >= CONFIG.MaxAddedSlots then
                        Log(string.format("at cap (AddedVehicleSlots=%d, MaxAddedSlots=%d), not extending",
                            before, CONFIG.MaxAddedSlots))
                        return
                    end

                    local newSlots = before + 1
                    pcall(function() cs2.Server_Companies[idx2].AddedVehicleSlots = newSlots end)
                    pcall(function() co2.AddedVehicleSlots = newSlots end)
                    Log(string.format("extended past vanilla cap: %d -> %d",
                        before, newSlots))
                end)
            end)
    end)
    if ok then
        Log("Hook registered: MotorTownPlayerController:ServerAddCompanyVehicleSlot")
    else
        Log("Hook failed: " .. tostring(err))
    end
end

Log("=== Cryovac Company Vehicle Limits Loading ===")
Log(string.format("MaxAddedSlots=%d (UI total up to %d) | PostCallDelayMs=%d",
    CONFIG.MaxAddedSlots, CONFIG.MaxAddedSlots + 5, CONFIG.PostCallDelayMs))

SetupHook()

Log("=== Cryovac Company Vehicle Limits Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> int:
    val = int(config.get('max_added_slots', DEFAULT_CONFIG['max_added_slots']))
    if val < 5:
        raise ValueError(f"max_added_slots {val} < 5 (vanilla minimum)")
    if val > 50:
        raise ValueError(f"max_added_slots {val} > 50 (upper sanity limit)")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    max_slots = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(max_added_slots=max_slots)


def generate_readme(config: Dict[str, Any]) -> str:
    max_slots = _validate(config)
    body = (
        f"Configured MaxAddedSlots: {max_slots} (UI total up to {max_slots + 5})\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Intercepts the vanilla ServerAddCompanyVehicleSlot RPC. When a\n"
        "confirmed purchase should have succeeded but vanilla silently\n"
        "rejects it (because it hit the built-in 5-slot cap), the mod\n"
        "adds the slot directly up to MaxAddedSlots. The user still pays\n"
        "for each slot through the normal in-game dialog.\n\n"
        "If MaxAddedSlots = 5, the mod does nothing (matches vanilla).\n"
        "If MaxAddedSlots = 15, you can purchase up to 15 additional\n"
        "slots - the game's UI caps visible slots at 20 total.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    max_slots = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'max_added_slots': max_slots},
    )


import sys as _sys
register(_sys.modules[__name__])
