"""Cryovac Contract Payment Boost — multiplies the cash payout on
every active contract.

Targets ``FMTContract.CompletionPayment`` (FMTShadowedInt64) on every
contract in ``UMTCompany.ContractsInProgress[]``. The shadowed-int64
holds two parallel int64s (``BaseValue`` and ``ShadowedValue``) that
the game cross-checks for anti-tamper; we set both so the reward is
honoured rather than reset.

Why polling instead of hooking
------------------------------
Motor Town's ``ServerSignContract`` RPC takes the contract as a
``const`` reference, and there's no observable ``ServerCompleteContract``
RPC to install a pre-hook on (contract completion runs entirely
inside the server tick). Polling every 5s catches new contracts
shortly after sign and keeps already-active contracts boosted in
case a save/load resets values.

Per-GUID baselines are captured on first sighting so repeated polls
don't compound the multiplier on the same contract.

Server-side mod (host or dedicated). For multiplayer, the host runs
this — clients see the boosted payouts via the normal money-sync
flow.
"""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacContractPaymentBoost'

UI_TITLE = 'Contract Payment Boost'

UI_DESCRIPTION = (
    "Multiplies <code>CompletionPayment</code> on every contract in "
    "<code>UMTCompany.ContractsInProgress[]</code>. A 2× setting "
    "doubles the cash you get when you finish a delivery contract; "
    "5× quintuples it.\n\n"
    "Polls every 5 seconds so newly-signed contracts get the boost "
    "shortly after you take them on. Per-contract baselines are "
    "captured on first sighting so repeated polls don't compound.\n\n"
    "<b>1.0×</b> — vanilla payouts, no change.<br>"
    "<b>2.0×</b> — every contract pays double.<br>"
    "<b>5.0×</b> — every contract pays 5×.<br>"
    "<b>10.0×</b> — sandbox-mode payouts, useful for testing.\n\n"
    "Note: this is distinct from <i>Company Profit Boost</i> "
    "(which targets the per-delivery owner-share via "
    "<code>ServerGiveOwnerProfitShare</code>). You can run both — "
    "the boosts compound multiplicatively for company-vehicle "
    "deliveries on contracts."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'multiplier': 1.0,
}

SETTINGS = [
    Setting(
        key='multiplier',
        label='Contract payment multiplier',
        kind='float',
        default=1.0,
        min_value=0.25,
        max_value=10.0,
        step=0.25,
        suffix='×',
        tooltip='Scale the CompletionPayment on every active contract. '
                '1.0 = vanilla, 2.0 = double payouts, 0.5 = half. '
                'Affects all companies (player and AI), but AI '
                'payments don\'t reach you so only your own contracts '
                'are user-visible.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Contract Payment Boost
    ===============================
    Multiplies CompletionPayment on every contract in
    UMTCompany.ContractsInProgress[].

    The payment is stored as FMTShadowedInt64 with two parallel
    int64 fields (BaseValue + ShadowedValue) cross-checked by the
    game for anti-tamper. We set both so the boost is honoured
    rather than reset on the next sync.

    Per-contract GUID baselines mean we never compound the
    multiplier on the same contract across polls. Newly-signed
    contracts get the boost on the next 5s tick.

    Generated by Frog Mod Editor. Multiplier is hardcoded below
    — regenerate the mod from Frog to change it.

    Server-side (host / dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Multiplier     = {multiplier},
    PollIntervalMs = 5000,
}}

local function Log(msg) print("[CryovacContractPaymentBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- Per-contract-GUID baselines.
--   baseline[guidString] = vanilla CompletionPayment.BaseValue
local baseline = {{}}

-- Format a Guid struct into a stable key. UE4SS exposes FGuid as
-- four uint32s (A/B/C/D); concat them into a single string.
local function GuidKey(guid)
    if not guid then return nil end
    local a = SafeGet(guid, "A") or 0
    local b = SafeGet(guid, "B") or 0
    local c = SafeGet(guid, "C") or 0
    local d = SafeGet(guid, "D") or 0
    return string.format("%08x-%08x-%08x-%08x", a, b, c, d)
end

local function BoostContract(contractInProgress)
    local guid = SafeGet(contractInProgress, "Guid")
    local key = GuidKey(guid)
    if not key then return false end

    local contract = SafeGet(contractInProgress, "Contract")
    if not contract then return false end

    local completion = SafeGet(contract, "CompletionPayment")
    if not completion then return false end

    local current = SafeGet(completion, "BaseValue")
    if type(current) ~= "number" then return false end

    -- Capture the vanilla value the first time we see this contract.
    -- Once captured, any later polls multiply against the captured
    -- value rather than the (possibly already-boosted) current.
    if baseline[key] == nil then
        baseline[key] = current
    end

    local target = math.floor(baseline[key] * CONFIG.Multiplier + 0.5)

    -- Skip if already at target (avoids repeated writes / log spam).
    if current == target then return false end

    -- Set BOTH fields. The game cross-checks them; setting only
    -- BaseValue triggers the anti-tamper reset.
    local ok = pcall(function()
        completion.BaseValue = target
        completion.ShadowedValue = target
    end)
    return ok
end

local function BoostAllContracts()
    local companies = FindAllOf("MTCompany")
    if not companies then return 0, 0 end
    local count = 0
    pcall(function() count = #companies end)

    local seen = 0
    local applied = 0

    for i = 1, count do
        local company = companies[i]
        if company ~= nil then
            local contracts = SafeGet(company, "ContractsInProgress")
            if contracts then
                local n = 0
                pcall(function() n = #contracts end)
                for j = 1, n do
                    seen = seen + 1
                    local cip = contracts[j]
                    if cip and BoostContract(cip) then
                        applied = applied + 1
                    end
                end
            end
        end
    end

    return seen, applied
end

Log("=== Cryovac Contract Payment Boost Loading ===")
Log(string.format("Multiplier=x%.2f", CONFIG.Multiplier))

local lastSeen = -1
LoopAsync(CONFIG.PollIntervalMs, function()
    local seen, applied = BoostAllContracts()
    if seen ~= lastSeen then
        Log(string.format("Poll: %d active contracts, %d freshly boosted this cycle",
            seen, applied))
        lastSeen = seen
    end
    return false  -- keep looping
end)

Log("=== Cryovac Contract Payment Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, Any]:
    """Coerce + clamp the config. Out-of-range or non-numeric raises
    so deploy fails loudly rather than producing a silent no-op Lua."""
    out: Dict[str, Any] = {}
    for s in SETTINGS:
        val = config.get(s.key, s.default)
        try:
            val = float(val)
        except (TypeError, ValueError):
            raise ValueError(f"{s.key} must be numeric")
        if not 0.25 <= val <= 10.0:
            raise ValueError(f"{s.key} = {val} out of range [0.25, 10.0]")
        out[s.key] = val
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        multiplier=f"{cfg['multiplier']:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    body = (
        f"Multiplier (applied every 5 seconds to every active contract):\n"
        f"  Contract Payment: x{cfg['multiplier']:.2f}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Every 5 seconds the mod scans every UMTCompany in the world\n"
        "(player + AI). For each company, it walks ContractsInProgress[]\n"
        "and for each contract:\n\n"
        "  1. Reads Contract.CompletionPayment.BaseValue (the cash you\n"
        "     get when the contract finishes).\n"
        "  2. Captures it as a per-GUID baseline on first sighting.\n"
        "  3. Sets BaseValue AND ShadowedValue to (baseline * multiplier).\n"
        "     Both must be set or the game's anti-tamper check resets\n"
        "     them on the next sync.\n\n"
        "Per-contract baselines mean repeated polls don't compound the\n"
        "boost. Newly-signed contracts get boosted on the next 5s tick.\n\n"
        "RELATIONSHIP TO COMPANY PROFIT BOOST\n"
        "------------------------------------\n"
        "This mod is independent from CryovacCompanyProfitBoost:\n"
        "  - CompanyProfitBoost hooks ServerGiveOwnerProfitShare to\n"
        "    rewrite per-delivery owner-share payouts in real time,\n"
        "    only on vehicles your company owns.\n"
        "  - This mod modifies the contract's saved CompletionPayment\n"
        "    field, which pays out when the contract is fully done.\n\n"
        "Running both stacks the multipliers (e.g. 2x contract +\n"
        "2x profit-share = 4x net for a company-vehicle delivery).\n\n"
        "MULTIPLAYER\n"
        "-----------\n"
        "Server-side mod. The host runs it; clients see the boosted\n"
        "payouts via the normal money-sync flow. AI companies\n"
        "(non-player) get the boost too but it doesn't reach the\n"
        "player so it's invisible.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
