"""Frog Mod Engine Volume — UE4SS Lua mod that applies per-engine
MasterVolume multipliers to modded engines at runtime.

Why this exists
---------------
The Engine Creator's Volume Adjustment slider stores an integer offset
(-25..+25) per engine in the engine's ``.creation.json`` sidecar.
That value alone does nothing in-game — Motor Town's
``MTEngineSoundDataAsset`` doesn't serialise tagged volume properties,
so we can't bake the multiplier into the asset without complex binary
surgery (adding new tagged FloatProperties to a class with no existing
ones).

Instead, this deployer scans every engine's ``.creation.json`` for
non-zero ``volume_offset`` values, builds a Lua mod that maps engine
names to MasterVolume multipliers, and writes the mod folder. The Lua
side polls ``FindAllOf("MHEngineDataAsset")`` every few seconds, looks
up each loaded engine in the embedded table, and writes
``MasterVolume`` on its ``EngineSoundData`` instance.

Conventions match the Cryovac mods:
  - Generated folder name: ``FrogModEngineVolume``
  - Default output: ``data/lua_mod_output/FrogModEngineVolume/``
  - One Lua file (``Scripts/main.lua``), README, mod_info.json,
    enabled.txt — all written via ``write_mod_folder`` from
    ``_shared.py``.

The deployer is unusual compared to the other mods: it has no
user-tunable SETTINGS. Its "config" is the live state of the engine
workspace, collected by ``collect_engine_offsets()`` and passed
through ``deploy()``.
"""
from __future__ import annotations

import glob
import json
import logging
import os
import re
import shutil
from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder

logger = logging.getLogger(__name__)


MOD_NAME = 'FrogModEngineVolume'

UI_TITLE = 'Engine Volume Adjustments'

UI_DESCRIPTION = (
    "Applies the per-engine Volume Adjustment slider settings from the "
    "Engine Creator. The slider's offset (-25..+25) maps to a "
    "MasterVolume multiplier (1.0 + offset * 0.04), which this Lua mod "
    "writes onto the engine's UMTEngineSoundDataAsset at runtime.\n\n"
    "Auto-regenerated whenever you save an engine in the Engine "
    "Creator. If every modded engine has volume_offset = 0, the mod "
    "folder is removed entirely so no Lua runs in-game."
)

# This deployer doesn't expose user-facing controls — its "config" is
# the dict {engine_name -> int offset} sourced from the workspace's
# .creation.json sidecars. Kept as empty placeholders so the registry
# checks pass.
DEFAULT_CONFIG: Dict[str, Any] = {}
SETTINGS = []  # type: ignore[var-annotated]


_PERCENT_PER_STEP = 4  # match VolumeOffsetWidget.PERCENT_PER_STEP

# Regex used to validate engine names before embedding them in Lua.
# We only let through identifier-safe characters so we can't accidentally
# emit something that would break Lua's string parser. Engine names in
# Motor Town only use [A-Za-z0-9_], so this is the natural ASCII subset.
_NAME_RE = re.compile(r'^[A-Za-z0-9_]+$')


def offset_to_multiplier(offset: int) -> float:
    """Convert the slider's integer offset to a MasterVolume factor."""
    return round(1.0 + (int(offset) * _PERCENT_PER_STEP / 100.0), 4)


_MAIN_LUA_TEMPLATE = '''--[[
    Frog Mod: Engine Volume Adjustments
    ===================================
    Applies per-engine MasterVolume multipliers to modded engines.
    The mapping below is generated by Frog Mod Editor from each
    engine's Volume Adjustment slider.

    How it works:
      Every {poll_seconds}s the mod scans every live MHEngineDataAsset.
      For each engine whose name matches a key in MULTIPLIERS, the
      EngineSoundData.MasterVolume field is rewritten to:
          baseline * MULTIPLIERS[name]
      Baselines are captured per-instance on first sighting so repeat
      polls don't compound the effect. Engines not in the table are
      ignored entirely (vanilla volume preserved).

    Generated by Frog Mod Editor. Edit the slider in the Engine Creator
    and re-save the engine to regenerate this mod with new values.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

-- ============================================================
-- Configuration
-- ============================================================
local CONFIG = {{
    PollIntervalMs = {poll_ms},
    InitialDelayMs = 8000,
}}

-- engine_name -> MasterVolume multiplier (1.0 = vanilla)
local MULTIPLIERS = {{
{multiplier_lines}
}}

-- ============================================================
-- Helpers
-- ============================================================
local function Log(msg) print("[FrogModEngineVolume] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- Engine names in Motor Town's pak look like /Game/Cars/Parts/Engine/
-- <Name>.<Name>. GetFullName() returns "ClassName /Game/.../Name.Name"
-- — pull just the trailing object name.
local function ExtractEngineName(fullname)
    if not fullname or fullname == "" then return nil end
    local _, _, tail = string.find(fullname, "%.([^%.]+)$")
    return tail
end

-- ============================================================
-- Application loop
-- ============================================================
local baselines = {{}}   -- [engineFullName] = baseline_master_volume

local function ApplyToAllEngines()
    local engines = FindAllOf("MHEngineDataAsset")
    if not engines then return 0, 0 end

    local count = 0
    pcall(function() count = #engines end)

    local matched = 0
    local applied = 0

    for i = 1, count do
        local engine = engines[i]
        local fullname = ""
        pcall(function() fullname = engine:GetFullName() end)
        local short = ExtractEngineName(fullname)
        if short and MULTIPLIERS[short] then
            matched = matched + 1
            local soundData = SafeGet(engine, "EngineSoundData")
            if soundData then
                local baselineKey = fullname
                if baselines[baselineKey] == nil then
                    local current = SafeGet(soundData, "MasterVolume")
                    -- Vanilla MTEngineSoundDataAsset uses class default
                    -- when MasterVolume isn't serialised. UE4SS still
                    -- exposes the property; if read returns nil, fall
                    -- back to 1.0 (the typical default for volume).
                    if type(current) ~= "number" then current = 1.0 end
                    baselines[baselineKey] = current
                    Log(string.format("baseline %s: MasterVolume=%.3f",
                        short, current))
                end
                local target = baselines[baselineKey] * MULTIPLIERS[short]
                local cur = SafeGet(soundData, "MasterVolume")
                if type(cur) ~= "number" or math.abs(cur - target) > 0.001 then
                    local ok = pcall(function()
                        soundData.MasterVolume = target
                    end)
                    if ok then
                        applied = applied + 1
                    end
                end
            end
        end
    end

    return matched, applied
end

Log("=== Frog Mod Engine Volume Loading ===")
local engineCount = 0
for _ in pairs(MULTIPLIERS) do engineCount = engineCount + 1 end
Log(string.format("Configured for %d engine(s)", engineCount))

-- LoopAsync waits the interval before the first call, so we just use
-- the regular interval as the warm-up. Engines that aren't loaded yet
-- (player still in main menu) just get skipped on early polls; once
-- they're in the world the next tick picks them up.
local lastMatched = -1
LoopAsync(CONFIG.PollIntervalMs, function()
    local matched, applied = ApplyToAllEngines()
    if matched ~= lastMatched then
        Log(string.format("Poll: %d engine(s) matched, %d applied this cycle",
            matched, applied))
        lastMatched = matched
    end
    return false  -- keep looping
end)

Log("=== Frog Mod Engine Volume Loaded ===")
'''


def _format_multiplier_lines(offsets: Dict[str, int]) -> str:
    """Render the engine_name -> multiplier table for the Lua template.

    Skips zero-offset entries (no point burning a poll cycle on
    multipliers that resolve to 1.0×). Sorts keys alphabetically so the
    generated Lua diffs cleanly when the workspace changes.
    """
    lines = []
    for name in sorted(offsets):
        offset = int(offsets[name])
        if offset == 0:
            continue
        if not _NAME_RE.match(name):
            logger.warning(
                "engine_volume: skipping name %r — not Lua-safe", name
            )
            continue
        mult = offset_to_multiplier(offset)
        lines.append(
            f'    ["{name}"] = {mult:.4f},  -- offset {offset:+d} '
            f'({mult:.2f}x)'
        )
    return '\n'.join(lines) if lines else '    -- (no engines configured)'


def _validate(config: Dict[str, Any]) -> Dict[str, int]:
    """Coerce the config dict into ``{engine_name: int_offset}``.

    Accepts either the bare offset map (``{"Foo": 12}``) or an
    ``{"engines": {...}}`` wrapper for forward compatibility. Drops:
      - non-integer offsets (couldn't be coerced),
      - names that don't pass the Lua-identifier safety check,
      - zero offsets (multiplier 1.0 is a no-op — no need to ship them
        to the Lua side and waste a polling slot on them).
    """
    raw = config.get('engines') if isinstance(config, dict) and 'engines' in config else config
    if not isinstance(raw, dict):
        return {}
    out: Dict[str, int] = {}
    for name, val in raw.items():
        if not isinstance(name, str) or not _NAME_RE.match(name):
            continue
        try:
            offset = int(val)
        except (TypeError, ValueError):
            continue
        if offset == 0:
            continue
        offset = max(-25, min(25, offset))
        out[name] = offset
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    offsets = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        poll_ms=3000,
        poll_seconds=3,
        multiplier_lines=_format_multiplier_lines(offsets),
    )


def generate_readme(config: Dict[str, Any]) -> str:
    offsets = _validate(config)
    rows = []
    for name in sorted(offsets):
        off = offsets[name]
        if off == 0:
            continue
        mult = offset_to_multiplier(off)
        rows.append(f"  {name}: offset {off:+d}  ->  MasterVolume x{mult:.2f}")
    table = '\n'.join(rows) if rows else '  (no engines have non-zero volume offsets)'
    body = (
        "Per-engine MasterVolume multipliers applied at runtime:\n\n"
        f"{table}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Every 3 seconds the mod scans every live MHEngineDataAsset.\n"
        "For each engine whose name matches a row in the table above,\n"
        "the EngineSoundData.MasterVolume field is rewritten to\n"
        "(vanilla_value * multiplier). Baselines are captured per\n"
        "instance on first sighting so repeated polls don't compound\n"
        "the effect on the same engine. Engines not in the table are\n"
        "left at their vanilla volume.\n\n"
        "WHY A LUA MOD AND NOT THE PAK?\n"
        "------------------------------\n"
        "Motor Town's UMTEngineSoundDataAsset doesn't serialise tagged\n"
        "volume properties — it relies on class defaults. To override\n"
        "the volume in the pak we'd need to add new tagged properties\n"
        "to a class that has none, which is non-trivial binary surgery.\n"
        "A Lua mod that sets the property at runtime is far simpler\n"
        "and works the same in-game.\n\n"
        "REGENERATION\n"
        "------------\n"
        "Edit the Volume Adjustment slider in the Engine Creator and\n"
        "save the engine — Frog Mod Editor regenerates this mod folder\n"
        "automatically. If every engine ends up with offset 0 the mod\n"
        "folder is removed.\n"
    )
    return render_install_readme(MOD_NAME, body)


def collect_engine_offsets(engine_dir: str) -> Dict[str, int]:
    """Scan ``engine_dir`` for ``*.creation.json`` files and return the
    map ``{engine_name: volume_offset}``. Skips entries with offset 0
    and entries with a missing or non-numeric volume_offset field.
    """
    out: Dict[str, int] = {}
    if not engine_dir or not os.path.isdir(engine_dir):
        return out
    for path in glob.glob(os.path.join(engine_dir, '*.creation.json')):
        engine_name = os.path.basename(path)[:-len('.creation.json')]
        try:
            with open(path, 'r', encoding='utf-8') as fh:
                meta = json.load(fh)
        except (OSError, json.JSONDecodeError):
            continue
        offset = meta.get('volume_offset', 0)
        try:
            offset_int = int(offset)
        except (TypeError, ValueError):
            continue
        if offset_int == 0:
            continue
        if not _NAME_RE.match(engine_name):
            continue
        out[engine_name] = max(-25, min(25, offset_int))
    return out


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    """Write the Lua mod folder for the given offsets, or remove it if
    the offsets dict is empty.

    ``config`` may be either ``{engine_name: offset}`` directly or
    ``{"engines": {...}}``.
    """
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    offsets = _validate(config)
    target_folder = os.path.join(out_dir, MOD_NAME)

    if not offsets:
        # No engines configured — clean up the mod folder so the user's
        # next regenerate doesn't ship a dead-no-op script.
        if os.path.isdir(target_folder):
            try:
                shutil.rmtree(target_folder)
                return {'success': True, 'path': target_folder, 'removed': True}
            except OSError as exc:
                logger.warning("could not remove %s: %s", target_folder, exc)
                return {'success': False, 'error': str(exc)}
        return {'success': True, 'path': target_folder, 'noop': True}

    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua({'engines': offsets}),
        readme=generate_readme({'engines': offsets}),
        mod_info={'engine_count': len(offsets), 'engines': offsets},
    )


def deploy_from_engine_workspace(engine_dir: str,
                                 output_dir: str = None) -> Dict[str, Any]:
    """Convenience: scan the engine workspace's .creation.json files
    and deploy the mod with whatever volume_offsets it finds. Used by
    the engine creation flow as a post-save hook."""
    offsets = collect_engine_offsets(engine_dir)
    return deploy({'engines': offsets}, output_dir=output_dir)


import sys as _sys
register(_sys.modules[__name__])
