"""Cryovac EXP Multiplier — scales job-income-derived XP by modifying
FMTBalanceTable.JobIncomeToJobExpMultiplier on the live UMTGameResource
and UMTBalanceSettings instances at runtime.

Vanilla JobIncomeToJobExpMultiplier = 0.10 — every 10 units of money
earned grants 1 XP. The slider here multiplies THAT coefficient, not
the final XP directly. A 2.0× slider means 0.20 coefficient (20% of
earned money becomes XP, effectively 2× the vanilla rate)."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacExpMultiplier'

UI_TITLE = 'EXP Multiplier'

UI_DESCRIPTION = (
    "Scales job-income XP gain. Vanilla Motor Town converts 10% of any "
    "job income (cargo, taxi, bus, ambulance, tow, etc.) into XP via the "
    "<code>JobIncomeToJobExpMultiplier</code> field on the global balance "
    "table. This mod scales that coefficient at runtime on the live "
    "<code>UMTGameResource</code> and <code>UMTBalanceSettings</code> "
    "instances, so every income-derived XP grant multiplies by your "
    "chosen factor.\n\n"
    "<b>0.5\u00d7</b> \u2014 slower levelling (5% of income to XP).<br>"
    "<b>1.0\u00d7</b> \u2014 vanilla (10% of income to XP).<br>"
    "<b>2.0\u00d7</b> \u2014 2\u00d7 vanilla XP gain.<br>"
    "<b>5.0\u00d7</b> \u2014 level up fast (50% of income to XP).\n\n"
    "Direct-grant XP from races and one-off rewards goes through a "
    "different path and isn't touched by this mod."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'multiplier': 2.0,
}

SETTINGS = [
    Setting(
        key='multiplier',
        label='EXP multiplier',
        kind='slider',
        default=2.0,
        min_value=0.5,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip='Factor applied to JobIncomeToJobExpMultiplier. '
                '0.5 = half vanilla XP, 1.0 = vanilla, 5.0 = 5\u00d7 XP.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: EXP Multiplier
    =======================
    Scales job-income-derived XP gain by modifying
    FMTBalanceTable.JobIncomeToJobExpMultiplier on every live instance
    of UMTGameResource and UMTBalanceSettings at runtime.

    Baselines are captured per-instance on first apply so re-applying
    doesn't compound. Vanilla coefficient is 0.10 — we multiply that
    by {multiplier}, so the modded coefficient is:

        {multiplier} * 0.10 = {modded_value}

    Direct-grant XP from races and one-off rewards goes through a
    different path (ClientGiveReward / FMTRewardEntry.exp) and is
    NOT touched by this mod.

    Generated by Frog Mod Editor. Multiplier is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Multiplier = {multiplier},

    -- Classes whose BalanceTable we'll modify. UMTGameResource is a
    -- UDataAsset loaded from the content tree; UMTBalanceSettings is
    -- a UDeveloperSettings CDO loaded from DefaultMotorTownBalance.ini.
    -- Both hold a nested FMTBalanceTable with the field we want.
    TargetClasses = {{ "MTGameResource", "MTBalanceSettings" }},

    InitialDelayMs = 15000,
}}

local function Log(msg) print("[CryovacExpMultiplier] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function SafeSet(obj, prop, value)
    local ok, err = pcall(function() obj[prop] = value end)
    return ok, err
end

local applied = false
local vanilla_baseline = {{}}   -- keyed by object:GetFullName()

local function ApplyToInstance(obj)
    if not obj then return false end
    local name = ""
    pcall(function() name = obj:GetFullName() end)

    local bt = SafeGet(obj, "BalanceTable")
    if not bt then
        Log(string.format("  %s: no BalanceTable; skipping", name))
        return false
    end

    local baseline = SafeGet(bt, "JobIncomeToJobExpMultiplier")
    if type(baseline) ~= "number" then
        Log(string.format("  %s: JobIncomeToJobExpMultiplier missing; skipping", name))
        return false
    end

    -- Capture the ORIGINAL (unmodified) value, not any value our own
    -- previous run may have written. Keyed by object path.
    if vanilla_baseline[name] == nil then
        vanilla_baseline[name] = baseline
    end

    local newValue = vanilla_baseline[name] * CONFIG.Multiplier
    local ok, err = SafeSet(bt, "JobIncomeToJobExpMultiplier", newValue)
    if not ok then
        Log(string.format("  %s: SET failed: %s", name, tostring(err)))
        return false
    end

    local verify = SafeGet(bt, "JobIncomeToJobExpMultiplier")
    Log(string.format("  %s: JobIncome->Exp %.4f -> %.4f (x%.2f)",
        name, vanilla_baseline[name], verify or 0, CONFIG.Multiplier))
    return true
end

local function ApplyMultiplier()
    if applied then return true end

    if math.abs(CONFIG.Multiplier - 1.0) < 1e-6 then
        Log("Multiplier = 1.0 - no modifications applied.")
        applied = true
        return true
    end

    local success_count = 0
    local attempted = 0

    for _, className in ipairs(CONFIG.TargetClasses) do
        local instances = FindAllOf(className)
        if instances then
            local count = 0
            pcall(function() count = #instances end)
            Log(string.format("Found %d %s instance(s)", count, className))
            for i = 1, count do
                attempted = attempted + 1
                if ApplyToInstance(instances[i]) then
                    success_count = success_count + 1
                end
            end
        end
    end

    if attempted == 0 then
        return false  -- retry; resources may not be loaded yet
    end

    Log(string.format("Applied EXP multiplier x%.2f to %d of %d instances.",
        CONFIG.Multiplier, success_count, attempted))
    applied = true
    return true
end

Log("=== Cryovac EXP Multiplier Loading ===")
Log(string.format("Multiplier: x%.2f (target: JobIncomeToJobExpMultiplier on %s)",
    CONFIG.Multiplier, table.concat(CONFIG.TargetClasses, ", ")))

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyMultiplier() then
        LoopAsync(5000, function() return ApplyMultiplier() end)
    end
end)

Log("=== Cryovac EXP Multiplier Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    val = float(config.get('multiplier', DEFAULT_CONFIG['multiplier']))
    if not 0.1 <= val <= 10.0:
        raise ValueError(f"multiplier {val} out of sanity range [0.1, 10.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        multiplier=f"{val:.3f}",
        modded_value=f"{val * 0.10:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    body = (
        f"EXP multiplier: x{val:.2f}\n"
        f"Effective JobIncomeToJobExpMultiplier: {val * 0.10:.3f} "
        f"(vanilla is 0.10)\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "At session start, finds every live UMTGameResource and\n"
        "UMTBalanceSettings instance and scales their nested\n"
        "FMTBalanceTable.JobIncomeToJobExpMultiplier field by the\n"
        "configured multiplier.\n\n"
        "Every job-income XP grant (cargo, taxi, bus, ambulance, tow,\n"
        "vehicle delivery, rescue) runs through this coefficient. Direct-\n"
        "grant XP from races and one-off reward popups uses a different\n"
        "code path and isn't affected by this mod.\n\n"
        "Baseline is captured per instance on first apply, so hot-reload\n"
        "or mod re-run won't compound the multiplier.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'multiplier': val, 'effective_coefficient': val * 0.10},
    )


import sys as _sys
register(_sys.modules[__name__])
