"""Cryovac EXP Multiplier — scales job-income-derived XP by modifying
FMTBalanceTable.JobIncomeToJobExpMultiplier on the live UMTGameResource
and UMTBalanceSettings instances at runtime.

Vanilla JobIncomeToJobExpMultiplier = 0.10 — every 10 units of money
earned grants 1 XP. The slider here multiplies THAT coefficient, not
the final XP directly. A 2.0× slider means 0.20 coefficient (20% of
earned money becomes XP, effectively 2× the vanilla rate)."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacExpMultiplier'

UI_TITLE = 'EXP Multiplier'

UI_DESCRIPTION = (
    "Scales XP gain across every character level: Driver, Taxi, Bus, "
    "Truck, Racer, Wrecker (Tow), and Police.\n\n"
    "Two code paths are covered so no level type is left behind:\n"
    "<br>\u2022 <b>Job types</b> (Taxi, Bus, Truck, Wrecker, Police) "
    "gain XP as a percentage of job income. This mod rewrites the "
    "<code>JobIncomeToJobExpMultiplier</code> field on "
    "<code>UMTGameResource</code> and <code>UMTBalanceSettings</code> "
    "to be <code>0.10 \u00d7 multiplier</code> (vanilla is 0.10).\n"
    "<br>\u2022 <b>Driver and Racer</b> XP don\u2019t go through the "
    "income path \u2014 they\u2019re granted directly by native code. "
    "This mod pre-hooks <code>ClientAddExp</code> and mutates the "
    "<code>exp</code> parameter in place for those two level types "
    "only (job types are skipped here so they aren\u2019t "
    "double-applied).\n\n"
    "<b>0.5\u00d7</b> \u2014 slower levelling across the board.<br>"
    "<b>1.0\u00d7</b> \u2014 vanilla (hook not installed, BalanceTable untouched).<br>"
    "<b>2.0\u00d7</b> \u2014 2\u00d7 XP on every level type.<br>"
    "<b>5.0\u00d7</b> \u2014 level up fast."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'multiplier': 2.0,
}

SETTINGS = [
    Setting(
        key='multiplier',
        label='EXP multiplier',
        kind='slider',
        default=2.0,
        min_value=0.5,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip='Factor applied to JobIncomeToJobExpMultiplier. '
                '0.5 = half vanilla XP, 1.0 = vanilla, 5.0 = 5\u00d7 XP.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: EXP Multiplier
    =======================
    Scales job-income-derived XP gain by modifying
    FMTBalanceTable.JobIncomeToJobExpMultiplier on every live instance
    of UMTGameResource and UMTBalanceSettings at runtime.

    Baselines are captured per-instance on first apply so re-applying
    doesn't compound. Vanilla coefficient is 0.10 — we multiply that
    by {multiplier}, so the modded coefficient is:

        {multiplier} * 0.10 = {modded_value}

    Direct-grant XP from races and one-off rewards goes through a
    different path (ClientGiveReward / FMTRewardEntry.exp) and is
    NOT touched by this mod.

    Generated by Frog Mod Editor. Multiplier is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    Multiplier = {multiplier},

    -- Hardcoded vanilla value so the final field is always
    --     VanillaBaseline * Multiplier
    -- regardless of what DefaultMotorTownBalance.ini (or any other mod)
    -- may have already set it to. If we trusted the live read, an INI
    -- that already shifted this value (e.g. Economy tab set to 2x
    -- writing 0.20) would compound with our multiplier and produce
    -- MultiplierSquared results. Hardcoding the vanilla 0.10 makes
    -- this mod the authoritative source of truth.
    VanillaBaseline = 0.10,

    -- Classes whose BalanceTable we'll modify. UMTGameResource is a
    -- UDataAsset loaded from the content tree; UMTBalanceSettings is
    -- a UDeveloperSettings CDO loaded from DefaultMotorTownBalance.ini.
    -- Both hold a nested FMTBalanceTable with the field we want.
    TargetClasses = {{ "MTGameResource", "MTBalanceSettings" }},

    InitialDelayMs = 15000,
}}

local function Log(msg) print("[CryovacExpMultiplier] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function SafeSet(obj, prop, value)
    local ok, err = pcall(function() obj[prop] = value end)
    return ok, err
end

local applied = false

local function ApplyToInstance(obj)
    if not obj then return false end
    local name = ""
    pcall(function() name = obj:GetFullName() end)

    local bt = SafeGet(obj, "BalanceTable")
    if not bt then
        Log(string.format("  %s: no BalanceTable; skipping", name))
        return false
    end

    local observed = SafeGet(bt, "JobIncomeToJobExpMultiplier")
    if type(observed) ~= "number" then
        Log(string.format("  %s: JobIncomeToJobExpMultiplier missing; skipping", name))
        return false
    end

    -- Always compute from the hardcoded vanilla, NEVER from what we
    -- read. Reading is only used to detect if something else (e.g. the
    -- INI pak's Economy tab) already shifted the field; if so, warn.
    local target = CONFIG.VanillaBaseline * CONFIG.Multiplier
    local drift = math.abs(observed - CONFIG.VanillaBaseline)
    if drift > 1e-4 and math.abs(observed - target) > 1e-4 then
        Log(string.format(
            "  %s: observed %.4f != vanilla %.4f. INI or another mod set it; "
         .. "overwriting with %.4f (x%.2f of vanilla) -- Lua is authoritative.",
            name, observed, CONFIG.VanillaBaseline, target, CONFIG.Multiplier))
    end

    local ok, err = SafeSet(bt, "JobIncomeToJobExpMultiplier", target)
    if not ok then
        Log(string.format("  %s: SET failed: %s", name, tostring(err)))
        return false
    end

    local verify = SafeGet(bt, "JobIncomeToJobExpMultiplier")
    Log(string.format("  %s: JobIncome->Exp %.4f -> %.4f (x%.2f of vanilla %.4f)",
        name, observed, verify or 0, CONFIG.Multiplier, CONFIG.VanillaBaseline))
    return true
end

local function ApplyMultiplier()
    if applied then return true end

    if math.abs(CONFIG.Multiplier - 1.0) < 1e-6 then
        Log("Multiplier = 1.0 - no modifications applied.")
        applied = true
        return true
    end

    local success_count = 0
    local attempted = 0

    for _, className in ipairs(CONFIG.TargetClasses) do
        local instances = FindAllOf(className)
        if instances then
            local count = 0
            pcall(function() count = #instances end)
            Log(string.format("Found %d %s instance(s)", count, className))
            for i = 1, count do
                attempted = attempted + 1
                if ApplyToInstance(instances[i]) then
                    success_count = success_count + 1
                end
            end
        end
    end

    if attempted == 0 then
        return false  -- retry; resources may not be loaded yet
    end

    Log(string.format("Applied EXP multiplier x%.2f to %d of %d instances.",
        CONFIG.Multiplier, success_count, attempted))
    applied = true
    return true
end

-- ============================================================
-- ClientAddExp pre-hook for XP types NOT covered by
-- JobIncomeToJobExpMultiplier.
--
-- The BalanceTable multiplier only scales job-income -> job-XP
-- (CL_Taxi, CL_Bus, CL_Truck, CL_Wrecker, CL_Police). It does
-- NOT scale CL_Driver (earned from driving activity) or
-- CL_Racer (earned from races). To cover those, we hook
-- ClientAddExp and mutate the `exp` parameter in place for
-- those level types only. Job types are intentionally skipped
-- here so we don't double-apply on top of the BalanceTable path.
--
-- EMTCharacterLevelType values (from EMTCharacterLevelType.h):
--   0 = CL_Driver   (hooked here)
--   1 = CL_Taxi     (covered by BalanceTable)
--   2 = CL_Bus      (covered by BalanceTable)
--   3 = CL_Truck    (covered by BalanceTable)
--   4 = CL_Racer    (hooked here)
--   5 = CL_Wrecker  (covered by BalanceTable - "Tow" in UI)
--   6 = CL_Police   (covered by BalanceTable)
-- ============================================================
local NON_JOB_LEVEL_TYPES = {{
    [0] = "CL_Driver",
    [4] = "CL_Racer",
}}

local function Unwrap(obj)
    if obj == nil then return nil end
    local ok, val = pcall(function() return obj:get() end)
    if ok and val ~= nil then return val end
    return obj
end

local function SetupNonJobExpHook()
    if math.abs(CONFIG.Multiplier - 1.0) < 1e-6 then
        Log("Multiplier = 1.0 -- ClientAddExp hook not installed (mod is no-op).")
        return
    end
    local ok, err = pcall(function()
        RegisterHook(
            "/Script/MotorTown.MotorTownPlayerController:ClientAddExp",
            function(self, ctxWrap, levelTypeWrap, expWrap, msgWrap)
                local levelType = Unwrap(levelTypeWrap)
                -- TEnumAsByte unwraps to a number in UE4SS Lua
                if type(levelType) ~= "number" then return end
                local typeName = NON_JOB_LEVEL_TYPES[levelType]
                if not typeName then return end  -- job type, skip

                local exp = Unwrap(expWrap) or 0
                if type(exp) ~= "number" or exp <= 0 then return end

                local boosted = math.floor(exp * CONFIG.Multiplier)
                if boosted <= exp then return end  -- no-op guard

                local setOk, setErr = pcall(function() expWrap:set(boosted) end)
                if setOk then
                    Log(string.format("%s exp: %d -> %d (x%.2f)",
                        typeName, exp, boosted, CONFIG.Multiplier))
                else
                    Log(string.format("%s exp set() failed: %s (unchanged)",
                        typeName, tostring(setErr)))
                end
            end)
    end)
    if ok then
        Log("Hook registered: MotorTownPlayerController:ClientAddExp "
         .. "(scales CL_Driver + CL_Racer only)")
    else
        Log("ClientAddExp hook failed: " .. tostring(err))
    end
end

Log("=== Cryovac EXP Multiplier Loading ===")
Log(string.format("Multiplier: x%.2f (BalanceTable: JobIncomeToJobExpMultiplier on %s)",
    CONFIG.Multiplier, table.concat(CONFIG.TargetClasses, ", ")))
Log("              (ClientAddExp hook: CL_Driver + CL_Racer)")

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    if not ApplyMultiplier() then
        LoopAsync(5000, function() return ApplyMultiplier() end)
    end
    SetupNonJobExpHook()
end)

Log("=== Cryovac EXP Multiplier Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    val = float(config.get('multiplier', DEFAULT_CONFIG['multiplier']))
    if not 0.1 <= val <= 10.0:
        raise ValueError(f"multiplier {val} out of sanity range [0.1, 10.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        multiplier=f"{val:.3f}",
        modded_value=f"{val * 0.10:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    body = (
        f"EXP multiplier: x{val:.2f}\n"
        f"Effective JobIncomeToJobExpMultiplier: {val * 0.10:.3f} "
        f"(vanilla is 0.10)\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Covers ALL character level types (Driver, Taxi, Bus, Truck,\n"
        "Racer, Wrecker/Tow, Police) using two complementary paths:\n\n"
        "1. BalanceTable path (job income -> job XP)\n"
        "   At session start, finds every live UMTGameResource and\n"
        "   UMTBalanceSettings instance and rewrites their nested\n"
        "   FMTBalanceTable.JobIncomeToJobExpMultiplier to\n"
        "   (0.10 * multiplier). Every job-income-derived XP grant\n"
        "   (Taxi, Bus, Truck, Wrecker, Police) runs through this.\n\n"
        "2. ClientAddExp hook (direct-grant XP)\n"
        "   Pre-hooks MotorTownPlayerController:ClientAddExp and\n"
        "   mutates the `exp` parameter in place for CL_Driver (0)\n"
        "   and CL_Racer (4) only - the two level types that don't\n"
        "   go through the job-income path. Job types are skipped at\n"
        "   this hook so they aren't double-applied.\n\n"
        "The BalanceTable path uses a hardcoded vanilla baseline (0.10)\n"
        "so any INI mod that also shifted JobIncomeToJobExpMultiplier\n"
        "cannot compound with this multiplier - Lua is authoritative.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'multiplier': val, 'effective_coefficient': val * 0.10},
    )


import sys as _sys
register(_sys.modules[__name__])
