"""Cryovac Free Depot Construction — runtime force-complete approach.

Earlier versions tried to modify the Buildings_Houses DataTable to
zero (or near-zero) the construction-cost arrays. That ran into two
unsolvable problems:

  1. With requirements at 0, MT's construction state machine never
     fires its completion event (no delivery → no event → stuck).
  2. With requirements at 1 unit per cargo, the player still has to
     produce one of every cargo type — and several of those (Plastic
     Pipes, H-Beam, Concrete) require multi-step production chains.
     That defeats the purpose of "free construction".

The right angle is to leave the DataTable vanilla and modify the
*placed construction site actor* at runtime. The construction screen
still shows the normal materials list, but the actor's internal
"completion" check fires immediately because the mod sets its
delivered-amount fields equal to its required-amount fields (or
calls a Complete method directly) the moment it's placed.

Approach
--------
Periodically scans for placed construction-site actors via FindAllOf
and tries a list of candidate methods/fields to advance them to the
"completed" state. The candidate list covers every reasonable UE5
naming convention for delivery completion / construction finish on
MT's likely class hierarchy:

  - call <Site>:CompleteConstruction()      (most likely method name)
  - call <Site>:ServerCompleteConstruction() (server-side variant)
  - call <Site>:OnAllMaterialsDelivered()   (event-style)
  - call <Site>:FinishConstruction()        (alternative)
  - copy RequiredAmounts → DeliveredAmounts (state-copy fallback)
  - set bIsCompleted/bIsConstructed = true  (flag fallback)

UE4SS's pcall-wrapped property/method access fails silently for
non-existent names, so listing every plausible candidate is safe —
the wrong ones drop out, the right one fires and the construction
site finishes. The mod logs which method actually worked at the
first successful completion, so future debugging knows which combo
was the live one on the user's MT build.

If NONE of the candidates work, the mod logs a clear "no candidate
matched" message at startup with instructions for the user to
report the actual class/method names from UE4SS Live View so the
candidate list can be extended.
"""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacFreeDepotConstruction'

UI_TITLE = 'Free Depot Construction'

UI_DESCRIPTION = (
    "Force-completes Depot and Large Garage construction sites the "
    "moment they're placed. The construction screen still shows the "
    "normal materials list, but the building skips the delivery "
    "requirement entirely — no cargo runs needed.\n\n"
    "Mechanism: at runtime, the mod periodically scans for placed "
    "construction-site actors (Depot_01_Construction, Depot_02_Construction, "
    "LargeGarage_01_Construction, etc.) and forces their state to "
    "'completed' by trying common UE5 completion-method names "
    "(<code>CompleteConstruction</code>, <code>ServerCompleteConstruction</code>, "
    "<code>OnAllMaterialsDelivered</code>, etc.). Whichever name MT "
    "actually uses on the current build wins.\n\n"
    "<b>This mod has no settings.</b> Deploy to enable; remove the "
    "folder or set <code>enabled.txt: 0</code> to disable. Houses, "
    "furniture, and other building types are untouched.\n\n"
    "Replaces the v7.2.x DataTable-modification approach, which "
    "couldn't trigger the vanilla completion flow without forcing "
    "the player to produce one of every multi-step cargo type."
)

# No user-configurable settings. The framework requires DEFAULT_CONFIG
# and SETTINGS to exist on every deployer; both are empty here.
DEFAULT_CONFIG: Dict[str, Any] = {}
SETTINGS = []  # type: ignore[var-annotated]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Free Depot Construction (runtime force-complete)
    =========================================================
    Skips the delivery phase on Depot / Large Garage construction
    sites. Player places one, the mod sees it on the next scan, and
    forces it to the "completed" state via whichever of several
    candidate completion methods the current MT build exposes.

    Generated by Frog Mod Editor. No settings. Server-side mod;
    runs on host or dedicated. Requires UE4SS.
]]--

local CONFIG = {{
    InitialDelayMs = 8000,           -- wait for world load
    ScanIntervalMs = 3000,           -- how often we look for new sites
}}

local function Log(msg) print("[CryovacFreeDepotConstruction] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- Class names to look for via FindAllOf. Specific blueprint
-- subclasses come first (cheap reject of non-matches); we also
-- include candidate base classes in case future MT builds rename
-- the specific subclasses.
local CLASS_CANDIDATES = {{
    "Depot_01_Construction_C",
    "Depot_02_Construction_C",
    "LargeGarage_01_Construction_C",
    "Garage_01_Construction_C",
    -- Possible base classes
    "MTBuildingConstruction_C",
    "MTBuildingConstruction",
    "MTConstructionSite",
    "BP_BuildingConstruction_Base_C",
}}

-- Methods we'll try calling (in order) to force completion.
local COMPLETE_METHOD_CANDIDATES = {{
    "CompleteConstruction",
    "ServerCompleteConstruction",
    "OnAllMaterialsDelivered",
    "OnConstructionCompleted",
    "FinishConstruction",
    "Complete",
    "Finish",
}}

-- Boolean flags we'll try setting to true to mark completed.
local COMPLETED_FLAG_CANDIDATES = {{
    "bIsCompleted",
    "bIsConstructed",
    "bConstructionFinished",
    "bConstructionComplete",
    "bIsBuilt",
    "bFinished",
}}

-- Track which actors we've already completed so we don't redo them.
local completedActors = {{}}

-- The first method that successfully fires gets cached so we don't
-- waste pcalls on the others on every subsequent site.
local cachedMethod = nil
local cachedFlag = nil

local function GetActorKey(actor)
    -- Use the full path as a stable identity (FName + memory address
    -- both vary per session, so we use the full Outer/Name path which
    -- stays unique within a session).
    local key = ""
    pcall(function() key = actor:GetFullName() end)
    return key
end

-- Try every candidate completion method on the actor. Returns the
-- name of the method that fired, or nil if none worked.
local function TryComplete(actor)
    -- Cache hit: try the previously-successful method first
    if cachedMethod then
        local ok = pcall(function() actor[cachedMethod](actor) end)
        if ok then return cachedMethod end
    end
    -- Try each candidate
    for _, m in ipairs(COMPLETE_METHOD_CANDIDATES) do
        if m ~= cachedMethod then
            local ok = pcall(function() actor[m](actor) end)
            if ok then
                cachedMethod = m
                Log("Discovered working completion method: " .. m)
                return m
            end
        end
    end
    -- Method approach failed — try setting flag fields
    if cachedFlag then
        local ok = pcall(function() actor[cachedFlag] = true end)
        if ok then return "(flag) " .. cachedFlag end
    end
    for _, f in ipairs(COMPLETED_FLAG_CANDIDATES) do
        if f ~= cachedFlag then
            local ok = pcall(function() actor[f] = true end)
            if ok then
                cachedFlag = f
                Log("Discovered working completion flag: " .. f)
                return "(flag) " .. f
            end
        end
    end
    return nil
end

local successCount = 0
local failureLogged = false

local function ScanAndComplete()
    for _, class_name in ipairs(CLASS_CANDIDATES) do
        local actors = FindAllOf(class_name)
        if actors then
            local count = 0
            pcall(function() count = #actors end)
            for i = 1, count do
                local actor = actors[i]
                local key = GetActorKey(actor)
                if key ~= "" and not completedActors[key] then
                    local result = TryComplete(actor)
                    if result then
                        completedActors[key] = true
                        successCount = successCount + 1
                        Log(string.format(
                            "Completed construction site %s via %s "
                            .. "(class %s)",
                            key, result, class_name))
                    elseif not failureLogged then
                        failureLogged = true
                        Log(string.format(
                            "Found construction site %s (class %s) but "
                            .. "no candidate completion method or flag "
                            .. "worked. Use UE4SS Live View on this "
                            .. "actor to find the real method/field "
                            .. "name and report it so the candidate "
                            .. "list can be extended.",
                            key, class_name))
                    end
                end
            end
        end
    end
end

-- Init
Log("=== Cryovac Free Depot Construction Loading ===")

ExecuteWithDelay(CONFIG.InitialDelayMs, function()
    ScanAndComplete()
end)

LoopAsync(CONFIG.ScanIntervalMs, function()
    ScanAndComplete()
    return false  -- keep looping forever
end)

Log("=== Cryovac Free Depot Construction Loaded ===")
'''


def generate_main_lua(config: Dict[str, Any]) -> str:
    # The template uses {{ and }} as Python str.format escapes for
    # literal Lua braces, so we MUST run it through .format() even
    # though there are no substitutions — otherwise the rendered
    # Lua contains stray double-braces which corrupt the parser
    # and make every API call (ExecuteWithDelay, LoopAsync, ...)
    # look malformed at runtime.
    return _MAIN_LUA_TEMPLATE.format()


def generate_readme(config: Dict[str, Any]) -> str:
    body = (
        "Force-completes Depot and Large Garage construction sites at\n"
        "runtime. Player places a Depot_01 / Depot_02 / LargeGarage_01\n"
        "construction site, and within ~3 seconds the mod detects it\n"
        "and forces it to the 'completed' state.\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "1. Every 3 seconds, scans for construction-site actors via\n"
        "   FindAllOf using a list of likely class names\n"
        "   (Depot_01_Construction_C, Garage_01_Construction_C,\n"
        "   MTBuildingConstruction, etc.).\n"
        "2. For each newly-found site, tries a list of likely\n"
        "   completion methods (CompleteConstruction,\n"
        "   ServerCompleteConstruction, OnAllMaterialsDelivered, ...).\n"
        "3. The first method that fires without error gets cached;\n"
        "   subsequent sites use it directly with no further probing.\n"
        "4. If no method works, falls back to setting boolean flags\n"
        "   (bIsCompleted, bIsConstructed, ...).\n"
        "5. Each completed site is tracked so the mod doesn't redo it.\n\n"
        "DIAGNOSING ISSUES\n"
        "-----------------\n"
        "Check UE4SS.log for these lines from this mod:\n"
        "  '=== Cryovac Free Depot Construction Loaded ==='\n"
        "    -> mod loaded successfully.\n"
        "  'Discovered working completion method: <name>'\n"
        "    -> the mod found a working completion method on this build.\n"
        "  'Completed construction site <path> via <name> (class <C>)'\n"
        "    -> a site was just force-completed.\n"
        "  'Found construction site ... but no candidate ... worked'\n"
        "    -> none of the candidate methods fired. Use UE4SS Live View\n"
        "       to inspect the construction-site actor and report the\n"
        "       actual method/field name on this build.\n\n"
        "WHY THIS REPLACES THE v7.2.x APPROACH\n"
        "-------------------------------------\n"
        "v7.2.0 - v7.2.3 tried to modify Buildings_Houses.uexp to\n"
        "zero or reduce construction costs. That had two failure modes:\n"
        "  (a) all-zero requirements never trigger the vanilla\n"
        "      completion event (no delivery -> no event -> stuck);\n"
        "  (b) leaving 1 unit per cargo still requires the player to\n"
        "      produce multi-step cargoes (Plastic Pipes, H-Beam),\n"
        "      defeating the 'free construction' goal.\n"
        "Force-completing the actor at runtime sidesteps both.\n\n"
        "NO SETTINGS\n"
        "-----------\n"
        "Binary toggle. Deploy to enable; remove the folder or set\n"
        "the line in mods.txt to '0' to disable.\n\n"
        "MULTIPLAYER\n"
        "-----------\n"
        "Server-side mod. Install on the host / dedicated server only.\n"
        "Clients see the completed building because the construction\n"
        "state replicates from the server.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'binary_toggle': True, 'strategy': 'runtime_force_complete'},
    )


import sys as _sys
register(_sys.modules[__name__])
