"""Cryovac Population Boost — multiplies NPC spawn counts, taxi/
ambulance passenger pools, and bus-stop spawn rate across Motor Town.

Four independent float multipliers: Residents (plus pedestrians and
hitchhikers), Taxi, Ambulance, and Bus spawn speed. Polls every 5s
so the boost re-asserts if the game re-loads spawn config mid-session."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacPopulationBoost'

UI_TITLE = 'Population Boost'

UI_DESCRIPTION = (
    "Increases NPC density in Motor Town. Resident multiplier covers "
    "pedestrians, hitchhikers, and search-and-rescue passengers. Taxi "
    "and Ambulance multipliers scale their specific passenger pools. "
    "Bus Spawn Speed shortens the passenger spawn period at bus stops "
    "(3\u00d7 = bus passengers appear roughly 3\u00d7 faster).\n\n"
    "Each multiplier accepts 0.5\u20135.0. 1.0 = vanilla."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'resident_multiplier':          2.0,
    'taxi_multiplier':              2.0,
    'ambulance_multiplier':         2.0,
    'bus_spawn_speed_multiplier':   3.0,
}


def _float_setting(key: str, label: str, default: float, tooltip: str) -> Setting:
    return Setting(
        key=key,
        label=label,
        kind='slider',
        default=default,
        min_value=0.5,
        max_value=5.0,
        step=0.1,
        suffix='\u00d7',
        tooltip=tooltip,
    )


SETTINGS = [
    _float_setting(
        'resident_multiplier', 'Residents',
        2.0, 'NumResidents, NumPedestrian, NumHitchhikers — population density.'
    ),
    _float_setting(
        'taxi_multiplier', 'Taxi pool',
        2.0, 'NumTaxiPassengers — how many taxi fares are waiting on the street.'
    ),
    _float_setting(
        'ambulance_multiplier', 'Ambulance pool',
        2.0, 'NumAmbulancePassengers — ambulance call frequency.'
    ),
    _float_setting(
        'bus_spawn_speed_multiplier', 'Bus spawn speed',
        3.0, 'Bus-stop passenger spawn rate — 3\u00d7 means they appear ~3\u00d7 faster.'
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Population Boost
    =========================
    Increases NPC spawn counts and bus stop passenger frequency.

    The actual spawn count is controlled by the Entries array on
    MTAICharacterSpawnConfig — each entry has NumActors and
    NumMaxActors. We boost both to get more NPCs in the world.

    Generated by Frog Mod Editor. Multipliers are hardcoded below —
    regenerate the mod from Frog to change them.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    ResidentMultiplier       = {resident_multiplier},
    TaxiMultiplier           = {taxi_multiplier},
    AmbulanceMultiplier      = {ambulance_multiplier},
    BusSpawnSpeedMultiplier  = {bus_spawn_speed_multiplier},
    PollIntervalMs           = 5000,
}}

local function Log(msg)
    print("[CryovacPopBoost] " .. msg)
end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local originalSpawnConfig = {{}}
local originalEntries = {{}}
local originalBusStopPeriods = {{}}

local function ApplySpawnConfig()
    local configs = FindAllOf("MTAICharacterSpawnConfig")
    if not configs then return end

    for _, config in ipairs(configs) do
        local fieldMultipliers = {{
            NumResidents                = CONFIG.ResidentMultiplier,
            NumPedestrian               = CONFIG.ResidentMultiplier,
            NumHitchhikers              = CONFIG.ResidentMultiplier,
            NumTaxiPassengers           = CONFIG.TaxiMultiplier,
            NumAmbulancePassengers      = CONFIG.AmbulanceMultiplier,
            NumSearchAndRescuePassengers = CONFIG.ResidentMultiplier,
        }}

        for field, mult in pairs(fieldMultipliers) do
            local val = SafeGet(config, field)
            if val and val > 0 then
                if not originalSpawnConfig[field] then
                    originalSpawnConfig[field] = val
                    Log("SpawnConfig original " .. field .. ": " .. val)
                end
                local target = math.floor(originalSpawnConfig[field] * mult)
                if val ~= target then
                    config[field] = target
                    Log("SpawnConfig " .. field .. " -> " .. target .. " (" .. mult .. "x)")
                end
            end
        end

        local busMult = SafeGet(config, "BusStopExtraMultiplier")
        if busMult then
            if not originalSpawnConfig.BusStopExtraMultiplier then
                originalSpawnConfig.BusStopExtraMultiplier = busMult
                Log("SpawnConfig original BusStopExtraMultiplier: " .. string.format("%.2f", busMult))
            end
            local target = originalSpawnConfig.BusStopExtraMultiplier * CONFIG.BusSpawnSpeedMultiplier
            if math.abs(busMult - target) > 0.01 then
                config.BusStopExtraMultiplier = target
                Log("SpawnConfig BusStopExtraMultiplier -> " .. string.format("%.2f", target))
            end
        end

        local entries = SafeGet(config, "Entries")
        if entries then
            for i = 1, #entries do
                local entry = entries[i]
                local name = SafeGet(entry, "ActorName") or ("Entry" .. i)
                local nameStr = tostring(name)
                local disabled = SafeGet(entry, "bDisabled")

                if disabled then goto nextEntry end

                local numActors = SafeGet(entry, "NumActors")
                if numActors and numActors > 0 then
                    if not originalEntries[nameStr] then
                        originalEntries[nameStr] = {{}}
                    end
                    if not originalEntries[nameStr].NumActors then
                        originalEntries[nameStr].NumActors = numActors
                        Log("Entry '" .. nameStr .. "' original NumActors: " .. numActors)
                    end
                    local target = math.floor(originalEntries[nameStr].NumActors * CONFIG.ResidentMultiplier)
                    if numActors ~= target then
                        entry.NumActors = target
                        Log("Entry '" .. nameStr .. "' NumActors -> " .. target)
                    end
                end

                local numMax = SafeGet(entry, "NumMaxActors")
                if numMax and numMax > 0 then
                    if not originalEntries[nameStr] then
                        originalEntries[nameStr] = {{}}
                    end
                    if not originalEntries[nameStr].NumMaxActors then
                        originalEntries[nameStr].NumMaxActors = numMax
                        Log("Entry '" .. nameStr .. "' original NumMaxActors: " .. numMax)
                    end
                    local target = math.floor(originalEntries[nameStr].NumMaxActors * CONFIG.ResidentMultiplier)
                    if numMax ~= target then
                        entry.NumMaxActors = target
                        Log("Entry '" .. nameStr .. "' NumMaxActors -> " .. target)
                    end
                end

                ::nextEntry::
            end
        end
    end
end

local function ApplyBusStopSpawns()
    local busStops = FindAllOf("MTBusStop")
    if not busStops then return end

    for _, stop in ipairs(busStops) do
        local key = tostring(stop:GetAddress())
        local period = SafeGet(stop, "PassengerSpawnPeriodMinMax")
        if not period then goto nextStop end

        local x = SafeGet(period, "X")
        local y = SafeGet(period, "Y")
        if not x or not y or x <= 0 or y <= 0 then goto nextStop end

        if not originalBusStopPeriods[key] then
            originalBusStopPeriods[key] = {{ x = x, y = y }}
            local newX = x / CONFIG.BusSpawnSpeedMultiplier
            local newY = y / CONFIG.BusSpawnSpeedMultiplier
            period.X = newX
            period.Y = newY
            Log("BusStop " .. key .. " SpawnPeriod: ("
                .. string.format("%.1f", x) .. ", " .. string.format("%.1f", y)
                .. ") -> (" .. string.format("%.1f", newX) .. ", " .. string.format("%.1f", newY) .. ")")
        else
            local orig = originalBusStopPeriods[key]
            local newX = orig.x / CONFIG.BusSpawnSpeedMultiplier
            local newY = orig.y / CONFIG.BusSpawnSpeedMultiplier
            if math.abs(x - newX) > 0.1 or math.abs(y - newY) > 0.1 then
                period.X = newX
                period.Y = newY
            end
        end

        ::nextStop::
    end
end

Log("=== Cryovac Population Boost Loading ===")
Log("Resident/pedestrian multiplier: " .. CONFIG.ResidentMultiplier .. "x")
Log("Taxi multiplier: " .. CONFIG.TaxiMultiplier .. "x")
Log("Ambulance multiplier: " .. CONFIG.AmbulanceMultiplier .. "x")
Log("Bus spawn speed: " .. CONFIG.BusSpawnSpeedMultiplier .. "x")

LoopAsync(CONFIG.PollIntervalMs, function()
    ApplySpawnConfig()
    ApplyBusStopSpawns()
    return false
end)

Log("=== Cryovac Population Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, float]:
    out = {}
    for s in SETTINGS:
        v = float(config.get(s.key, s.default))
        if v < 0.1 or v > 10.0:
            raise ValueError(f"{s.key} = {v} out of sanity range [0.1, 10.0]")
        out[s.key] = v
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        resident_multiplier=f"{cfg['resident_multiplier']:.3f}",
        taxi_multiplier=f"{cfg['taxi_multiplier']:.3f}",
        ambulance_multiplier=f"{cfg['ambulance_multiplier']:.3f}",
        bus_spawn_speed_multiplier=f"{cfg['bus_spawn_speed_multiplier']:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    body = (
        "Multipliers:\n"
        f"  Residents (and pedestrians, hitchhikers): {cfg['resident_multiplier']:.2f}x\n"
        f"  Taxi passenger pool:                      {cfg['taxi_multiplier']:.2f}x\n"
        f"  Ambulance passenger pool:                 {cfg['ambulance_multiplier']:.2f}x\n"
        f"  Bus stop spawn speed:                     {cfg['bus_spawn_speed_multiplier']:.2f}x\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Polls every 5 seconds and re-asserts the configured multipliers\n"
        "on every MTAICharacterSpawnConfig (Entries[*].NumActors and\n"
        "NumMaxActors) and on every MTBusStop's PassengerSpawnPeriodMinMax.\n"
        "Baselines are captured on first apply so poll cycles don't\n"
        "compound multipliers.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
