"""Cryovac Production + Storage Boost — scales production speed and
warehouse storage capacity on every live AMTDeliveryPoint.

Two independent multipliers:
  - Production speed: walks ProductionConfigs[] and scales each
    config's ProductionSpeedMultiplier. Affects how fast production
    buildings turn input cargo into output.
  - Warehouse storage: scales the delivery point's MaxStorage AND
    each entry in StorageConfigs[].MaxStorage so capacity boosts
    apply to both the per-cargo quotas and the overall cap.

Polls every 5 seconds so newly-loaded delivery points pick up the
boost. Baselines are captured per (delivery_point_full_name, index)
so repeated polls don't compound the effect on the same instance.

Caveat — server-side only:
The MaxStorage fields are not network-replicated as deltas, so for
multiplayer the host has to run this mod for clients to see the
boost. Single-player works either way.
"""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacProductionStorageBoost'

UI_TITLE = 'Production + Storage Boost'

UI_DESCRIPTION = (
    "Two independent sliders that scale every delivery point in the "
    "world:\n\n"
    "<br>• <b>Production Speed</b> — multiplies "
    "<code>ProductionSpeedMultiplier</code> on every recipe in "
    "<code>AMTDeliveryPoint.ProductionConfigs[]</code>. A 2× setting "
    "halves the time it takes for a production building to convert "
    "input cargo into output.\n"
    "<br>• <b>Warehouse Storage</b> — multiplies the delivery "
    "point's <code>MaxStorage</code> and each entry in "
    "<code>StorageConfigs[].MaxStorage</code>. Affects how much cargo "
    "a depot or production warehouse can hold.\n\n"
    "Polls every 5 seconds so freshly-loaded delivery points get the "
    "boost too. Baselines are captured per-instance on first apply, "
    "so repeated polls don't compound the multiplier."
)


def _slider(key: str, label: str, tooltip: str) -> Setting:
    return Setting(
        key=key,
        label=label,
        kind='float',
        default=1.0,
        min_value=0.25,
        max_value=10.0,
        step=0.25,
        suffix='×',
        tooltip=tooltip,
    )


SETTINGS = [
    _slider('production_speed_multiplier', 'Production Speed',
            'Scales ProductionSpeedMultiplier on every production recipe '
            'across every delivery point. 2x halves production time.'),
    _slider('warehouse_storage_multiplier', 'Warehouse Storage',
            'Scales the delivery point\'s MaxStorage and each '
            'StorageConfigs[].MaxStorage. 2x doubles how much a '
            'warehouse / depot can hold.'),
]

DEFAULT_CONFIG: Dict[str, Any] = {
    'production_speed_multiplier': 1.0,
    'warehouse_storage_multiplier': 1.0,
}


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Production + Storage Boost
    ===================================
    Scales two things on every live AMTDeliveryPoint:

      1. Production speed
         For each entry in ProductionConfigs[], multiply
         ProductionSpeedMultiplier by ProductionMult. Faster
         production = shorter time to convert input cargo into
         output. 2x ~ half the production time.

      2. Warehouse storage capacity
         Multiply the delivery point's MaxStorage AND each
         StorageConfigs[].MaxStorage by StorageMult. Boosts both
         the per-cargo storage limits and the overall depot cap.

    Baselines (per (delivery_point_full_name, index)) are captured
    on first apply, so polling every 5 seconds doesn't compound
    the effect on the same instance. Newly-loaded delivery points
    are baselined + scaled on the next poll.

    Server-side mod (host or dedicated). Requires UE4SS.

    Generated by Frog Mod Editor. Multipliers are hardcoded below
    — regenerate the mod from Frog to change them.
]]--

local CONFIG = {{
    ProductionMult = {production_speed_multiplier},
    StorageMult    = {warehouse_storage_multiplier},
    PollIntervalMs = 5000,
}}

local function Log(msg) print("[CryovacProductionStorageBoost] " .. msg) end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- ============================================================
-- Baselines: keyed by full_name and stored as a dict so we can
-- track each per-instance value independently.
--   prodBase[fullname][i] = vanilla ProductionSpeedMultiplier of cfg i
--   storeBase[fullname][i] = vanilla MaxStorage of storage cfg i
--   pointStoreBase[fullname] = vanilla AMTDeliveryPoint.MaxStorage
-- ============================================================
local prodBase = {{}}
local storeBase = {{}}
local pointStoreBase = {{}}

local function ApplyToPoint(point)
    local fullname = ""
    pcall(function() fullname = point:GetFullName() end)
    if fullname == "" then return 0, 0 end

    local prodApplied = 0
    local storeApplied = 0

    -- ── Production configs (TArray of FMTProductionConfig) ──
    local prodConfigs = SafeGet(point, "ProductionConfigs")
    if prodConfigs then
        local n = 0
        pcall(function() n = #prodConfigs end)
        if n > 0 and prodBase[fullname] == nil then prodBase[fullname] = {{}} end
        for i = 1, n do
            local cfg = prodConfigs[i]
            if cfg then
                local current = SafeGet(cfg, "ProductionSpeedMultiplier")
                if type(current) == "number" then
                    if prodBase[fullname][i] == nil then
                        prodBase[fullname][i] = current
                    end
                    local target = prodBase[fullname][i] * CONFIG.ProductionMult
                    if math.abs(current - target) > 0.001 then
                        local ok = pcall(function()
                            cfg.ProductionSpeedMultiplier = target
                        end)
                        if ok then prodApplied = prodApplied + 1 end
                    end
                end
            end
        end
    end

    -- ── Per-cargo storage configs (TArray of FMTDeliveryStorageConfig) ──
    local storeConfigs = SafeGet(point, "StorageConfigs")
    if storeConfigs then
        local n = 0
        pcall(function() n = #storeConfigs end)
        if n > 0 and storeBase[fullname] == nil then storeBase[fullname] = {{}} end
        for i = 1, n do
            local cfg = storeConfigs[i]
            if cfg then
                local current = SafeGet(cfg, "MaxStorage")
                if type(current) == "number" then
                    if storeBase[fullname][i] == nil then
                        storeBase[fullname][i] = current
                    end
                    local target = math.floor(storeBase[fullname][i] * CONFIG.StorageMult + 0.5)
                    if current ~= target then
                        local ok = pcall(function()
                            cfg.MaxStorage = target
                        end)
                        if ok then storeApplied = storeApplied + 1 end
                    end
                end
            end
        end
    end

    -- ── Top-level MaxStorage on the delivery point itself ──
    local pointMax = SafeGet(point, "MaxStorage")
    if type(pointMax) == "number" then
        if pointStoreBase[fullname] == nil then
            pointStoreBase[fullname] = pointMax
        end
        local target = math.floor(pointStoreBase[fullname] * CONFIG.StorageMult + 0.5)
        if pointMax ~= target then
            local ok = pcall(function() point.MaxStorage = target end)
            if ok then storeApplied = storeApplied + 1 end
        end
    end

    return prodApplied, storeApplied
end

local function ApplyToAllPoints()
    local points = FindAllOf("MTDeliveryPoint")
    if not points then return 0, 0, 0 end
    local count = 0
    pcall(function() count = #points end)

    local seen = 0
    local prodTotal = 0
    local storeTotal = 0

    for i = 1, count do
        local point = points[i]
        if point ~= nil then
            seen = seen + 1
            local prodApplied, storeApplied = ApplyToPoint(point)
            prodTotal = prodTotal + prodApplied
            storeTotal = storeTotal + storeApplied
        end
    end

    return seen, prodTotal, storeTotal
end

Log("=== Cryovac Production + Storage Boost Loading ===")
Log(string.format("Production=x%.2f  Storage=x%.2f",
    CONFIG.ProductionMult, CONFIG.StorageMult))

local lastSeen = -1
LoopAsync(CONFIG.PollIntervalMs, function()
    local seen, prodApplied, storeApplied = ApplyToAllPoints()
    if seen ~= lastSeen then
        Log(string.format("Poll: %d delivery points, %d production cfgs scaled, %d storage cfgs scaled this cycle",
            seen, prodApplied, storeApplied))
        lastSeen = seen
    end
    return false  -- keep looping
end)

Log("=== Cryovac Production + Storage Boost Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, Any]:
    """Coerce the config dict, clamping each multiplier into the
    declared 0.25–10.0 range. Anything non-numeric raises."""
    out: Dict[str, Any] = {}
    for s in SETTINGS:
        val = config.get(s.key, s.default)
        try:
            val = float(val)
        except (TypeError, ValueError):
            raise ValueError(f"{s.key} must be numeric")
        if not 0.25 <= val <= 10.0:
            raise ValueError(f"{s.key} = {val} out of range [0.25, 10.0]")
        out[s.key] = val
    return out


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        production_speed_multiplier=f"{cfg['production_speed_multiplier']:.3f}",
        warehouse_storage_multiplier=f"{cfg['warehouse_storage_multiplier']:.3f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    body = (
        f"Multipliers (applied every 5 seconds to every "
        f"AMTDeliveryPoint in the world):\n"
        f"  Production Speed:  x{cfg['production_speed_multiplier']:.2f}\n"
        f"  Warehouse Storage: x{cfg['warehouse_storage_multiplier']:.2f}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Every 5 seconds the mod scans every live AMTDeliveryPoint.\n"
        "For each, it walks two arrays:\n\n"
        "  1. ProductionConfigs[].ProductionSpeedMultiplier — multiplied\n"
        "     by the Production Speed slider value.\n\n"
        "  2. StorageConfigs[].MaxStorage AND the delivery point's\n"
        "     top-level MaxStorage — multiplied by the Warehouse\n"
        "     Storage slider value (rounded to the nearest integer).\n\n"
        "Baselines per (delivery_point, array_index) are captured on\n"
        "first sighting so repeated polls don't compound the effect\n"
        "on the same instance. Newly-loaded delivery points are\n"
        "baselined + scaled on the next poll.\n\n"
        "MULTIPLAYER\n"
        "-----------\n"
        "This mod runs server-side. The fields it modifies are not\n"
        "network-replicated as deltas, so for multiplayer the host has\n"
        "to run this mod for clients to see the boost. Single-player\n"
        "works either way.\n\n"
        "RECOMMENDED SETTINGS\n"
        "--------------------\n"
        "Production Speed 2x–3x is a noticeable speedup without\n"
        "trivializing the economy. Storage 2x–4x reduces the need\n"
        "for constant deliveries to keep production buildings fed.\n"
        "Above 5x things get arcade-y; the 10x slider cap is for\n"
        "sandbox builds.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
