"""Cryovac Skip Night — jumps the in-game clock to sunrise whenever
nighttime is detected. Doesn't modify game clock speed — lets vanilla
handle time advancement."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacSkipNight'

UI_TITLE = 'Skip Night'

UI_DESCRIPTION = (
    "When nighttime starts, jumps the in-game time to sunrise so you "
    "don't have to grind through dark hours. Doesn't change the game's "
    "clock speed \u2014 vanilla time keeps advancing between sunrise and "
    "sunset.\n\n"
    "Sunrise and sunset times are adjustable below. Defaults are 06:00 "
    "and 20:00."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'day_start_hour': 6.0,
    'day_end_hour':   20.0,
}

SETTINGS = [
    Setting(
        key='day_start_hour',
        label='Sunrise',
        kind='float',
        default=6.0,
        min_value=0.0,
        max_value=12.0,
        step=0.5,
        suffix=':00',
        tooltip='Hour of day considered "sunrise". When night is skipped, '
                'the clock jumps to this hour.',
    ),
    Setting(
        key='day_end_hour',
        label='Sunset',
        kind='float',
        default=20.0,
        min_value=12.0,
        max_value=24.0,
        step=0.5,
        suffix=':00',
        tooltip='Hour of day considered "sunset". Time >= this triggers '
                'the skip on the next poll.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Skip Night
    ===================
    Skips night entirely. When nighttime is detected, jumps to sunrise.
    Does NOT modify the game's clock speed - lets vanilla handle
    time advancement so the clock actually moves.

    Generated by Frog Mod Editor. Sunrise / sunset hours are hardcoded
    below - regenerate the mod from Frog to change them.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    DayStartHour   = {day_start_hour},
    DayEndHour     = {day_end_hour},
    PollIntervalMs = 1000,
}}

local function Log(msg)
    print("[CryovacSkipNight] " .. msg)
end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local function IsNight(t)
    return t >= CONFIG.DayEndHour or t < CONFIG.DayStartHour
end

Log("=== Cryovac Skip Night Loading ===")
Log("Sunrise: " .. CONFIG.DayStartHour .. ":00  Sunset: " .. CONFIG.DayEndHour .. ":00")

local skippedThisNight = false

LoopAsync(CONFIG.PollIntervalMs, function()
    local sunSkys = FindAllOf("MTSunSky")
    local currentTime = nil
    if sunSkys then
        for _, sun in ipairs(sunSkys) do
            currentTime = SafeGet(sun, "SolarTime")
            if currentTime then break end
        end
    end

    if not currentTime then return false end

    local isNight = IsNight(currentTime)

    if isNight and not skippedThisNight then
        Log("Night detected (time=" .. string.format("%.2f", currentTime) .. "), skipping to sunrise")

        local controllers = FindAllOf("MotorTownPlayerController")
        if controllers then
            for _, pc in ipairs(controllers) do
                local currentSpeed = nil
                local configs = FindAllOf("MTTimeOfDayConfig")
                if configs then
                    for _, config in ipairs(configs) do
                        local todConfig = SafeGet(config, "TimeOfDayConfig")
                        if todConfig then
                            currentSpeed = SafeGet(todConfig, "Speed")
                            break
                        end
                    end
                end

                local speed = currentSpeed or 0.01
                pcall(function()
                    pc:ClientSetTimeOfDay(CONFIG.DayStartHour, speed)
                end)
                Log("ClientSetTimeOfDay(" .. CONFIG.DayStartHour .. ", " .. string.format("%.6f", speed) .. ")")
            end
        end

        if sunSkys then
            for _, sun in ipairs(sunSkys) do
                sun.SolarTime = CONFIG.DayStartHour
            end
        end

        local configs = FindAllOf("MTTimeOfDayConfig")
        if configs then
            for _, config in ipairs(configs) do
                local todConfig = SafeGet(config, "TimeOfDayConfig")
                if todConfig then
                    todConfig.Start = CONFIG.DayStartHour
                end
            end
        end

        skippedThisNight = true

    elseif not isNight then
        if skippedThisNight then
            Log("Daytime (time=" .. string.format("%.2f", currentTime) .. ")")
            skippedThisNight = false
        end
    end

    return false
end)

Log("=== Cryovac Skip Night Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> Dict[str, float]:
    start = float(config.get('day_start_hour', DEFAULT_CONFIG['day_start_hour']))
    end = float(config.get('day_end_hour', DEFAULT_CONFIG['day_end_hour']))
    if not 0.0 <= start < 24.0:
        raise ValueError(f"day_start_hour {start} out of [0, 24)")
    if not 0.0 < end <= 24.0:
        raise ValueError(f"day_end_hour {end} out of (0, 24]")
    if end <= start:
        raise ValueError(f"day_end_hour ({end}) must be > day_start_hour ({start})")
    return {'day_start_hour': start, 'day_end_hour': end}


def generate_main_lua(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(
        day_start_hour=f"{cfg['day_start_hour']:.1f}",
        day_end_hour=f"{cfg['day_end_hour']:.1f}",
    )


def generate_readme(config: Dict[str, Any]) -> str:
    cfg = _validate(config)
    body = (
        f"Sunrise: {cfg['day_start_hour']:.1f}:00\n"
        f"Sunset:  {cfg['day_end_hour']:.1f}:00\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Polls every second. When SolarTime falls in the night window\n"
        "(before sunrise or after sunset), the mod:\n"
        "  - Calls ClientSetTimeOfDay(<sunrise>, <current_speed>) on\n"
        "    every MotorTownPlayerController\n"
        "  - Sets MTSunSky.SolarTime = sunrise\n"
        "  - Sets MTTimeOfDayConfig.TimeOfDayConfig.Start = sunrise\n"
        "Vanilla time speed is preserved; once it's daytime the mod\n"
        "stays out of the way until the next night cycle.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    cfg = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info=cfg,
    )


import sys as _sys
register(_sys.modules[__name__])
