"""Cryovac Slow Decay — compensates for the C++-hardcoded town bonus
decay rate by re-adding a fraction of any drop each poll. Effectively
scales the observed decay speed by (1 - DecayReduction)."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacSlowDecay'

UI_TITLE = 'Slow Decay'

UI_DESCRIPTION = (
    "Slows the decay of town coverage rates: Food Supply, Bus Transport, "
    "Taxi Transport, Police Patrol, and Garbage Collection. Vanilla Motor "
    "Town decays these continuously in C++ and the speed isn't "
    "configurable \u2014 this mod polls every 2 seconds, detects any drop, "
    "and re-adds a fraction of it back so the effective decay is "
    "slower.\n\n"
    "<b>0.0\u00d7 \u2013 0.9\u00d7</b> \u2014 reduce the decay rate on population "
    "bonuses (0.5\u00d7 = decay runs at half speed).<br>"
    "<b>1.0\u00d7</b> \u2014 disable decay entirely; population bonuses never "
    "fall on their own."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'decay_reduction': 0.5,
}

SETTINGS = [
    Setting(
        key='decay_reduction',
        label='Decay reduction',
        kind='slider',
        default=0.5,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        suffix='\u00d7',
        tooltip='Fraction of each observed drop to add back. '
                '0 = vanilla, 0.5 = half decay speed, 1 = disabled.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Slow Decay
    ===================
    Slows the C++-hardcoded town coverage decay.

    All five rates (Food, Bus, Taxi, Police, Garbage) naturally decay
    over time. Each poll cycle, this mod re-adds (DecayReduction * drop)
    back to the observed rate:

      0.0x  vanilla (no compensation)
      0.5x  decay runs at half speed
      1.0x  decay disabled entirely

    Generated by Frog Mod Editor. DecayReduction is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    DecayReduction = {decay_reduction},
    PollIntervalMs = 2000,
}}

local RATE_FIELDS = {{
    "FoodSupplyRate",
    "BusTransportRate",
    "TaxiTransportRate",
    "PolicePatrolRate",
    "GarbageCollectRate",
}}

local function Log(msg)
    print("[CryovacSlowDecay] " .. msg)
end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

-- Stable per-zone string key. FName wrappers don't always stringify
-- usefully via tostring() in UE4SS - it can return the same userdata
-- address for different zones, which collapses lastRates into one
-- bucket and causes cross-zone bleed. We use :ToString() (UE4SS's
-- FName accessor) with a zone-index fallback.
local function ZoneStableKey(zone, index)
    local zoneName = SafeGet(zone, "ZoneKey")
    if zoneName then
        local ok, s = pcall(function() return zoneName:ToString() end)
        if ok and type(s) == "string" and s ~= "" and s ~= "None" then
            return s
        end
    end
    return "<idx:" .. tostring(index) .. ">"
end

-- Keyed by "zoneKey.fieldName". Value is the last rate WE observed
-- in that zone/field combo. Only written after a successful read,
-- never from a cross-zone source.
local lastRates = {{}}

local function ApplyDecayCompensation()
    local gameStates = FindAllOf("MotorTownGameState")
    if not gameStates then return end

    for _, gs in ipairs(gameStates) do
        local hotState = SafeGet(gs, "Net_HotState")
        if not hotState then goto nextGS end

        local zoneStates = SafeGet(hotState, "ZoneStates")
        if not zoneStates then goto nextGS end

        local zoneCount = 0
        pcall(function() zoneCount = #zoneStates end)
        if zoneCount == 0 then goto nextGS end

        -- Pre-compute every zone's stable key. If any two zones hash
        -- to the same key we CANNOT safely key lastRates by zone, so
        -- abort the whole cycle. Previous behaviour was to silently
        -- cross-pollinate, which produced "all towns go up" bleed.
        local zoneKeys = {{}}
        local seen = {{}}
        local collision = false
        for i = 1, zoneCount do
            local k = ZoneStableKey(zoneStates[i], i)
            if seen[k] then
                Log(string.format(
                    "abort cycle: duplicate zone key '%s' at indices %d and %d "
                 .. "(UE4SS FName stringify collision) - rates left untouched this tick",
                    k, seen[k], i))
                collision = true
                break
            end
            seen[k] = i
            zoneKeys[i] = k
        end
        if collision then goto nextGS end

        for i = 1, zoneCount do
            local zone = zoneStates[i]
            local zoneKey = zoneKeys[i]

            for _, field in ipairs(RATE_FIELDS) do
                local current = SafeGet(zone, field)
                if type(current) ~= "number" then goto nextField end

                local mapKey = zoneKey .. "." .. field
                local prev = lastRates[mapKey]

                if prev and current < prev then
                    local drop = prev - current
                    local compensation = drop * CONFIG.DecayReduction
                    local newRate = current + compensation
                    -- HARD CAP: never write above the previous observation.
                    -- Compensation slows a drop; it must never raise a rate
                    -- past where it already was.
                    if newRate > prev then newRate = prev end
                    if newRate > 1.0 then newRate = 1.0 end
                    if newRate < 0.0 then newRate = 0.0 end
                    zone[field] = newRate
                    Log(string.format(
                        "%s.%s: %.4f -> %.4f (decay %.4f, compensated +%.4f)",
                        zoneKey, field, prev, newRate, drop, compensation))
                    lastRates[mapKey] = newRate
                else
                    -- Rise (player activity) or first observation: just
                    -- record the live value, no write-back.
                    lastRates[mapKey] = current
                end

                ::nextField::
            end
        end

        ::nextGS::
    end
end

Log("=== Cryovac Slow Decay Loading ===")
do
    local r = CONFIG.DecayReduction
    local descr
    if r <= 0 then
        descr = "vanilla (no compensation)"
    elseif r >= 1 then
        descr = "decay disabled (rates never fall on their own)"
    else
        descr = string.format("%.0f%% of each drop restored (decay at %.0f%% of vanilla speed)",
            r * 100, (1.0 - r) * 100)
    end
    Log("Decay reduction: " .. descr)
end
Log("Tracking rates: " .. table.concat(RATE_FIELDS, ", "))
Log("Poll interval: " .. CONFIG.PollIntervalMs .. "ms")

LoopAsync(CONFIG.PollIntervalMs, function()
    ApplyDecayCompensation()
    return false
end)

Log("=== Cryovac Slow Decay Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    val = float(config.get('decay_reduction', DEFAULT_CONFIG['decay_reduction']))
    if not 0.0 <= val <= 1.0:
        raise ValueError(f"decay_reduction {val} out of [0.0, 1.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(decay_reduction=f"{val:.3f}")


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    if val <= 0.0:
        descr = "vanilla (no compensation)"
    elif abs(val - 1.0) < 1e-6:
        descr = "decay disabled (rates never fall on their own)"
    else:
        descr = (f"{val * 100:.0f}% of each drop restored "
                 f"(effective decay = {(1.0 - val) * 100:.0f}% of vanilla speed)")
    body = (
        f"Decay reduction: {val:.2f}x  \u2014  {descr}\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Polls every 2 seconds. For each zone, reads the five coverage\n"
        "rates (Food, Bus, Taxi, Police, Garbage). If a rate dropped\n"
        "since the last poll, adds (drop * DecayReduction) back to the\n"
        "rate so the effective decay runs slower. At 1.0x the drop is\n"
        "fully restored, which disables decay entirely.\n\n"
        "Player activity that INCREASES a rate is not touched.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'decay_reduction': val},
    )


import sys as _sys
register(_sys.modules[__name__])
