"""Cryovac Slow Decay — compensates for the C++-hardcoded town bonus
decay rate by re-adding a fraction of any drop each poll. Effectively
scales the observed decay speed by (1 - DecayReduction)."""
from __future__ import annotations

from typing import Any, Dict

from . import register, DEFAULT_OUTPUT_DIR, Setting
from ._shared import render_install_readme, write_mod_folder


MOD_NAME = 'CryovacSlowDecay'

UI_TITLE = 'Slow Decay'

UI_DESCRIPTION = (
    "Slows the decay of town coverage rates: Food Supply, Bus Transport, "
    "Taxi Transport, Police Patrol, and Garbage Collection. Vanilla C++ "
    "decays these continuously and the speed isn't configurable — this "
    "mod polls every 2 seconds, detects any drop, and re-adds a fraction "
    "back so the effective decay is slower.\n\n"
    "<b>Decay Reduction = 0.0</b> \u2014 no compensation (vanilla).<br>"
    "<b>Decay Reduction = 0.5</b> \u2014 half the decay speed (default).<br>"
    "<b>Decay Reduction = 1.0</b> \u2014 no decay at all (ratings never drop on their own)."
)

DEFAULT_CONFIG: Dict[str, Any] = {
    'decay_reduction': 0.5,
}

SETTINGS = [
    Setting(
        key='decay_reduction',
        label='Decay reduction',
        kind='float',
        default=0.5,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        suffix='',
        tooltip='Fraction of each observed drop to add back. '
                '0 = vanilla, 0.5 = half decay speed, 1 = frozen.',
    ),
]


_MAIN_LUA_TEMPLATE = '''--[[
    Cryovac: Slow Decay
    ===================
    Cuts town bonus decay rates by (DecayReduction * 100)%.

    All five coverage rates (Food, Bus, Taxi, Police, Garbage) naturally
    decay over time in C++. Since the decay speed isn't configurable, this
    mod compensates by tracking each rate and adding back a fraction of
    any drop detected each poll cycle.

    Generated by Frog Mod Editor. DecayReduction is hardcoded below -
    regenerate the mod from Frog to change it.

    Runs on SERVER (host or dedicated). Requires UE4SS.
]]--

local CONFIG = {{
    DecayReduction = {decay_reduction},
    PollIntervalMs = 2000,
}}

local RATE_FIELDS = {{
    "FoodSupplyRate",
    "BusTransportRate",
    "TaxiTransportRate",
    "PolicePatrolRate",
    "GarbageCollectRate",
}}

local function Log(msg)
    print("[CryovacSlowDecay] " .. msg)
end

local function SafeGet(obj, prop)
    local ok, val = pcall(function() return obj[prop] end)
    if ok then return val end
    return nil
end

local lastRates = {{}}

local function MakeKey(zoneName, field)
    return tostring(zoneName) .. "." .. field
end

local function ApplyDecayCompensation()
    local gameStates = FindAllOf("MotorTownGameState")
    if not gameStates then return end

    for _, gs in ipairs(gameStates) do
        local hotState = SafeGet(gs, "Net_HotState")
        if not hotState then goto nextGS end

        local zoneStates = SafeGet(hotState, "ZoneStates")
        if not zoneStates then goto nextGS end

        for i = 1, #zoneStates do
            local zone = zoneStates[i]
            local zoneName = SafeGet(zone, "ZoneKey")
            if not zoneName then goto nextZone end

            for _, field in ipairs(RATE_FIELDS) do
                local current = SafeGet(zone, field)
                if not current then goto nextField end

                local key = MakeKey(zoneName, field)
                local prev = lastRates[key]

                if prev and current < prev then
                    local drop = prev - current
                    local compensation = drop * CONFIG.DecayReduction
                    local newRate = current + compensation
                    if newRate > 1.0 then newRate = 1.0 end
                    if newRate < 0.0 then newRate = 0.0 end
                    zone[field] = newRate
                    Log(string.format("%s.%s: %.4f -> %.4f (decay %.4f, compensated +%.4f)",
                        tostring(zoneName), field, prev, newRate, drop, compensation))
                    lastRates[key] = newRate
                else
                    lastRates[key] = current
                end

                ::nextField::
            end

            ::nextZone::
        end

        ::nextGS::
    end
end

Log("=== Cryovac Slow Decay Loading ===")
Log("Decay reduction: " .. (CONFIG.DecayReduction * 100) .. "% (multiply decay by " .. (1.0 - CONFIG.DecayReduction) .. ")")
Log("Tracking rates: " .. table.concat(RATE_FIELDS, ", "))
Log("Poll interval: " .. CONFIG.PollIntervalMs .. "ms")

LoopAsync(CONFIG.PollIntervalMs, function()
    ApplyDecayCompensation()
    return false
end)

Log("=== Cryovac Slow Decay Loaded ===")
'''


def _validate(config: Dict[str, Any]) -> float:
    val = float(config.get('decay_reduction', DEFAULT_CONFIG['decay_reduction']))
    if not 0.0 <= val <= 1.0:
        raise ValueError(f"decay_reduction {val} out of [0.0, 1.0]")
    return val


def generate_main_lua(config: Dict[str, Any]) -> str:
    val = _validate(config)
    return _MAIN_LUA_TEMPLATE.format(decay_reduction=f"{val:.3f}")


def generate_readme(config: Dict[str, Any]) -> str:
    val = _validate(config)
    pct = val * 100.0
    effective = (1.0 - val) * 100.0
    body = (
        f"Decay Reduction: {val:.2f} ({pct:.0f}% of each drop restored)\n"
        f"Effective decay speed: {effective:.0f}% of vanilla\n\n"
        "WHAT THIS MOD DOES\n"
        "------------------\n"
        "Polls every 2 seconds. For each zone, reads the five coverage\n"
        "rates (Food, Bus, Taxi, Police, Garbage). If a rate dropped\n"
        "since the last poll, adds back (drop * DecayReduction) to\n"
        "slow the effective decay.\n\n"
        "Player activity that INCREASES a rate is not touched. Only\n"
        "natural decay gets compensated.\n"
    )
    return render_install_readme(MOD_NAME, body)


def deploy(config: Dict[str, Any], output_dir: str = None) -> Dict[str, Any]:
    out_dir = output_dir or DEFAULT_OUTPUT_DIR
    val = _validate(config)
    return write_mod_folder(
        mod_name=MOD_NAME,
        output_dir=out_dir,
        main_lua=generate_main_lua(config),
        readme=generate_readme(config),
        mod_info={'decay_reduction': val},
    )


import sys as _sys
register(_sys.modules[__name__])
